"""Bairisch - München/Oberbayern, wie heute wirklich geredet wird.

Diese Fassung wurde durchgehend überarbeitet. Vorher standen hier zwei
Schreibweisen nebeneinander, und im später ergänzten Teil war der
Wiener Ton durchgeschlagen.

Die Regeln, nach denen hier geschrieben wird:

* a bleibt a:         was, macha, sagn, ham, Wassa, Dog
                      (Wien macht daraus wos, mochn, sogn, hom, Wossa)
* ei wird zu oa:      hoass -> hoaß, woaß, oans, zwoa, koa, kloa, hoam
* r wird zum Vokal:   Wassa, Filta, Zimma, weida, bessa, lauta
* l wird zum Vokal:   vui, ois, voi, hoit, schnei, stei, selba
* uo wird zu ua:      guad, Tuach, Bruada, ruafn, Fiaß, Plural Tiacha
* schauen -> schaugn: der klarste bairische Marker, nie "schaun"
* p wird zu b:        bassd, butzn, bisserl
* an- wird zu o-:     ogreifn, odockn, ofanga, obglehnt
* Richtungswörter:   eini, aussa, owa, auffi, umanand
* kommen -> i kimm, nicht -> ned, nachher -> nacha, später -> spata

Zwei Fehler der Vorfassung sind raus: "bittschön" (bairisch heißt schön
"schee") und "Fuiast nach" (das ist Präsens, gebraucht wird der
Imperativ "Fui nach"). Nebenbei sagt ein granteliger Bayer nicht in
jedem zweiten Satz bitte - das steht jetzt nur noch dort, wo es sitzt.

Der Grant ist bewusst sparsam dosiert: bei fast 600 Ansagen wird
Dauergranteln anstrengend, und Fehlermeldungen müssen verständlich
bleiben.
"""

from __future__ import annotations

from . import muster
from ..i18n import t

KEY = "bayerisch"
NAME = t("bayerisch.name")
BESCHREIBUNG = t("bayerisch.beschreibung")
LANG_ID = "BAYERN"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "I wart auf's Netzwerk.",
    2: "Mit'm WLAN hod's ned highaut. Schaug da s Passwort no amoi o.",
    3: "I kimm ned auf'n Server. Schaug da dei Netzwerk o.",
    4: "I bin aus'm Netzwerkmodus aussa.",
    5: "Netzwerk bassd, i bin drin.",
    6: "Mit'm Netzwerk hod's ned highaut. Probier's spata no amoi.",
    304: "S Netzwerk is verbundn.",
    306: "Des hob i ned verstandn. Richt zerst s Netzwerk ei.",
    313: "S Netz is schlecht. Stei mi wo hi, wo da Empfang bessa is.",
    377: "S Netzwerk lasst si ned einrichtn. Wend di an 'n Kundendienst.",
    378: "S Passwort bassd ned. Richt s Netzwerk no amoi ei.",
    379: "I find koa WLAN. Nimm s Zwoakommavier-Gigahertz-Netz.",
    380: "I hob koa IP-Adress kriagt. Schaug amoi in dein Router.",
    381: "I kimm ned auf'n Server. Wend di an 'n Kundendienst.",
    382: "I kimm ned ins Netz. Schaug, ob dei Internet geht.",
    383: "S Netzwerk lasst si ned einrichtn. Wend di an 'n Kundendienst.",
    385: "I verbind mi grad mit'm Netzwerk.",

    # --- Reinigung ---------------------------------------------------
    7: "So, packma's. I fang zum Saugn o.",
    8: "I mach den oan Fleck sauba.",
    9: "De eiplante Reinigung geht jetzt los.",
    10: "I mach weida, wo i aufghört hob.",
    11: "I mach a Pausn.",
    12: "Fertig samma. Ois sauba.",
    54: "Bassd, i saug weida.",
    55: "Bassd, i fahr weida zur Station.",
    56: "I mach des Zimma sauba.",
    57: "I mach de Zone sauba.",
    58: "I mach mei Arbeit weida.",
    61: "I fang zum Wischn o.",
    62: "Du steuerst mi jetzt selba.",
    64: "Des hod ned highaut. I fahr zur Station.",
    65: "I fahr weida zur Station.",
    77: "Stei mi auf an Hartbodn, nacha fang i o.",
    82: "I zeichne jetzt a Kartn vo dera Wohnung.",
    83: "I zeichne weida an da Kartn.",
    84: "D'Kartn is fertig.",
    85: "Bassd, i zeichne weida.",
    86: "Des hod ned highaut. I fang mit'm Zeichna neich o.",
    105: "Auf geht's, i fang o.",
    126: "I fang zum Saugn o.",
    127: "I mach an Fleck sauba.",
    128: "I wisch an Fleck.",
    129: "De eiplante Reinigung geht los.",
    130: "S eiplante Zeichna geht los.",
    133: "I mach de ausgwählten Zimma sauba.",
    134: "I wisch de ausgwählten Zimma.",
    135: "I mach de Zone sauba.",
    136: "I wisch de Zone.",
    137: "I saug weida.",
    138: "I wisch weida.",
    139: "I kimm zruck.",
    143: "Fertig. Do schaugt's jetzt sauba aus, gell.",
    144: "Gwischt hob i a scho.",
    145: "Bassd, i saug weida.",
    146: "Bassd, i zeichne weida.",
    150: "Do kimm i ned hi. Nimm d'Sperrzonen weg.",
    152: "Mei Weg is verstellt. Nimm d'Sperrzonen weg oda stei mi woanders hi.",
    163: "I schaug grad mit da Kamera.",
    164: "So, des war's. Feierabend.",
    171: "De gscheide Hindernisumfahrung is o.",
    172: "De gscheide Hindernisumfahrung is aus.",
    257: "D'Kameraüberwachung is aus.",
    280: "I fang mit dera eigstellten Reinigung o.",
    321: "I fang mit'm gscheidn Fleckenwischn o.",
    344: "Bassd scho, i saug zerst und wisch nacha.",
    362: "S Wischtuach sitzt ned richtig. Nacha saug i hoit bloß.",
    363: "S Saugn is fertig, jetzt wisch i.",
    366: "Do is a Fleck, i mach'n sauba.",
    367: "Bassd scho, i mach 'n Fleck sauba.",
    368: "Do is a Fleck. I mach'n sauba, sobald i gwaschn hob.",
    369: "Bassd scho, i mach do sauba.",
    424: "I woaß ned, wo i bin. Stei mi auf a freie Fläch und fang neich o.",
    433: "I mach no a Extrarundn.",
    434: "D'Extrarundn is fertig, i mach normal weida.",
    435: "I fahr aus dem Bereich aussa.",
    450: "In ana Sperrzon fang i ned o. Stei mi woanders hi.",
    451: "Im verstecktn Bereich fang i ned o. Stei mi woanders hi.",
    677: "Do kimm i ned hi. Nimm d'Sperrzonen oda d'Schwelln weg.",
    678: "Mei Weg is verstellt. Nimm d'Sperrzonen oda d'Schwelln weg.",
    679: "I steh in ana Sperrzon. Hoi mi do aussa.",
    680: "I zeichne zerst a Kartn, nacha mach i sauba.",
    681: "Bassd scho, i mach weida.",

    # --- Akku und Laden ----------------------------------------------
    13: "I fahr hoam zum Aufladn.",
    14: "Mei Batterie is boid leer. I fahr hoam zum Ladn und mach nacha weida.",
    17: "Stei mi bittschee wieda auf d'Station.",
    18: "I lad grad auf.",
    19: "Nimm mi vo da Station owa, bevor'st mi ausschoitst.",
    20: "Mei Batterie is boid leer.",
    21: "Batterie leer. I schoit mi jetzt ab.",
    25: "Da Akku is z'schwach für de eiplante Reinigung.",
    47: "I fang zum Ladn o.",
    48: "Batterie is schwach, i fahr zur Station.",
    50: "Mit'm Ladn stimmt was ned. Butz ma de Kontakte.",
    87: "Batterie schwach, i fahr zur Station.",
    301: "I lad grad auf.",
    302: "I bin grad am Werkeln.",
    303: "I ruh mi grad aus.",
    307: "I lad grad auf.",
    692: "I fahr zum Ladn. A extra Reinigung geht grad ned.",
    708: "Da Weg zur Ladestation is zua. Schaug nach, ob was im Weg steht.",
    812: "Stei mi zum Ladn in d'Station.",

    # --- Station und Wischen -----------------------------------------
    59: "D'Kartn is fertig. Nimm 'n Wassatank aussa.",
    106: "I wasch mei Wischtuach.",
    107: "I trockne meine Wischtiacha.",
    110: "I saug mein Staub aus.",
    111: "Ma fehln d'Wischtiacha. Mach's ma dro.",
    112: "Stei mi zerst amoi in d'Station.",
    113: "Fertig. Leer 'n Schmutzwassatank aus.",
    114: "D'Wischtiacha san dro.",
    115: "D'Wischtiacha san abgnomma.",
    140: "A neiche Umgebung. I fahr zur Station.",
    148: "I fahr zur Station und mach mi selba sauba.",
    169: "D'Wischtiacha san trocken.",
    177: "I fahr los.",
    179: "S Wischtuach is sauba. Bloß s Frischwassa geht ma aus.",
    181: "Ma geht s Wassa aus. Fui ma bittschee nach.",
    186: "Schaug da 'n Frischwassatank o.",
    187: "Des dauert so fümf bis zehn Minutn.",
    188: "I dock automatisch o.",
    209: "Bassd scho, i fahr zur Station und wasch mei Wischtuach.",
    210: "I wasch d'Wischtiacha.",
    211: "Absaugn geht nur, wenn i in da Station steh.",
    212: "Bassd scho, i saug mi aus.",
    213: "Trockna geht nur, wenn i in da Station steh.",
    214: "I trockne grad.",
    215: "Bassd scho, i fang zum Trockna o.",
    216: "Do muass zerst s Wischtuach dro.",
    278: "Bassd scho, s Trockna is fertig.",
    298: "I mach s Waschbrett sauba.",
    305: "Bassd scho, i mach s Waschbrett sauba. Butz's innen mit ana Bürstn oda am Tuach.",
    311: "D'Wischtiacha san abgnomma.",
    318: "Mei Wischtuach is wieda sauba.",
    349: "Schaug, dass d'Station Strom hod, und stei mi drauf.",
    350: "I fang mit'm Einrichtn vo da Station o.",
    351: "D'Station is eigricht.",
    352: "S Einrichtn hod ned highaut. Schaug in da App nach.",
    360: "I loss s Wassa aus'm Tank.",
    361: "S Wassa is draußn.",
    371: "Nimm s Waschbrett aussa.",
    372: "S Frischwassa lauft eini.",
    373: "S Wassa is drin. Wart zehn Sekundn, nacha geht's weida.",
    374: "Butz 'n Bodn vo da Station mit ana Bürstn oda am Tuach.",
    375: "Schieb 'n Dreck zum Absaugn hi. Des dauert a bisserl.",
    376: "S Absaugn is fertig. Butz s Waschbrett extra und setz's wieda eini.",
    396: "I leer s Wassamodul aus. Des dauert a bisserl.",
    397: "S Wassa is obn und untn draußn.",
    398: "D'Kartn is fertig. Schaug's da in da App o und stei mi zruck auf d'Station.",
    399: "Da Test is fertig. Stei mi zruck auf d'Station.",
    400: "D'Selbstreinigung is fertig. Stei mi jetzt auf 'n richtign Stock.",
    401: "Stei mi auf d'Station, nacha fang i mit da Selbstreinigung o.",
    478: "Wenn i gwaschn hob, mach i mit'm Saugn weida.",
    479: "Bassd scho, fang dei Arbeit neich o.",
    480: "Fui gnua Wassa eini, dass's für's Nächste reicht.",
    481: "I leer 'n Handstaubsauger aus.",
    482: "I leer 'n Handstaubsauger aus. Mi selba saug i nacha aus.",
    483: "I leer 'n Handstaubsauger aus. S Wischtuach wasch i nacha.",
    484: "I leer 'n Handstaubsauger aus. Gsaugt wird nacha.",
    485: "I saug mi grad aus. Da Handstaubsauger kimmt nacha.",
    486: "I wasch grad s Wischtuach. Da Handstaubsauger kimmt nacha.",
    487: "Schaug, dass i in da Station steh.",
    636: "Mei Wischtuach is saudreckert. I muass zur Station.",
    638: "I saug mi weida aus.",
    661: "I mach s Waschbrett sauba. Des dauert a knappe Minutn.",
    662: "I mach elektrolysiert's Wassa zum Butzn.",
    689: "I fang zum Trockna vom Staubbehälter und Beitl o.",
    690: "S Trockna vom Staubbehälter und Beitl is gstoppt.",
    691: "Da Mopp wird grad gwaschn. Probier's spata no amoi.",
    701: "D'Platte is hoaß. Ned ogreifn.",
    703: "I fang mit da Staub- und Mopptrocknung o.",
    704: "D'Mopptrocknung is pausiert.",
    711: "D'Desinfektion fangt o.",
    712: "S Waschbrett is hoaß. Ned ogreifn.",
    715: "In da Station fehlt da Mopp. Setz eahm eini, nacha mach i weida.",
    716: "In da Station fehlt da Mopp. Setz eahm eini - solang arbat i im Standardmodus.",
    717: "Da Mopp sitzt ned richtig. Ruck eahm zrecht, nacha mach i weida.",
    722: "Da Mopp kimmt in hoaß's Wassa, damit er warm wird. Drum dauert's a bisserl länga. Hob a weng Geduld.",
    724: "Da Mopp liegt in da Station ned richtig. Ruck eahm glei zrecht.",
    728: "I fang mit da Bodnpfleg o.",
    729: "Da Mopp wird grad gwechslt. Probier's spata no amoi.",
    731: "Mei Schmutzwassatank is voi. Stei mi zruck auf d'Station, dass i 'n Mopp waschn ko.",
    752: "I mach mit da Bodnpfleg weida.",
    754: "I hob mi gfundn. I mach mit da Bodnpfleg weida.",
    757: "Mei Schmutzwassatank is voi. Leer eahm glei aus.",
    758: "Z'weng Wassa. Stei mi zruck auf d'Station und druck auf Start, nacha wird nachgfüllt.",
    765: "Da Mopp wird grad gwechslt. Probier's spata no amoi.",
    775: "Solang da Mopp lauft, lass d'Klappn zua.",
    779: "D'Zeit fürs Mopp-Rausnehma is um. I hör auf.",
    780: "S Aufnehma oda Ablegn vom Mopp hod ned klappt. Nimm 'n Mopp aus da Halterung und leg eahm wieda ins Fach an da Klappn.",
    784: "Wenn Schritt oans fertig is, fahr i vo alloa aus da Station.",
    785: 'Mach d\'Waschbrett-Basis mit ana Bürstn oda am Tuach sauba. Nacha tippst in da App auf "Reinigung beendn".',
    786: "D'Waschbrett-Basis is sauba.",
    787: "I fahr vo alloa zur Station zruck und mach 'n Mopp sauba und trocken.",
    795: "I fang mit da Reinigung vo da Waschbrett-Basis o. Des dauert ungefähr zwoa Minutn.",
    798: "D'Selbstreinigung vo da Station dauert ungefähr vier Minutn. Schieb mi solang ned umanand.",
    805: "I fang o, den grobn Dreck aufz'saugn.",
    813: "I fang mit da kräftign Absaugung vom Dreck o.",
    814: "I fang mit da Selbstreinigung vo da Station und da kräftign Absaugung o.",
    849: "I fang zum Trockna vom Staubbehälter und Beitl o.",
    850: "S Trockna vom Staubbehälter und Beitl is gstoppt.",
    857: "Setz bittschee s Waschbrett eini.",

    # --- Fehler und Wartung ------------------------------------------
    24: "Schaug amoi, ob da Wassatank richtig drin sitzt.",
    34: "Do fehlt a Teil. Steck's bittschee eini.",
    35: "Mit da Hauptbürstn stimmt was ned. Butz's ma bittschee.",
    36: "Mit da Seitenbürstn stimmt was ned. Butz's ma bittschee.",
    37: "Mit'm rechtn Radl stimmt was ned.",
    38: "Mit'm linkn Radl stimmt was ned.",
    39: "Meine Radln ham koan Bodnkontakt. Butz de Absturzsensorn.",
    40: "Zefix, i häng fest. Machst mi amoi frei?",
    41: "Meine Radln ham koan Bodnkontakt. Stei mi woanders hi.",
    42: "Schaug da mein Filta o.",
    43: "Mit meim Stoßbügel stimmt was ned. Druck amoi sanft drauf.",
    44: "Do stimmt was ned. Schaug in da Anleitung nach.",
    52: "I steh schiaf. Stei mi bittschee grad hi.",
    66: "Mei Filta is hi. Tausch'n aus.",
    67: "De Seitenbürstn is hi. Tausch's aus.",
    68: "De Hauptbürstn is hi. Tausch's aus.",
    71: "Schaug amoi, ob am Laser-Abstandssensor was klemmt.",
    72: "D'Abdeckung vom Lasersensor klemmt.",
    73: "Mit'm Kantensensor stimmt was ned.",
    75: "Da Filta is feucht oda verstopft.",
    81: "Mit'm Teppichsensor stimmt was ned.",
    91: "Da Frischwassatank fehlt. Setz'n eini.",
    93: "Z'weng Wassa drin. Fui bittschee nach.",
    97: "Do fehlt da Staubbeitl.",
    101: "D'Klappn vo da Absaugstation is offen oda da Beitl fehlt. Mach d'Klappn zua oda leg an Beitl eini.",
    102: "Da Staubbeitl is voi oda da Kanal is verstopft.",
    104: "S Waschbrett is ned drin. Setz's eini und mach de Klammern auf beidn Seitn fest.",
    108: "Mit'm Wassastand vom Waschbrett stimmt was ned. Butz's.",
    109: "Mit'm Schmutzwassatank stimmt was ned. Schaug, ob er drin und leer is.",
    118: "D'Knöpf san gsperrt. Hoit d'Tastn an da Station druckt, nacha geht's.",
    142: "S Wischtuach is hi. Tausch's aus.",
    156: "Mei Wischtuach is ned dro.",
    166: "Do hod si was in mei Wischtuach eigwicklt. Mach's weg.",
    170: "D'Tastnsperr is o. Hoit d'Tastn an da Station druckt, nacha geht's wieda auf.",
    173: "Tausch bittschee s Silberionen-Modul aus.",
    244: "D'Reinigungsmittelflaschn is dro.",
    245: "Mehr Kartn gehn nimmer. Lösch oane in da App.",
    248: "S Wischtuach fehlt. Mach's dro und probier's no amoi.",
    266: "Tausch s Reinigungsmittel aus.",
    267: "Meine Sensorn san dreckert. Butz's ma.",
    296: "Schaug amoi, ob da Schmutzwassatank voi is.",
    297: "D'Reinigungsmittelflaschn is dro. Wennst's no nia benutzt host, schaug in da App nach.",
    299: "D'Reinigungsmittelflaschn und s Nachfüllmodul san dro.",
    300: "Des Zubehör kenn i ned.",
    312: "Über des Zubehör woaß i nix. Tausch's aus, wenn's hi is.",
    315: "S Wischtuach is ned in da Station. Leg's eini und probier's no amoi.",
    316: "In da Station liegt eh scho a Wischtuach.",
    319: "S Wischtuach hod si ned löst. Nimm's mit da Hand owa.",
    320: "S Wischtuach hod si ned dromacht. Mach's mit da Hand dro.",
    329: "I test mi grad selba. Nimm mi ned vo da Station owa.",
    330: "Wart, bis da Selbsttest fertig is.",
    331: "Ois in Ordnung. I hob nix gfundn.",
    332: "I hob an Fehler gfundn. Schaug in da App nach.",
    353: "Da Schmutzwassabehälter is drin.",
    354: "Da Schmutzwassabehälter is aussa.",
    355: "Z'weng Wassa. Fui 'n Frischwassatank nach.",
    356: "Da Fehler is no do. De eiplante Reinigung is abgsagt.",
    358: "Setz bittschee 'n Schmutzwassabehälter eini.",
    384: "Im automatischn Wassamodul is koa Wassa.",
    386: "Mei Schmutzwassabehälter is voi. I fahr zruck und leer eahm aus.",
    387: "S Ausleern is fertig. I mach weida.",
    388: "Do derf i ned hi. Stei mi woanders hi.",
    389: "Da Laser fahrt ned owa. Schaug, ob was klemmt.",
    390: "Da Laser fahrt ned auffi. Schaug, ob was klemmt.",
    391: "Stei mi auf a freie Fläch, bevor's losgeht.",
    392: "Im Clean-Genius-Modus lasst si des ned einstelln.",
    393: "Mei Schmutzwassabehälter is dreckert. Mach eahm glei sauba.",
    394: "Da Wassasensor mog nimma.",
    426: "I bin abgrutscht und häng fest. I probier's weida.",
    437: "Bassd wieda. Druck auf Start, nacha geht's weida.",
    438: "Da Stoßbügel klemmt. Druck amoi sanft drauf.",
    439: "D'Laserabdeckung klemmt. Druck amoi sanft drauf.",
    440: "A Radl hängt in da Luft. Stei mi auf a freie Fläch.",
    441: "Do hod si was um d'Hauptbürstn gwicklt. Butz's.",
    442: "Do hod si was um d'Seitenbürstn gwicklt.",
    443: "Um meine Radln hod si was gwicklt.",
    444: "Stei mi auf a freie Fläch, nacha fang i o.",
    445: "Mei Wischtuach is ma owaghaut. Schaug amoi in da Nähe nach.",
    446: "Am Wischtuachhalta hängt was dro.",
    447: "D'Station hod koan Strom. Schaug amoi nach.",
    448: "Da Schmutzwassatank fehlt. Setz'n eini.",
    449: "Auf'm Teppich fang i ned o. Stei mi auf'n Hartbodn.",
    452: "Mit'm Teppichsensor stimmt was ned. Dreh mi um und butz s weiße Fensterl.",
    453: "Mit'm Kantensensor stimmt was ned. Butz mi rechts.",
    454: "Z'weng Wassa im Tank. Fui ma nach.",
    455: "Da Frischwassatank sitzt ned richtig drin.",
    456: "Da Schmutzwassatank is voi oda er fehlt.",
    457: "Da Schmutzwassatank is voi oda ned drin. Schaug nach.",
    458: "Da Staubbeitl sitzt ned richtig.",
    459: "Da Wischtuachhalta sitzt ned richtig. Schaug nach.",
    460: "Da Geruchsfilta is aufbraucht. Tausch'n aus.",
    639: "Do fehlt da Filta vom Waschbrett.",
    658: "Da Kalkschutz is aufbraucht. Tausch'n aus.",
    663: "Mit'm Wassastand im Waschbrett stimmt was ned. Butz 'n Filta.",
    673: "Um meine Beindl hod si vielleicht was gwicklt. Butz's vor'm Start.",
    674: "Mei Mopp klemmt vielleicht oda hod si was eigwicklt. Schaug nach und mach eahm sauba.",
    682: "Mei Mopp dreht si nimma.",
    683: "Da Mopp is ned dro. Mach zerst 'n Mopp dro und probier's nacha no amoi.",
    696: "Fehler bei da Klappn.",
    699: "Sensorfehler. Schaug nach, ob da Kamerasensor dreckert is.",
    706: "Fehler beim Kreisl. Start d'Aufgab no amoi.",
    707: "Fehler beim Fahrgstell. Start d'Aufgab no amoi.",
    719: "Fehler beim Mopp-Wechsl.",
    725: "Fehler bei da Moppabdeckung.",
    726: "Fehler beim Rollmopp.",
    755: "Da Lasersensor mog ned. Schaug nach, ob do was dreckert is oda klemmt.",
    771: "Da Rollmopp bleibt stehn oda is blockiert.",
    777: "D'Zeit is um. Schaug nach, ob unter'm Gerät was im Weg is.",
    778: "Obacht, pass auf deine Finger auf.",
    782: "Fehler beim Auflockern vo da Rolle. Butz's, nacha geht's weida.",
    797: "Do stimmt vielleicht was ned mit'm Gerät. Ruaf beim Kundendienst o.",
    799: "D'Zeit is um. Schaug nach, ob a Viech oda a Hindernis unter'm Gerät steht.",
    823: "Da Wassastand im Waschbrett bassd ned. Butz's, bevor's losgeht.",
    824: "Da Rollmopp bleibt stehn oda is blockiert.",
    828: "Da Filta is durch. Mach eahm boid sauba.",
    915: "Da Wassastand im Waschbrett bassd ned. Butz 'n Filta, damit nix verstopft.",

    # --- Wegfindung ---------------------------------------------------
    30: "I schaug grad, wo i bin.",
    31: "I woaß ned, wo i bin. Nacha fang i hoit neich o.",
    45: "I bin do!",
    149: "Do kimm i ned hi. Raum weg, was im Weg steht.",
    151: "Mei Weg is verstellt. Raum was weg.",
    153: "I steh in ana Sperrzon. Hoi mi do aussa.",
    258: "I fang zum Umanandfahrn o.",
    259: "I fahr do hi, wo'st gsagt host.",
    260: "I fahr weida umanand.",
    261: "I fahr weida do hi.",
    262: "I woaß ned, wo i bin.",
    698: "S Kartn-Zeichna is fertig. I find d'Station ned und fang selba zum Reinign o.",
    702: "Mit ana provisorischn Kartn ko i ned reinign. Druck no amoi auf Reinigung, nacha wird d'Kartn gspeichert.",
    723: "Beim Kartn-Zeichna schaug, dass ois guad ausgleicht is. Stei nix in d'Türn und schieb weda mi no d'Station umanand.",

    # --- Bedienung -----------------------------------------------------
    26: "I setz mi zruck auf d'Werkseinstellung.",
    27: "I mach a Update. Dauert fümf Minutn. Bittschee ned ausschoitn.",
    28: "Des Update hod highaut.",
    29: "Des Update hod ned highaut. Probier's spata no amoi.",
    46: "Roboter und Handy san verbundn.",
    116: "D'Kindersicherung is o. D'Knöpf san gsperrt.",
    117: "D'Kindersicherung is aus.",
    162: "D'Kamera is o.",
    293: "Anrufe san o.",
    294: "Anrufe san aus.",
    338: "Da Videoanruf steht.",
    339: "Anruf obglehnt.",
    340: "Koa Antwort.",
    364: "I richt 'n Videocode ei.",
    365: "S Livebuid is ausgschoit.",
    421: "Servus. Ab jetzt red i Bayerisch mit dir.",
    463: "Servus, schee dass'd do bist. Mach 'n Deckl auf und scann 'n QR-Code.",
    464: "Damit's spata glatt lauft, stei mi vor'm Start auf d'Station.",
    465: 'Stei mi vor\'m Start auf d\'Station. Wennst "I lad grad auf" heast, bassd\'s.',
    466: "Mach d'Türn auf und raum 'n Bodn frei.",
    467: "Stei mi auf d'Station und fang s Zeichna neich o.",
    468: "Schaug da d'Kartn in da App o.",
    630: "Servus, schee dass'd do bist. Mach 'n Deckl auf und scann 'n QR-Code.",
    631: "Schee, dass'd di für'n Dreame entschiedn host. Mach d'Klappn auf und scann 'n QR-Code, nacha kannst d'App ladn.",
    632: "Da Sprachwechsel dauert a hoibe Minutn.",
    633: "Da Sprachwechsel hod ned highaut.",
    634: "I fang zum Haar-Entwirrn o.",
    697: "I bin gsperrt. Mach zerst d'Kindersicherung aus.",
    718: "Des lasst si im Energiesparmodus ned ändern. Mach 'n Energiesparmodus aus und probier's no amoi.",
    910: "Servus und willkomma in da Ausstellung für Saugroboter.",

    # --- Sprachassistent ------------------------------------------------
    190: "Bassd, i fang zum Saugn o.",
    191: "Bassd, i saug und wisch.",
    192: "Bassd, i wisch.",
    193: "Bassd, i saug.",
    194: "I bin eh scho am Saugn.",
    195: "Bassd scho, i mach des Zimma sauba. Schaug, dass d'Tür auf is.",
    196: "Bassd scho, i saug 'n Bodn. Schaug, dass d'Tür auf is.",
    197: "Bassd scho, i wisch 'n Bodn. Schaug, dass d'Tür auf is.",
    198: "Bassd scho, i saug und wisch. Schaug, dass d'Tür auf is.",
    199: "Des Zimma kenn i ned. Schaug in da App nach, wia's hoaßt.",
    200: "Pfiat di.",
    201: "Bassd scho, i mach weida.",
    202: "Bassd scho, i hör auf und fahr zum Ladn.",
    203: "Bassd scho, i fahr zum Ladn.",
    204: "Bassd scho, i fang zum Zeichna o. Mach olle Türn auf.",
    205: "Bassd scho, i fahr vo da Station owa.",
    206: "Bassd scho, i schaug, wo'st bist.",
    207: "I find di ned. Stei di in mei Sichtweite.",
    208: "Do bist ja. I kimm saugn.",
    217: "Mehr Saugkraft geht nimmer.",
    218: "Weniger Saugkraft geht nimmer.",
    219: "Mehr Wassa geht nimmer.",
    220: "Weniger Wassa geht nimmer.",
    221: "Bassd scho.",
    222: "Saugstufn leise.",
    223: "Saugstufn normal.",
    224: "Saugstufn stark.",
    225: "Saugstufn Turbo.",
    226: "S Wischtuach is leicht feucht.",
    227: "S Wischtuach is feucht.",
    228: "S Wischtuach is nass.",
    229: "Heit is",
    230: "Heit is da oanazwanzigste Februar zwoatausend zwoaundzwanzig.",
    231: "Heit is Mondog.",
    232: "Heit is Dienstog.",
    233: "Heit is Mittwoch.",
    234: "Heit is Donnerstog.",
    235: "Heit is Freidog.",
    236: "Heit is Samstog.",
    237: "Heit is Sonntog.",
    238: "Bassd scho, i hör auf.",
    246: "I bin do hint!",
    247: "Des hob i jetzt ned verstandn.",
    249: "I arbat grad. Mach des zerst fertig, nacha geht's.",
    250: "I bin grad im Wischmodus. Stei um.",
    251: "I bin grad im Saugmodus. Stei um.",
    252: "Fertig. I bin aus da eigstellten Reinigung aussa.",
    253: "Lauter geht nimmer.",
    254: "Leiser geht nimmer.",
    255: "Des geht nur, wenn d'Hindernisumfahrung o is.",
    269: "Probier's no amoi, wenn i fertig bin.",
    275: "Des kenn i ned. In da App findst olle Sprachbefehle.",
    276: "Des mach i grad ned.",
    277: "Bassd scho, i kimm und mach's do sauba.",
    279: "I saug grad. Mach des zerst fertig und probier's no amoi.",
    281: "I saug mi grad aus. Probier's glei no amoi.",
    282: "I wasch grad mei Wischtuach. Probier's glei no amoi.",
    283: "I steh ned in da Station. Probier's spata no amoi.",
    284: "Bassd scho, i hör auf und kimm saugn.",
    285: "Bleib kurz steh, i schaug wo'st bist.",
    286: "Do brauch i zerst a Kartn.",
    287: "Bassd scho, jetzt is leise.",
    288: "Bassd scho, jetzt is normal.",
    289: "Bassd scho, jetzt is stark.",
    290: "Bassd scho, jetzt is Turbo.",
    291: "Bassd scho, jetzt is leicht feucht.",
    292: "Bassd scho, jetzt is nass.",
    308: "Des hob i ned mitkriagt. Weck mi no amoi auf.",
    309: "Do bist ja, i kimm.",
    310: "Bassd scho, i fahr glei do weg.",
    314: "Des geht ned. Aber du kannst ma sagn, i soi mi umdrahn.",
    317: "Des geht grad ned, i mach a eigstellte Reinigung.",
    322: "Des kenn i ned. In da App findst olle Sprachbefehle.",
    323: "Des kenn i ned. Frag mi amoi, was i ollas ko.",
    324: "I wasch mi grad. Weck mi auf, wenn i fertig bin.",
    328: "Des kannst ma nur sagn, wenn i grad saug.",
    341: "Do bist ja. I geh dir nach. Sag Ende, wennst gnua host.",
    342: "Wo bist? Stei di ungefähr andahoib Meter vor mi hi.",
    343: "I hob di verlorn. Du bist z'schnei. Stei di andahoib Meter vor mi hi.",
    489: "I bin im Clean-Genius-Modus. Sag ma, i soi aufhörn.",
    490: "Bassd scho, eigstellte Reinigung: i wisch.",
    491: "Bassd scho, eigstellte Reinigung: i saug.",
    508: "I red lauter.",
    509: "I red leiser.",
    510: "Guad, i hör auf für heit.",
    511: "I mach grad goa nix.",
    512: "In da Kartn is no koa Tiermöbel. Trag's in da App ei.",
    513: "Bassd scho, i mach ums Tiermöbel umanand sauba.",
    515: "Sei so guad und heb amoi d'Fiaß.",
    516: "I schaug, wo dei Viech steckt.",
    517: "I hob's gfundn. I fahr zum Ladn.",
    518: "I hob koans gfundn. I fahr zum Ladn.",
    522: "Was is'n schiafganga?",
    523: "Magst ma des a bisserl genauer sagn?",
    524: "Nimm mi dahi, wo's passiert is.",
    525: "Wart kurz, i schaug ma des o.",
    641: "Sag ma einfach, i soi zum Saugn ofanga.",
    642: "Sag ma einfach, i soi stärker saugn.",
    643: "Sag ma einfach, i soi mehr Wassa nehma.",
    644: "Sag ma einfach, i soi saugn und wischn.",
    645: "Sag ma einfach, i soi wischn.",
    646: "Sag ma einfach, i soi do herkemma und sauba macha.",
    647: "Sag ma einfach, i soi zerst saugn und nacha wischn.",
    648: "Sag ma einfach, i soi ois sauba macha.",
    659: "Des hob i ned verstandn. Frag mi amoi, was i ollas ko.",
    660: 'Tschuidigung, des hob i ned kapiert. Sag "Hey Rover, was kannst du", nacha sag i dir, was i ollas ko.',
    664: "Sag zu mir: Hey Rover, fang zum Reinign o.",
    665: "Wenn ois bassd, sag zu mir: Hey Rover, fang zum Reinign o.",
    666: "Sag zu mir: Hey Rover, mach de Saugkraft stärker.",
    667: "Sag zu mir: Hey Rover, gib mehr Wassa.",
    668: "Sag zu mir: Hey Rover, fang zum Saugn o. Spata sagst wischn, nacha wechsl i 'n Modus.",
    669: "Sag zu mir: Hey Rover, fang zum Wischn o. Spata kannst 'n Modus wechsln.",
    670: "Sag zu mir: Hey Rover, kimm her und mach do sauba.",
    671: "Sag zu mir: Hey Rover, fang zum Saugn o. Spata kannst 'n Modus wechsln.",
    672: "Sag zu mir: Hey Rover, fang zum Reinign o. Spata kannst de ganze Wohnung reinign lassn.",
    694: "Sag ma einfach, i soi zum Saugn ofanga.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Da Akku is auf {p} Prozent.'
RAUM_MUSTER = 'Bassd, i mach {raum} sauba.'
RAUM_NAMEN = {
    'wohnzimmer': 's Wohnzimma',
    'schlafzimmer': 's Schlafzimma',
    'hauptschlafzimmer': 's Hauptschlafzimma',
    'gaestezimmer': 's Gästezimma',
    'arbeitszimmer': 's Arbeitszimma',
    'kueche': 'd Kuchl',
    'esszimmer': 's Esszimma',
    'bad': 's Bad',
    'balkon': 'n Balkon',
    'flur': 'n Gang',
    'hauswirtschaftsraum': 'd Waschkuchl',
    'abstellraum': 'd Abstellkammer',
    'salon': 'n Salon',
    'buero': 's Büro',
    'gym': 'n Fitnessraum',
    'freizeitraum': 'n Freizeitraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))
