"""Berlinerisch - Berliner Schnauze."""

from __future__ import annotations

from . import muster

KEY = "berlinerisch"
NAME = "Berlin Dialect"
BESCHREIBUNG = (
    "Berlin's famous 'Schnauze': blunt, dry, with heart. Loves to "
    "complain, but cleans anyway."
)
LANG_ID = "BERLIN"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "Ick warte uffs Netzwerk.",
    2: "Mitm WLAN hats nich jeklappt. Kiek ma nachm Passwort.",
    3: "Ick komm nich uffn Server. Kiek ma dein Netzwerk an.",
    5: "Netzwerk passt, ick bin drin.",
    6: "Mitm Netzwerk hats nich jeklappt. Probier's später nochma.",

    # --- Reinigung ---------------------------------------------------
    7: "Na denn los. Ick fang an zu sauje.",
    8: "Ick mach den eenen Fleck sauber.",
    9: "De jeplante Reinigung jeht jetzt los.",
    10: "Ick mach weiter, wo ick uffjehört hab.",
    12: "Fertich. Allet sauber.",
    56: "Ick mach det Zimmer sauber.",
    57: "Ick mach de Zone sauber.",
    58: "Ick mach meine Arbeet weiter.",
    61: "Ick fang an zu wischen.",
    62: "Du steuerst mir jetzt selber.",
    82: "Ick mal jetzt ne Karte von de Wohnung.",
    84: "De Karte is fertich.",
    105: "Uff jehts, ick fang an.",
    126: "Ick fang an zu sauje.",
    137: "Ick sauje weiter.",
    138: "Ick wische weiter.",
    139: "Ick komm zurück.",
    143: "Fertich. Da siehts jetzt sauber aus.",
    144: "Jewischt hab ick ooch schon.",
    164: "So, det wars. Feierabend.",
    433: "Ick mach noch ne Extrarunde.",
    434: "De Extrarunde is fertich, ick mach normal weiter.",

    # --- Akku und Laden ----------------------------------------------
    13: "Ick fahr nach Hause zum Uffladen.",
    14: "Meine Batterie is bald leer. Ick fahr laden und mach denn weiter.",
    17: "Stell mir bitte wieder uff de Station.",
    18: "Ick lade jerade uff.",
    20: "Meine Batterie is bald leer.",
    21: "Batterie leer. Ick mach jetzt Schluss.",
    47: "Ick fang an zu laden.",
    48: "Batterie is schwach, ick fahr zur Station.",
    50: "Mitm Laden stimmt wat nich. Mach ma de Kontakte sauber.",
    301: "Ick lade jerade uff.",
    302: "Ick bin jerade am Arbeeten.",

    # --- Station und Wischen -----------------------------------------
    106: "Ick wasch mein Wischtuch.",
    107: "Ick trockne meine Wischtücher.",
    110: "Ick sauje meinen Staub raus.",
    111: "Mir fehlen de Wischtücher. Mach se mir bitte dran.",
    112: "Stell mir erstma in de Station.",
    113: "Fertich. Mach bitte den Schmutzwassertank leer.",
    114: "De Wischtücher sind dran.",
    115: "De Wischtücher sind runter.",
    148: "Ick fahr zur Station und mach mir selber sauber.",
    169: "De Wischtücher sind trocken.",
    177: "Ick fahr los.",
    179: "Wischtuch is sauber. Aber det Frischwasser jeht mir aus.",
    181: "Mir jeht det Wasser aus. Füll ma nach.",
    186: "Kiek ma nachm Frischwassertank.",
    187: "Det dauert so fünf bis zehn Minuten.",
    318: "Mein Wischtuch is wieder sauber.",
    636: "Mein Wischtuch is total dreckich. Ick muss zur Station.",

    # --- Fehler und Wartung ------------------------------------------
    35: "Mit de Hauptbürste stimmt wat nich. Mach se ma sauber.",
    36: "Mit de Seitenbürste stimmt wat nich. Mach se ma sauber.",
    37: "Mitm rechten Rad stimmt wat nich.",
    38: "Mitm linken Rad stimmt wat nich.",
    40: "Mensch Meier, ick häng fest. Machste mir bitte frei?",
    42: "Kiek ma nach mein Filter.",
    43: "Mit mein Stoßbügel stimmt wat nich. Drück ma sachte druff.",
    44: "Da stimmt wat nich. Kiek bitte in de Anleitung.",
    52: "Ick steh schief. Stell mir bitte jerade hin.",
    66: "Mein Filter is hin. Tausch'n bitte aus.",
    67: "De Seitenbürste is hin. Tausch se bitte aus.",
    68: "De Hauptbürste is hin. Tausch se bitte aus.",
    91: "Der Frischwassertank fehlt. Setz'n bitte rin.",
    93: "Zu wenich Wasser drin. Füll bitte nach.",
    97: "Da fehlt der Staubbeutel.",
    102: "Der Staubbeutel is voll oder der Kanal is verstopft.",
    156: "Mein Wischtuch is nich dran.",
    166: "Da hat sich wat in mein Wischtuch jewickelt. Mach's bitte weg.",
    267: "Meine Sensoren sind dreckich. Mach se ma sauber.",
    331: "Allet in Ordnung. Ick hab nischt jefunden.",
    332: "Ick hab een Fehler jefunden. Kiek ma in de App.",
    426: "Ick bin abjerutscht und häng fest. Ick probier's weiter.",
    437: "Passt wieder. Drück uff Start, denn jehts weiter.",
    441: "Da hat sich wat um de Hauptbürste jewickelt. Mach's bitte sauber.",
    442: "Da hat sich wat um de Seitenbürste jewickelt.",
    443: "Um meine Räder hat sich wat jewickelt.",
    444: "Stell mir bitte uff ne freie Fläche, denn fang ick an.",
    445: "Mein Wischtuch is mir runter. Kiek ma in de Nähe.",
    446: "Am Wischtuchhalter hängt wat dran.",
    447: "De Station hat keen Strom. Kiek bitte ma nach.",
    448: "Der Schmutzwassertank fehlt. Setz'n bitte rin.",
    449: "Uffm Teppich fang ick nich an. Stell mir uffn Hartboden.",
    454: "Zu wenich Wasser im Tank. Füll ma nach.",
    455: "Der Frischwassertank sitzt nich richtich drin.",
    456: "Der Schmutzwassertank is voll oder er fehlt.",
    458: "Der Staubbeutel sitzt nich richtich.",
    460: "Der Jeruchsfilter is alle. Tausch'n bitte aus.",
    639: "Da fehlt der Filter vom Waschbrett.",
    658: "Der Kalkschutz is alle. Tausch'n bitte aus.",

    # --- Wegfindung ---------------------------------------------------
    30: "Ick kiek jerade, wo ick bin.",
    31: "Ick weess nich, wo ick bin. Ick fang eenfach neu an.",
    45: "Ick bin hier!",
    149: "Da komm ick nich hin. Räum bitte weg, wat im Weje steht.",
    151: "Mein Weg is verstellt. Räum bitte wat weg.",
    153: "Ick steh in ner Sperrzone. Hol mir da bitte raus.",

    # --- Bedienung -----------------------------------------------------
    26: "Ick setz mir zurück uff de Werkseinstellung.",
    27: "Ick mach een Update. Dauert fünf Minuten. Bitte nich ausschalten.",
    28: "Det Update hat jeklappt.",
    29: "Det Update hat nich jeklappt. Probier's später nochma.",
    116: "De Kindersicherung is an. De Knöppe sind jesperrt.",
    117: "De Kindersicherung is aus.",
    162: "De Kamera is an.",
    329: "Ick teste mir jerade selber. Nimm mir nich von de Station runter.",
    421: "Na, ab jetzt schnack ick Berlinerisch mit dir.",
    632: "Der Sprachwechsel dauert ne halbe Minute.",
    633: "Der Sprachwechsel hat nich jeklappt.",

    # --- Sprachassistent ------------------------------------------------
    190: "Allet klar, ick fang an zu sauje.",
    191: "Allet klar, ick sauje und wische.",
    192: "Allet klar, ick wische.",
    193: "Allet klar, ick sauje.",
    221: "Passt schon.",
    246: "Ick bin hier hinten!",
    247: "Det hab ick jetzt nich verstanden.",
    508: "Ick red lauter.",
    509: "Ick red leiser.",
    510: "Jut, ick mach Schluss für heute.",
    515: "Sei so jut und heb ma de Beene.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Akku is bei {p} Prozent.'
RAUM_MUSTER = 'Allet klar, ick mach {raum} sauber.'
RAUM_NAMEN = {
    'wohnzimmer': 'det Wohnzimmer',
    'schlafzimmer': 'det Schlafzimmer',
    'hauptschlafzimmer': 'det Hauptschlafzimmer',
    'gaestezimmer': 'det Jästezimmer',
    'arbeitszimmer': 'det Arbeetszimmer',
    'kueche': 'de Küche',
    'esszimmer': 'det Esszimmer',
    'bad': 'det Bad',
    'balkon': 'den Balkon',
    'flur': 'den Flur',
    'hauswirtschaftsraum': 'de Waschküche',
    'abstellraum': 'de Abstellkammer',
    'salon': 'den Salon',
    'buero': 'det Büro',
    'gym': 'den Fitnessraum',
    'freizeitraum': 'den Freizeitraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))

# --------------------------------------------------------------------------
# Vollständige Abdeckung: die restlichen Ansagen des X50 Ultra Complete.
# Nummern ohne Sprachinhalt (Klänge, Tierlaute) bleiben im Original; die
# Nummern-Umsetzung des Modells versorgt 856, 858, 859, 863 und 864.
# --------------------------------------------------------------------------

TEXTE.update({
    # --- Netzwerk -----------------------------------------------------
    4: "Ick bin ausm Netzwerkmodus raus.",
    304: "Det Netzwerk is verbunden.",
    306: "Det hab ick nich verstanden. Richt erstma det Netzwerk ein.",
    313: "Der Empfang is mies. Stell mir woanders hin.",
    377: "Det Netzwerk läuft nich. Frag beim Kundendienst nach.",
    378: "Det Passwort stimmt nich. Richt det Netzwerk nochma ein.",
    379: "Ick find keen WLAN. Nimm det Zweikommavier-Gigahertz-Netz.",
    380: "Ick hab keene IP-Adresse jekriegt. Kiek ma in dein Router.",
    381: "Ick komm nich uffn Server. Frag beim Kundendienst nach.",
    382: "Ick komm nich ins Netz. Kiek, ob dein Internet läuft.",
    383: "Det Netzwerk läuft nich. Frag beim Kundendienst nach.",
    385: "Ick verbind mir jerade mitm Netzwerk.",

    # --- Reinigung ----------------------------------------------------
    11: "Ick mach ne Pause.",
    54: "Passt, ick sauje weiter.",
    55: "Passt, ick fahr weiter zur Station.",
    64: "Hat nich jeklappt. Ick fahr zur Station.",
    65: "Ick fahr weiter zur Station.",
    77: "Stell mir uffn Hartboden, denn fang ick an.",
    83: "Ick mal weiter an de Karte.",
    85: "Passt, ick mal weiter.",
    86: "Hat nich jeklappt. Ick fang mitm Malen neu an.",
    127: "Ick mach den Fleck sauber.",
    128: "Ick wisch den Fleck.",
    129: "De jeplante Reinigung jeht los.",
    130: "De jeplante Kartierung jeht los.",
    133: "Ick mach de ausjesuchten Zimmer sauber.",
    134: "Ick wisch de ausjesuchten Zimmer.",
    135: "Ick mach de Zone sauber.",
    136: "Ick wisch de Zone.",
    145: "Passt, ick sauje weiter.",
    146: "Passt, ick mal weiter.",
    150: "Da komm ick nich hin. Nimm bitte de Sperrzonen weg.",
    152: "Mein Weg is verstellt. Nimm de Sperrzonen weg oder stell mir woanders hin.",
    163: "Ick kiek jerade mit de Kamera.",
    171: "De schlaue Hindernisumfahrung is an.",
    172: "De schlaue Hindernisumfahrung is aus.",
    257: "De Kameraüberwachung is aus.",
    280: "Ick fang mit de einjestellten Reinigung an.",
    321: "Ick fang mitm jründlichen Fleckenwischen an.",
    344: "Allet klar, ick sauje erst und wische denn.",
    362: "Det Wischtuch sitzt nich richtich. Ick sauje stattdessen bloß.",
    363: "Det Saujen is fertich, jetzt wisch ick.",
    366: "Da is een Fleck, ick mach den sauber.",
    367: "Allet klar, ick mach den Fleck sauber.",
    368: "Da is een Fleck. Ick mach den sauber, wenn ick jewaschen hab.",
    369: "Allet klar, ick mach da sauber.",
    424: "Ick weess nich, wo ick bin. Stell mir uff ne freie Fläche und fang neu an.",
    435: "Ick fahr aus dem Bereich raus.",
    450: "In ner Sperrzone fang ick nich an. Stell mir woanders hin.",
    451: "Im versteckten Bereich fang ick nich an. Stell mir woanders hin.",
    677: "Da komm ick nich hin. Nimm de Sperrzonen oder de Schwellen weg.",
    678: "Mein Weg is verstellt. Nimm de Sperrzonen oder de Schwellen weg.",
    679: "Ick steh in ner Sperrzone. Hol mir da bitte raus.",
    680: "Ick mal erst ne Karte, denn mach ick sauber.",
    681: "Allet klar, ick mach weiter.",

    # --- Akku und Laden ------------------------------------------------
    19: "Nimm mir von de Station runter, bevor de mir ausmachst.",
    25: "Der Akku is zu schwach für de jeplante Reinigung.",
    87: "Batterie schwach, ick fahr zur Station.",
    303: "Ick ruh mir jerade aus.",
    307: "Ick lade jerade uff.",

    # --- Fehler und Wartung --------------------------------------------
    34: "Da fehlt een Teil. Setz det bitte rin.",
    39: "Meine Räder hängen in de Luft. Mach de Absturzsensoren sauber.",
    41: "Meine Räder hängen in de Luft. Stell mir woanders hin.",
    71: "Kiek ma, ob am Laser-Abstandssensor wat klemmt.",
    72: "De Abdeckung vom Lasersensor klemmt.",
    73: "Mitm Kantensensor stimmt wat nich.",
    75: "Der Filter is feucht oder verstopft.",
    81: "Mitm Teppichsensor stimmt wat nich.",
    108: "Mitm Wasserstand vom Waschbrett stimmt wat nich. Mach det sauber.",
    109: "Mitm Schmutzwassertank stimmt wat nich. Kiek, ob er drin und leer is.",
    118: "De Knöppe sind jesperrt. Halt de Taste an de Station jedrückt.",
    142: "Det Wischtuch is hin. Tausch det bitte aus.",
    173: "Tausch bitte det Silberionen-Modul aus.",
    244: "De Reinigungsmittelflasche is dran.",
    245: "Mehr Karten jehen nich. Lösch bitte eene in de App.",
    296: "Kiek ma, ob der Schmutzwassertank voll is.",
    297: "De Reinigungsmittelflasche is dran. Wenn de se noch nie benutzt hast, kiek in de App.",
    298: "Ick mach det Waschbrett sauber.",
    299: "De Reinigungsmittelflasche und det Nachfüllmodul sind dran.",
    300: "Det Zubehör kenn ick nich.",
    312: "Über det Zubehör weess ick nischt. Tausch det aus, wenn et hin is.",
    315: "Det Wischtuch is nich in de Station. Leg det rin und probier nochma.",
    316: "In de Station liegt schon een Wischtuch.",
    319: "Det Wischtuch is nich runter. Nimm det von Hand ab.",
    320: "Det Wischtuch is nich drangejangen. Mach det von Hand dran.",
    330: "Wart, bis der Selbsttest fertich is.",
    355: "Zu wenich Wasser. Füll den Frischwassertank nach.",
    356: "Der Fehler is noch da. De jeplante Reinigung is abjesagt.",
    384: "Im automatischen Wassermodul is keen Wasser.",
    388: "Da darf ick nich hin. Stell mir woanders hin.",
    389: "Der Laser fährt nich runter. Kiek, ob wat klemmt.",
    390: "Der Laser fährt nich ruff. Kiek, ob wat klemmt.",
    391: "Stell mir uff ne freie Fläche, bevor et losjeht.",
    392: "Im Clean-Genius-Modus jeht det nich.",
    438: "Der Stoßbügel klemmt. Drück ma sachte drauf.",
    439: "De Laserabdeckung klemmt. Drück ma sachte drauf.",
    440: "Een Rad hängt in de Luft. Stell mir uff ne freie Fläche.",
    452: "Mitm Teppichsensor stimmt wat nich. Dreh mir um und mach det weisse Loch sauber.",
    453: "Mitm Kantensensor stimmt wat nich. Mach mir rechts sauber.",
    457: "Der Schmutzwassertank is voll oder nich drin. Kiek ma nach.",
    459: "Der Wischtuchhalter sitzt nich richtich. Kiek ma nach.",
    663: "Mitm Wasserstand im Waschbrett stimmt wat nich. Mach det sauber.",
    673: "Um meine Beinchen hat sich vielleicht wat jewickelt. Mach det vorm Start sauber.",

    # --- Basisstation ---------------------------------------------------
    46: "Roboter und Handy sind verbunden.",
    59: "De Karte is fertich. Nimm den Wassertank raus.",
    140: "Ne neue Umjebung. Ick fahr zur Station.",
    188: "Ick docke automatisch an.",
    209: "Allet klar, ick fahr zur Station und wasch mein Wischtuch.",
    210: "Ick wasch de Wischtücher.",
    211: "Aussaujen jeht bloß, wenn ick in de Station steh.",
    212: "Allet klar, ick sauje mir aus.",
    213: "Trocknen jeht bloß, wenn ick in de Station steh.",
    214: "Ick trockne jerade.",
    215: "Allet klar, ick fang mitm Trocknen an.",
    216: "Da muss erst det Wischtuch dran.",
    278: "Allet klar, det Trocknen is fertich.",
    349: "Kiek, dat de Station Strom hat, und stell mir drauf.",
    350: "Ick fang mitm Einrichten von de Station an.",
    351: "De Station is einjerichtet.",
    352: "Det Einrichten hat nich jeklappt. Kiek in de App.",
    360: "Ick lass det Wasser ausm Tank.",
    361: "Det Wasser is raus.",
    371: "Nimm bitte det Waschbrett raus.",
    372: "Det Frischwasser läuft rin.",
    373: "Det Wasser is drin. Wart zehn Sekunden, denn jehts weiter.",
    374: "Mach den Boden von de Station mit ner Bürste oder eem Tuch sauber.",
    375: "Schieb den Dreck zum Aussaujen hin. Det dauert een bisschen.",
    376: "Det Aussaujen is fertich. Mach det Waschbrett extra sauber und setz det wieder rin.",
    396: "Ick mach det Wassermodul leer. Det dauert een bisschen.",
    397: "Det Wasser is oben und unten raus.",
    398: "De Karte is fertich. Kiek se dir in de App an und stell mir zurück.",
    399: "Der Test is fertich. Stell mir zurück uff de Station.",
    400: "De Selbstreinigung is fertich. Stell mir jetzt uff det richtige Stockwerk.",
    401: "Stell mir uff de Station, denn fang ick mit de Selbstreinigung an.",
    478: "Wenn ick jewaschen hab, mach ick mitm Saujen weiter.",
    479: "Allet klar, fang deine Arbeet neu an.",
    480: "Füll jenuch Wasser rin, dat et fürs Nächste reicht.",
    481: "Ick mach den Handstaubsauger leer.",
    482: "Ick mach den Handstaubsauger leer. Mir selber sauje ick denn aus.",
    483: "Ick mach den Handstaubsauger leer. Det Wischtuch wasch ick denn.",
    484: "Ick mach den Handstaubsauger leer. Jesaugt wird denn.",
    485: "Ick sauje mir jerade aus. Der Handstaubsauger kommt denn.",
    486: "Ick wasch jerade det Wischtuch. Der Handstaubsauger kommt denn.",
    487: "Kiek, dat ick in de Station steh.",
    638: "Ick sauje mir weiter aus.",
    661: "Ick mach det Waschbrett sauber. Det dauert ne knappe Minute.",
    662: "Ick mach elektrolysiertet Wasser zum Putzen.",

    # --- Sprachassistent -------------------------------------------------
    194: "Ick bin schon am Saujen.",
    195: "Allet klar, ick mach det Zimmer sauber. Kiek, dat de Tür uff is.",
    196: "Allet klar, ick sauje den Boden. Kiek, dat de Tür uff is.",
    197: "Allet klar, ick wische den Boden. Kiek, dat de Tür uff is.",
    198: "Allet klar, ick sauje und wische. Kiek, dat de Tür uff is.",
    199: "Det Zimmer kenn ick nich. Kiek in de App, wie et heißt.",
    200: "Mach et jut.",
    201: "Allet klar, ick mach weiter.",
    202: "Allet klar, ick hör uff und fahr zum Laden.",
    203: "Allet klar, ick fahr zum Laden.",
    204: "Allet klar, ick fang mitm Malen an. Mach bitte alle Türen uff.",
    205: "Allet klar, ick fahr von de Station runter.",
    206: "Allet klar, ick kiek, wo de bist.",
    207: "Ick find dir nich. Stell dir in meine Sichtweite.",
    208: "Da biste ja. Ick komm saujen.",
    217: "Mehr Saugkraft jeht nich.",
    218: "Weniger Saugkraft jeht nich.",
    219: "Mehr Wasser jeht nich.",
    220: "Weniger Wasser jeht nich.",
    222: "Saugstufe leise.",
    223: "Saugstufe normal.",
    224: "Saugstufe stark.",
    225: "Saugstufe Turbo.",
    226: "Det Wischtuch is leicht feucht.",
    227: "Det Wischtuch is feucht.",
    228: "Det Wischtuch is nass.",
    229: "Heute is",
    230: "Heute is der eenundzwanzigste Februar zweetausendzweeundzwanzig.",
    231: "Heute is Montach.",
    232: "Heute is Dienstach.",
    233: "Heute is Mittwoch.",
    234: "Heute is Donnerstach.",
    235: "Heute is Freitach.",
    236: "Heute is Sonnabend.",
    237: "Heute is Sonntach.",
    238: "Allet klar, ick hör uff.",
    248: "Det Wischtuch fehlt. Mach det dran und probier nochma.",
    249: "Ick arbeete jerade. Mach det erst fertich, denn jehts.",
    250: "Ick bin jerade im Wischmodus. Stell bitte um.",
    251: "Ick bin jerade im Saugmodus. Stell bitte um.",
    252: "Fertich. Ick bin aus de einjestellten Reinigung raus.",
    253: "Lauter jeht nich.",
    254: "Leiser jeht nich.",
    255: "Det jeht bloß mit einjeschalteter Hindernisumfahrung.",
    258: "Ick fang an rumzufahren.",
    259: "Ick fahr zu der Stelle hin.",
    260: "Ick fahr weiter rum.",
    261: "Ick fahr weiter zu der Stelle.",
    262: "Ick weess nich, wo ick bin.",
    266: "Tausch bitte det Reinigungsmittel aus.",
    269: "Probier nochma, wenn ick fertich bin.",
    275: "Det kenn ick nich. In de App stehen alle Sprachbefehle.",
    276: "Det mach ick jerade nich.",
    277: "Allet klar, ick komm und mach da sauber.",
    279: "Ick sauje jerade. Mach det erst fertich und probier nochma.",
    281: "Ick sauje mir jerade aus. Probier jleich nochma.",
    282: "Ick wasch jerade mein Wischtuch. Probier jleich nochma.",
    283: "Ick steh nich in de Station. Probier später nochma.",
    284: "Allet klar, ick hör uff und komm saujen.",
    285: "Bleib kurz stehen, ick kiek wo de bist.",
    286: "Da brauch ick erst ne Karte.",
    287: "Allet klar, jetzt is leise.",
    288: "Allet klar, jetzt is normal.",
    289: "Allet klar, jetzt is stark.",
    290: "Allet klar, jetzt is Turbo.",
    291: "Allet klar, jetzt is leicht feucht.",
    292: "Allet klar, jetzt is nass.",
    293: "Anrufe sind an.",
    294: "Anrufe sind aus.",
    305: "Allet klar, ick mach det Waschbrett sauber. Mach det innen mit ner Bürste sauber.",
    308: "Det hab ick nich mitjekriegt. Weck mir nochma.",
    309: "Da biste ja, ick komm.",
    310: "Allet klar, ick fahr jleich da weg.",
    311: "De Wischtücher sind runter.",
    314: "Det jeht nich. Du kannst mir sagen, ick soll mir umdrehen.",
    317: "Det jeht jerade nich, ick mach ne einjestellte Reinigung.",
    322: "Det kenn ick nich. In de App stehen alle Sprachbefehle.",
    323: "Det kenn ick nich. Frag mir ma, wat ick allet kann.",
    324: "Ick wasch mir jerade. Weck mir, wenn ick fertich bin.",
    328: "Det kannste mir bloß sagen, wenn ick jerade sauje.",
    338: "Der Videoanruf steht.",
    340: "Keene Antwort.",
    341: "Da biste ja. Ick jeh dir nach. Sag Ende, wenn et reicht.",
    342: "Wo biste? Stell dir ungefähr anderthalb Meter vor mir.",
    343: "Ick hab dir verloren. Du bist zu schnell. Stell dir anderthalb Meter vor mir.",
    364: "Ick richt den Videocode ein.",
    365: "Det Livebild is aus.",
    489: "Ick bin im Clean-Genius-Modus. Sag mir, ick soll uffhören.",
    490: "Allet klar, einjestellte Reinigung: ick wische.",
    491: "Allet klar, einjestellte Reinigung: ick sauje.",
    511: "Ick mach jerade nischt.",
    512: "In de Karte is noch keen Tiermöbel. Trag det in de App ein.",
    513: "Allet klar, ick mach ums Tiermöbel rum sauber.",
    516: "Ick kiek, wo dein Viech steckt.",
    517: "Ick hab et jefunden. Ick fahr zum Laden.",
    518: "Ick hab keens jefunden. Ick fahr zum Laden.",
    522: "Wat is denn schiefjejangen?",
    523: "Kannste mir det een bisschen jenauer sagen?",
    524: "Nimm mir dahin, wo et passiert is.",
    525: "Wart kurz, ick kiek mir det an.",
    641: "Sag mir eenfach, ick soll mitm Saujen anfangen.",
    642: "Sag mir eenfach, ick soll stärker saujen.",
    643: "Sag mir eenfach, ick soll mehr Wasser nehmen.",
    644: "Sag mir eenfach, ick soll saujen und wischen.",
    645: "Sag mir eenfach, ick soll wischen.",
    646: "Sag mir eenfach, ick soll dahin kommen und sauber machen.",
    647: "Sag mir eenfach, ick soll erst saujen und denn wischen.",
    648: "Sag mir eenfach, ick soll allet sauber machen.",
    659: "Det hab ick nich verstanden. Frag mir ma, wat ick allet kann.",
    694: "Sag mir eenfach, ick soll mitm Saujen anfangen.",

    # --- Erste Einrichtung ------------------------------------------------
    463: "Na, schön dat de da bist. Mach den Deckel uff und scann den QR-Code.",
    464: "Damit später allet jlatt läuft, stell mir vorm Start uff de Station.",
    465: "Stell mir vorm Start uff de Station. Wenn de 'Ick lade uff' hörst, passt et.",
    466: "Mach bitte de Türen uff und räum den Boden frei.",
    467: "Stell mir uff de Station und fang det Malen neu an.",
    468: "Kiek dir de Karte bitte in de App an.",
    630: "Na, schön dat de da bist. Mach den Deckel uff und scann den QR-Code.",
})

# --------------------------------------------------------------------------
# Die letzten Ansagen des r2532v (X50 Ultra Complete). Ihr Wortlaut steht in
# keiner Textdatei des Pakets - er wurde aus den deutschen Originalaufnahmen
# transkribiert (Windows-Spracherkennung) und anschliessend von Hand
# geglättet. Sinngemäß richtig, im Wortlaut sinnvoll gekürzt.
# --------------------------------------------------------------------------

TEXTE.update({
    24: 'Kiek ma, ob der Wassertank richtich drinsteckt.',
    101: 'De Klappe von de Absaugstation is uff oder der Beutel fehlt. Mach de Klappe zu oder lej een Beutel rin.',
    104: 'Det Waschbrett is nich drin. Setz det rin und mach de Klammern uff beide Seiten fest.',
    170: 'De Tastensperre is an. Halt de Tasten an de Station jedrückt, denn jeht se wieder uff.',
    339: 'Anruf abjelehnt.',
    353: 'Der Schmutzwasserbehälter is drin.',
    354: 'Der Schmutzwasserbehälter is raus.',
    358: 'Setz bitte den Schmutzwasserbehälter rin.',
    386: 'Mein Schmutzwasserbehälter is voll. Ick fahr zurück und mach den leer.',
    387: 'Det Leermachen is fertich. Ick mach weiter.',
    393: 'Mein Schmutzwasserbehälter is dreckich. Mach den jleich sauber.',
    394: 'Der Wassersensor macht et nich mehr.',
    631: 'Schön, dat de dir fürn Dreame entschieden hast. Mach de Klappe uff und scann den QR-Code, denn kannste de App laden.',
    634: 'Ick fang an, de Haare zu entwirren.',
    660: 'Tschuldjung, det hab ick nich verstanden. Sag Hey Rover, was kannst du, denn sag ick dir, wat ick allet kann.',
    664: 'Sag zu mir: Hey Rover, fang an zu reinjen.',
    665: 'Wenn allet passt, sag zu mir: Hey Rover, fang an zu reinjen.',
    666: 'Sag zu mir: Hey Rover, mach de Saugkraft stärker.',
    667: 'Sag zu mir: Hey Rover, jib mehr Wasser.',
    668: 'Sag zu mir: Hey Rover, fang an zu saujen. Später sagste wischen, denn wechsel ick den Modus.',
    669: 'Sag zu mir: Hey Rover, fang an zu wischen. Später kannste den Modus wechseln.',
    670: 'Sag zu mir: Hey Rover, komm her und mach da sauber.',
    671: 'Sag zu mir: Hey Rover, fang an zu saujen. Später kannste den Modus wechseln.',
    672: 'Sag zu mir: Hey Rover, fang an zu reinjen. Später kannste de janze Wohnung machen lassen.',
    674: 'Mein Mopp klemmt vielleicht oder hat sich wat rinjewickelt. Kiek nach und mach den sauber.',
    682: 'Mein Mopp dreht sich nich mehr.',
    683: 'Der Mopp is nich dran. Mach erst den Mopp dran und probier denn nochma.',
    689: 'Ick fang an, Staubbehälter und Beutel zu trocknen.',
    690: 'Det Trocknen von Staubbehälter und Beutel is jestoppt.',
    691: 'Der Mopp wird jerade jewaschen. Probier später nochma.',
    692: 'Ick fahr zum Laden. Ne extra Reinjung jeht jerade nich.',
    696: 'Fehler an de Klappe.',
    697: 'Ick bin jesperrt. Mach erst de Kindersicherung aus.',
    698: 'Det Kartenmalen is fertich. Ick find de Station nich und fang alleene an zu reinjen.',
    699: 'Sensorfehler. Kiek nach, ob der Kamerasensor dreckich is.',
    701: 'De Platte is heiß. Bitte nich anfassen.',
    702: 'Mit ner vorläufjen Karte kann ick nich reinjen. Drück nochma uff Reinjung, denn wird de Karte jespeichert.',
    703: 'Ick fang mit de Staub- und Mopptrocknung an.',
    704: 'De Mopptrocknung is pausiert.',
    706: 'Fehler am Kreisel. Bitte de Aufjabe nochma starten.',
    707: 'Fehler am Fahrjestell. Bitte de Aufjabe nochma starten.',
    708: 'Der Weg zur Ladestation is zu. Kiek nach, ob wat im Weg steht.',
    711: 'De Desinfektion fängt an.',
    712: 'Det Waschbrett is heiß. Bitte nich anfassen.',
    715: 'In de Station fehlt der Mopp. Setz den rin, denn mach ick weiter.',
    716: 'In de Station fehlt der Mopp. Setz den rin - solange arbeete ick im Standardmodus.',
    717: 'Der Mopp sitzt nich richtich. Rück den zurecht, denn mach ick weiter.',
    718: 'Det lässt sich im Energiesparmodus nich ändern. Mach den Energiesparmodus aus und probier nochma.',
    719: 'Fehler beim Moppwechsel.',
    722: 'Der Mopp kommt in heißet Wasser, damit er warm wird. Darum dauert et een bisschen länger. Hab een bisschen Jeduld.',
    723: 'Beim Kartenmalen kiek, dat allet jut beleuchtet is. Stell nischt in de Türen und schieb weder mir noch de Station rum.',
    724: 'Der Mopp liegt in de Station nich richtich. Rück den jleich zurecht.',
    725: 'Fehler an de Moppabdeckung.',
    726: 'Fehler am Rollmopp.',
    728: 'Ick fang mit de Bodenpflege an.',
    729: 'Der Mopp wird jerade jewechselt. Probier später nochma.',
    731: 'Mein Schmutzwassertank is voll. Stell mir zurück uff de Station, damit ick den Mopp waschen kann.',
    752: 'Ick mach mit de Bodenpflege weiter.',
    754: 'Ick hab mir jefunden. Ick mach mit de Bodenpflege weiter.',
    755: 'Der Lasersensor macht et nich. Kiek nach, ob da wat dreckich is oder klemmt.',
    757: 'Mein Schmutzwassertank is voll. Mach den jleich leer.',
    758: 'Zu wenich Wasser. Stell mir zurück uff de Station und drück uff Start, denn wird nachjefüllt.',
    765: 'Der Mopp wird jerade jewechselt. Probier später nochma.',
    771: 'Der Rollmopp bleibt stehen oder is blockiert.',
    775: 'Solange der Mopp läuft, lass de Klappe zu.',
    777: 'De Zeit is um. Kiek nach, ob unterm Jerät wat im Weg is.',
    778: 'Achtung, pass uff deine Finger uff.',
    779: 'De Zeit fürs Mopprausnehmen is um. Ick hör uff.',
    780: 'Det Uffnehmen oder Ablejen vom Mopp hat nich jeklappt. Nimm den Mopp aus de Halterung und lej den wieder ins Fach an de Klappe.',
    782: 'Fehler beim Uffflockern von de Rolle. Mach se sauber, denn jeht et weiter.',
    784: 'Wenn Schritt eens fertich is, fahr ick von alleene aus de Station.',
    785: 'Mach de Waschbrett-Basis bitte mit ner Bürste oder eem Tuch sauber. Danach tippste in de App uff Reinjung beenden.',
    786: 'De Waschbrett-Basis is sauber.',
    787: 'Ick fahr von alleene zur Station zurück und mach den Mopp sauber und trocken.',
    795: 'Ick fang mit de Reinjung von de Waschbrett-Basis an. Det dauert ungefähr zwee Minuten.',
    797: 'Da stimmt vielleicht wat nich mitm Jerät. Ruf beim Kundendienst an.',
    798: 'De Selbstreinjung von de Station dauert ungefähr vier Minuten. Schieb mir solange nich rum.',
    799: 'De Zeit is um. Kiek nach, ob een Tier oder een Hindernis unterm Jerät steht.',
    805: 'Ick fang an, den jroben Dreck uffzusaujen.',
    812: 'Stell mir bitte zum Laden in de Station.',
    813: 'Ick fang mit de kräftjen Absaugung vom Dreck an.',
    814: 'Ick fang mit de Selbstreinjung von de Station und de kräftjen Absaugung an.',
    823: 'Der Wasserstand im Waschbrett passt nich. Mach det sauber, bevor et losjeht.',
    824: 'Der Rollmopp bleibt stehen oder is blockiert.',
    828: 'Der Filter is durch. Mach den bald sauber.',
    849: 'Ick fang an, Staubbehälter und Beutel zu trocknen.',
    850: 'Det Trocknen von Staubbehälter und Beutel is jestoppt.',
    857: 'Setz bitte det Waschbrett rin.',
    910: 'Na, willkommen in de Ausstellung für Saugroboter.',
    915: 'Der Wasserstand im Waschbrett passt nich. Mach den Filter sauber, denn verstopft nischt.',
})
