"""Hessisch - Frankfurt und Rhein-Main, lautgetreu geschrieben.

Diese Fassung wurde durchgehend überarbeitet. Vorher mischten sich zwei
Schreibweisen, und die Lautung war nur halb umgesetzt.

Die Regeln, nach denen hier geschrieben wird:

* -ig wird -isch:      fertisch, dreckisch, wenisch, rischtisch, gleisch
* ich/mich/dich/sich:  isch, misch, disch, sisch
* Lenisierung:         p->b, t->d (basst, Bladd, gud, bidde, Duch, Debbisch)
* sp->schb, st->schd:  schbäder, schdell, schdimmt - und im Wortinneren
                       erschd, feschd, bischd, Fenschder, Bürschd
* ue wird i:           Kisch (Küche), zurick, misse, Glick, Fieß, fer
* ei wird aa:          waaß, haaß, aans, zwaa, kaa
* eu/aeu wird ei:      Beidel, Leit, heit, Freind
* b/w zwischen Vokalen: iwwer, owwe, unne, widder, dribbe

Das k bleibt: "Gard" für Karte wäre rheinhessisch. Frankfurt sagt Kart,
Kerb, Kuh, kaputt.

Achtung beim Lesen: **aa** heißt "an" (isch fang aa, guck der des aa),
**aach** heißt "auch". Das ist der häufigste Schreibfehler im Hessischen.

Der Ton ist gutgelaunt-geschwätzig statt grantig - der hessische Roboter
kommentiert gern und nimmt sich nicht zu ernst. Fehlermeldungen bleiben
trotzdem klar.
"""

from __future__ import annotations

from . import muster
from ..i18n import t

KEY = "hessisch"
NAME = t("hessisch.name")
BESCHREIBUNG = t("hessisch.beschreibung")
LANG_ID = "HESSEN"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "Isch wart uff des Netzwerk.",
    2: "Mit'm WLAN hat's net geklappt. Guck der mol des Passwort aa.",
    3: "Isch komm net uff de Server. Guck der mol dei Netzwerk aa.",
    4: "Isch hab de Netzwerkmodus verlasse.",
    5: "Netzwerk basst, isch bin dribbe.",
    6: "Mit'm Netzwerk hat's net geklappt. Probier's schbäder nochemol.",
    304: "Des Netzwerk is verbunne.",
    306: "Des hab isch net verschdanne. Rischt erschd es Netzwerk ei.",
    313: "De Empfang is schlecht. Schdell misch woanners hie.",
    377: "Es Netzwerk lässt sisch net eirischte. Frag beim Kundedienst nach.",
    378: "Es Passwort schdimmt net. Rischt es Netzwerk nochemol ei.",
    379: "Isch find kaa WLAN. Nimm es Zwaakommavier-Gigahertz-Netz.",
    380: "Isch hab kaa IP-Adress kriegt. Guck emol in dein Router.",
    381: "Isch komm net uff de Server. Frag beim Kundedienst nach.",
    382: "Isch komm net ins Netz. Guck, ob dei Internet läft.",
    383: "Es Netzwerk lässt sisch net eirischte. Frag beim Kundedienst nach.",
    385: "Isch verbinn misch grad mit'm Netzwerk.",

    # --- Reinigung ---------------------------------------------------
    7: "Ei gude, dann geht's los. Isch fang aa zu sauge.",
    8: "Isch mach den aane Fleck sauber.",
    9: "Die eigeschdellte Reinischung geht jetzt los.",
    10: "Isch mach weider, wo isch uffgehört hab.",
    11: "Isch mach e Paus.",
    12: "Fertisch. Alles sauber.",
    54: "Basst, isch saug weider.",
    55: "Basst, isch fahr weider zur Station.",
    56: "Isch mach des Zimmer sauber.",
    57: "Isch mach die Zone sauber.",
    58: "Isch mach mei Arbeit weider.",
    61: "Isch fang aa zu wische.",
    62: "Du schdeuerst misch jetzt selber.",
    64: "Des hat net geklappt. Isch fahr zur Station.",
    65: "Isch fahr weider zur Station.",
    77: "Schdell misch uff en Hartbodde, dann fang isch aa.",
    82: "Isch mal jetzt e Kart vun de Wohnung.",
    83: "Isch mal weider aa de Kart.",
    84: "Die Kart is fertisch.",
    85: "Basst, isch mal weider.",
    86: "Des hat net geklappt. Isch fang mit'm Male neu aa.",
    105: "Uff geht's, isch fang aa.",
    126: "Isch fang aa zu sauge.",
    127: "Isch mach de Fleck sauber.",
    128: "Isch wisch de Fleck.",
    129: "Die eigeschdellte Reinischung geht los.",
    130: "Es eigeschdellte Male geht los.",
    133: "Isch mach die ausgesuchte Zimmer sauber.",
    134: "Isch wisch die ausgesuchte Zimmer.",
    135: "Isch mach die Zone sauber.",
    136: "Isch wisch die Zone.",
    137: "Isch saug weider.",
    138: "Isch wisch weider.",
    139: "Isch komm zurick.",
    143: "Fertisch. Do sieht's jetzt sauber aus, gell.",
    144: "Gewischt hab isch aach schon.",
    145: "Basst, isch saug weider.",
    146: "Basst, isch mal weider.",
    150: "Do komm isch net hie. Nimm bidde die Schberrzone weg.",
    152: "Mei Weg is verschdellt. Nimm die Schberrzone weg oder schdell misch woanners hie.",
    163: "Isch guck grad mit de Kamera.",
    164: "So, des war's. Feierohmd.",
    171: "Die schlaue Hindernisumfahrung is aa.",
    172: "Die schlaue Hindernisumfahrung is aus.",
    257: "Die Kameraiwerwachung is aus.",
    280: "Isch fang mit de eigeschdellte Reinischung aa.",
    321: "Isch fang mit'm grindlische Fleckewische aa.",
    344: "Basst scho, isch saug erschd un wisch dann.",
    362: "Des Wischduch sitzt net rischtisch. Dann saug isch halt nur.",
    363: "Es Sauge is fertisch, jetzt wisch isch.",
    366: "Do is e Fleck, isch mach en sauber.",
    367: "Basst scho, isch mach de Fleck sauber.",
    368: "Do is e Fleck. Isch mach en sauber, wenn isch gewasche hab.",
    369: "Basst scho, isch mach do sauber.",
    424: "Isch waaß net, wo isch bin. Schdell misch uff e freie Fläch un fang neu aa.",
    433: "Isch mach noch e Extrarund.",
    434: "Die Extrarund is fertisch, isch mach normal weider.",
    435: "Isch fahr aus dem Bereisch raus.",
    450: "In ere Schberrzon fang isch net aa. Schdell misch woanners hie.",
    451: "Im verschdeckte Bereisch fang isch net aa. Schdell misch woanners hie.",
    677: "Do komm isch net hie. Nimm die Schberrzone oder die Schwelle weg.",
    678: "Mei Weg is verschdellt. Nimm die Schberrzone oder die Schwelle weg.",
    679: "Isch schdeh in ere Schberrzon. Nimm misch do bidde raus.",
    680: "Isch mal erschd e Kart, dann mach isch sauber.",
    681: "Basst scho, isch mach weider.",

    # --- Akku und Laden ----------------------------------------------
    13: "Isch fahr heim zum Uffladde.",
    14: "Mei Batterie is bald leer. Isch fahr heim zum Ladde un mach dann weider.",
    17: "Schdell misch bidde widder uff die Station.",
    18: "Isch lad grad uff.",
    19: "Nimm misch vun de Station, eh's de misch ausmachst.",
    20: "Mei Batterie is bald leer.",
    21: "Batterie leer. Isch schalt misch jetzt aus.",
    25: "De Akku is zu schwach fer die eigeschdellte Reinischung.",
    47: "Isch fang aa zu ladde.",
    48: "Batterie is schwach, isch fahr zur Station.",
    50: "Mit'm Ladde schdimmt was net. Mach mer die Kontakte sauber.",
    87: "Batterie schwach, isch fahr zur Station.",
    301: "Isch lad grad uff.",
    302: "Isch bin grad am Schaffe.",
    303: "Isch ruh misch grad aus.",
    307: "Isch lad grad uff.",
    692: "Isch fahr zum Ladde. En extra Reinischung geht grad net.",
    708: "De Weg zur Ladestation is zu. Guck noch, ob was im Weg schdeht.",
    812: "Schdell misch bidde zum Ladde in die Station.",

    # --- Station und Wischen -----------------------------------------
    59: "Die Kart is fertisch. Nimm de Wassertank raus.",
    106: "Isch wasch mei Wischduch.",
    107: "Isch drockne mei Wischdicher.",
    110: "Isch saug mein Schdaab aus.",
    111: "Mir fehle die Wischdicher. Mach se mer bidde draa.",
    112: "Schdell misch erschd emol in die Station.",
    113: "Fertisch. Mach bidde de Schmutzwassertank leer.",
    114: "Die Wischdicher sinn draa.",
    115: "Die Wischdicher sinn runner.",
    140: "E neue Umgebung. Isch fahr zur Station.",
    148: "Isch fahr zur Station un mach misch selber sauber.",
    169: "Die Wischdicher sinn drocke.",
    177: "Isch fahr los.",
    179: "Es Wischduch is sauber. Aber es Frischwasser geht mer aus.",
    181: "Mir geht es Wasser aus. Füll mer bidde nach.",
    186: "Guck der bidde de Frischwassertank aa.",
    187: "Des dauert so fünf bis zehn Minudde.",
    188: "Isch dock automatisch aa.",
    209: "Basst scho, isch fahr zur Station un wasch mei Wischduch.",
    210: "Isch wasch die Wischdicher.",
    211: "Aussauge geht nur, wenn isch in de Station schdeh.",
    212: "Basst scho, isch saug misch aus.",
    213: "Drockne geht nur, wenn isch in de Station schdeh.",
    214: "Isch drockne grad.",
    215: "Basst scho, isch fang mit'm Drockne aa.",
    216: "Do muss erschd des Wischduch dro.",
    278: "Basst scho, es Drockne is fertisch.",
    298: "Isch mach des Waschbredd sauber.",
    305: "Basst scho, isch mach es Waschbredd sauber. Butz es inne mit ere Bürschd.",
    311: "Die Wischdicher sinn runner.",
    318: "Mei Wischduch is widder sauber.",
    349: "Guck, dass die Station Schdrom hat, un schdell misch druff.",
    350: "Isch fang mit'm Eirischte vun de Station aa.",
    351: "Die Station is eigerischt.",
    352: "Es Eirischte hat net geklappt. Guck in de App nach.",
    360: "Isch loss es Wasser ausm Tank.",
    361: "Es Wasser is draußt.",
    371: "Nimm bidde es Waschbredd raus.",
    372: "Es Frischwasser läft ei.",
    373: "Es Wasser is drin. Wart zehn Sekunde, dann geht es weider.",
    374: "Butz de Bodde vun de Station mit ere Bürschd oder eme Duch.",
    375: "Schieb de Dreck zum Aussauge hie. Des dauert e bissi.",
    376: "Es Aussauge is fertisch. Butz es Waschbredd extra un setz es widder nei.",
    396: "Isch mach es Wassermodul leer. Des dauert e bissi.",
    397: "Es Wasser is owwe un unne draußt.",
    398: "Die Kart is fertisch. Guck se der in de App aa un schdell misch zurick.",
    399: "De Test is fertisch. Schdell misch zurick uff die Station.",
    400: "Die Selbschdreinischung is fertisch. Schdell misch jetzt uff es rischtische Schdockwerk.",
    401: "Schdell misch uff die Station, dann fang isch mit de Selbschdreinischung aa.",
    478: "Wenn isch gewasche hab, mach isch mit'm Sauge weider.",
    479: "Basst scho, fang dei Arbeit neu aa.",
    480: "Füll genug Wasser ei, dass es fer's Nächste reischt.",
    481: "Isch mach de Handschdaabsauger leer.",
    482: "Isch mach de Handschdaabsauger leer. Misch selbst saug isch dann aus.",
    483: "Isch mach de Handschdaabsauger leer. Es Wischduch wasch isch dann.",
    484: "Isch mach de Handschdaabsauger leer. Gesaugt werd dann.",
    485: "Isch saug misch grad aus. De Handschdaabsauger kommt dann.",
    486: "Isch wasch grad es Wischduch. De Handschdaabsauger kommt dann.",
    487: "Guck, dass isch in de Station schdeh.",
    636: "Mei Wischduch is arg dreckisch. Isch muss zur Station.",
    638: "Isch saug misch weider aus.",
    661: "Isch mach es Waschbredd sauber. Des dauert e knapp Minudd.",
    662: "Isch mach elektrolysiertes Wasser zum Butze.",
    689: "Isch fang aa, Schdaabbehälder un Beidel zu drockne.",
    690: "Es Drockne vun Schdaabbehälder un Beidel is geschdoppt.",
    691: "De Mopp werd grad gewasche. Probier schbäder nochemol.",
    701: "Die Bladd is haaß. Bidde net aafasse.",
    703: "Isch fang mit de Schdaab- un Mopptrocknung aa.",
    704: "Die Mopptrocknung is pausiert.",
    711: "Die Desinfektion fängt aa.",
    712: "Es Waschbredd is haaß. Bidde net aafasse.",
    715: "In de Station fehlt de Mopp. Setz en nei, dann mach isch weider.",
    716: "In de Station fehlt de Mopp. Setz en nei - solang schaff isch im Schdandardmodus.",
    717: "De Mopp sitzt net rischtisch. Rick en zurescht, dann mach isch weider.",
    722: "De Mopp kommt in haaß Wasser, damit er warm werd. Drum dauert's e bissi länger. Hab en Moment Geduld.",
    724: "De Mopp liegt in de Station net rischtisch. Rick en gleisch zurescht.",
    728: "Isch fang mit de Boddepfleg aa.",
    729: "De Mopp werd grad gewechselt. Probier schbäder nochemol.",
    731: "Mei Schmutzwassertank is voll. Schdell misch zurick uff die Station, dass isch de Mopp wasche kann.",
    752: "Isch mach mit de Boddepfleg weider.",
    754: "Isch hab misch gefunne. Isch mach mit de Boddepfleg weider.",
    757: "Mei Schmutzwassertank is voll. Mach en gleisch leer.",
    758: "Zu wenisch Wasser. Schdell misch zurick uff die Station un drick uff Start, dann werd nachgefüllt.",
    765: "De Mopp werd grad gewechselt. Probier schbäder nochemol.",
    775: "Solang de Mopp läuft, loss die Klabb zu.",
    779: "Die Zeit fer's Moppraushole is um. Isch hör uff.",
    780: "Es Uffnehme oder Ablege vum Mopp hat net geklappt. Nimm de Mopp aus de Halderung un leg en widder ins Fach an de Klabb.",
    784: "Wenn Schritt aans fertisch is, fahr isch vun alleen aus de Station.",
    785: 'Mach die Waschbredd-Basis bidde mit ere Bürschd oder eme Duch sauber. Danach tippst de in de App uff "Reinischung beende".',
    786: "Die Waschbredd-Basis is sauber.",
    787: "Isch fahr vun alleen zur Station zurick un mach de Mopp sauber un drocke.",
    795: "Isch fang mit de Reinischung vun de Waschbredd-Basis aa. Des dauert ungefähr zwaa Minudde.",
    798: "Die Selbschdreinischung vun de Station dauert ungefähr vier Minudde. Schieb misch solang net rum.",
    805: "Isch fang aa, de grobe Dreck uffzusauge.",
    813: "Isch fang mit de kräftische Absaugung vum Dreck aa.",
    814: "Isch fang mit de Selbschdreinischung vun de Station un de kräftische Absaugung aa.",
    849: "Isch fang aa, Schdaabbehälder un Beidel zu drockne.",
    850: "Es Drockne vun Schdaabbehälder un Beidel is geschdoppt.",
    857: "Setz bidde es Waschbredd nei.",

    # --- Fehler und Wartung ------------------------------------------
    24: "Guck mol, ob de Wassertank rischtisch dringschdeckt.",
    34: "Do fehlt e Deil. Setz es bidde nei.",
    35: "Mit de Hauptbürschd schdimmt was net. Mach se mer sauber.",
    36: "Mit de Seidebürschd schdimmt was net. Mach se mer sauber.",
    37: "Mit'm rechte Rad schdimmt was net.",
    38: "Mit'm linke Rad schdimmt was net.",
    39: "Mei Räder hänge in de Luft. Mach die Abschdurzsensore sauber.",
    40: "Ei verrescht, isch häng fescht. Machst misch bidde frei?",
    41: "Mei Räder hänge in de Luft. Schdell misch woanners hie.",
    42: "Guck der bidde mein Filder aa.",
    43: "Mit meim Schdoßbügel schdimmt was net. Drick emol sanft druff.",
    44: "Do schdimmt was net. Guck bidde in de Aaleitung nach.",
    52: "Isch schdeh schief. Schdell misch bidde grad hie.",
    66: "Mei Filder is hie. Dausch'n bidde aus.",
    67: "Die Seidebürschd is hie. Dausch se bidde aus.",
    68: "Die Hauptbürschd is hie. Dausch se bidde aus.",
    71: "Guck emol, ob am Laser-Abschdandssensor ebbes klemmt.",
    72: "Die Abdeckung vum Lasersensor klemmt.",
    73: "Mit'm Kantesensor schdimmt was net.",
    75: "De Filder is feucht oder verschdopft.",
    81: "Mit'm Debbischsensor schdimmt was net.",
    91: "De Frischwassertank fehlt. Setz'n bidde nei.",
    93: "Zu wenisch Wasser drin. Füll bidde nach.",
    97: "Do fehlt de Schdaabbeidel.",
    101: "Die Klabb vun de Absaugstation is uff, oder de Beidel fehlt. Mach die Klabb zu oder leg en Beidel nei.",
    102: "De Schdaabbeidel is voll oder de Kanal is verschdopft.",
    104: "Es Waschbredd is net drin. Setz es nei un mach die Klammern uff beide Seide fescht.",
    108: "Mit'm Wasserschdand vum Waschbredd schdimmt was net. Mach es sauber.",
    109: "Mit'm Schmutzwassertank schdimmt was net. Guck, ob er drin un leer is.",
    118: "Die Knöpp sinn geschberrt. Halt die Dast an de Station gedrickt.",
    142: "Des Wischduch is hie. Dausch es bidde aus.",
    156: "Mei Wischduch is net draa.",
    166: "Do hat sisch was in mei Wischduch gewickelt. Mach's bidde weg.",
    170: "Die Daschdesperr is aa. Halt die Dast an de Station gedrickt, dann geht's widder uff.",
    173: "Dausch bidde des Silberione-Modul aus.",
    244: "Die Reinischungsmittelflasch is dro.",
    245: "Mehr Karte gehe net. Lösch bidde aane in de App.",
    248: "Des Wischduch fehlt. Mach es dro un probier nochemol.",
    266: "Dausch bidde des Reinischungsmittel aus.",
    267: "Mei Sensore sinn dreckisch. Mach se mer bidde sauber.",
    296: "Guck emol, ob de Schmutzwassertank voll is.",
    297: "Die Reinischungsmittelflasch is dro. Wenn de se noch nie benutzt hast, guck in de App.",
    299: "Die Reinischungsmittelflasch un es Nachfüllmodul sinn dro.",
    300: "Des Zubehör kenn isch net.",
    312: "Iwwer des Zubehör waaß isch nix. Dausch es aus, wenn es hie is.",
    315: "Des Wischduch is net in de Station. Leg es nei un probier nochemol.",
    316: "In de Station liegt doch schon e Wischduch.",
    319: "Des Wischduch is net runnergange. Nimm es vun Hand ab.",
    320: "Des Wischduch is net drogange. Mach es vun Hand dro.",
    329: "Isch test misch grad selber. Nimm misch net vun de Station runner.",
    330: "Wart, bis de Selbschdtest fertisch is.",
    331: "Alles in Ordnung. Isch hab nix gefunne.",
    332: "Isch hab en Fehler gefunne. Guck emol in de App nach.",
    353: "De Schmutzwasserbehälder is drin.",
    354: "De Schmutzwasserbehälder is raus.",
    355: "Zu wenisch Wasser. Füll de Frischwassertank nach.",
    356: "De Fehler is noch do. Die eigeschdellte Reinischung is abgesagt.",
    358: "Setz bidde de Schmutzwasserbehälder nei.",
    384: "Im automatische Wassermodul is kaa Wasser.",
    386: "Mei Schmutzwasserbehälder is voll. Isch fahr zurick un mach en leer.",
    387: "Es Leermache is fertisch. Isch mach weider.",
    388: "Do derf isch net hie. Schdell misch woanners hie.",
    389: "De Laser fährt net runner. Guck, ob ebbes klemmt.",
    390: "De Laser fährt net ruff. Guck, ob ebbes klemmt.",
    391: "Schdell misch uff e freie Fläch, eh's losgeht.",
    392: "Im Clean-Genius-Modus lässt sisch des net eischdelle.",
    393: "Mei Schmutzwasserbehälder is dreckisch. Mach en gleisch sauber.",
    394: "De Wassersensor will net mehr.",
    426: "Isch bin abgerutscht un häng fescht. Isch probier's weider.",
    437: "Basst widder. Drick uff Start, dann geht's weider.",
    438: "De Schdoßbügel klemmt. Drick emol sanft druff.",
    439: "Die Laserabdeckung klemmt. Drick emol sanft druff.",
    440: "E Rad hängt in de Luft. Schdell misch uff e freie Fläch.",
    441: "Do hat sisch was um die Hauptbürschd gewickelt. Mach's bidde sauber.",
    442: "Do hat sisch was um die Seidebürschd gewickelt.",
    443: "Um mei Räder hat sisch was gewickelt.",
    444: "Schdell misch bidde uff e freie Fläch, dann fang isch aa.",
    445: "Mei Wischduch is mer runnergefalle. Guck emol in de Näh.",
    446: "Am Wischduchhalder hängt was draa.",
    447: "Die Station hat kaan Schdrom. Guck bidde emol nach.",
    448: "De Schmutzwassertank fehlt. Setz'n bidde nei.",
    449: "Uff'm Debbisch fang isch net aa. Schdell misch uff de Hartbodde.",
    452: "Mit'm Debbischsensor schdimmt was net. Dreh misch um un butz es weiße Loch.",
    453: "Mit'm Kantesensor schdimmt was net. Butz misch rechts aa.",
    454: "Zu wenisch Wasser im Tank. Füll mer bidde nach.",
    455: "De Frischwassertank sitzt net rischtisch drin.",
    456: "De Schmutzwassertank is voll oder er fehlt.",
    457: "De Schmutzwassertank is voll oder net drin. Guck emol nach.",
    458: "De Schdaabbeidel sitzt net rischtisch.",
    459: "De Wischduchhalder sitzt net rischtisch. Guck emol nach.",
    460: "De Geruchsfilder is uffgebraucht. Dausch'n bidde aus.",
    639: "Do fehlt de Filder vum Waschbredd.",
    658: "De Kalkschutz is uffgebraucht. Dausch'n bidde aus.",
    663: "Mit'm Wasserschdand im Waschbredd schdimmt was net. Mach de Filder sauber.",
    673: "Um mei Beinsche hat sisch villeischt ebbes gewickelt. Mach es vor'm Start sauber.",
    674: "Mei Mopp klemmt villeischt oder hat sisch was neigewickelt. Guck noch un mach en sauber.",
    682: "Mei Mopp dreht sisch net mehr.",
    683: "De Mopp is net dro. Mach erschd de Mopp dro un probier dann nochemol.",
    696: "Fehler an de Klabb.",
    699: "Sensorfehler. Guck noch, ob de Kamerasensor dreckisch is.",
    706: "Fehler am Kreisel. Schdart die Uffgab bidde nochemol.",
    707: "Fehler am Fahrgeschdell. Schdart die Uffgab bidde nochemol.",
    719: "Fehler beim Moppwechsel.",
    725: "Fehler an de Moppabdeckung.",
    726: "Fehler am Rollmopp.",
    755: "De Lasersensor will net. Guck noch, ob do was dreckisch is oder klemmt.",
    771: "De Rollmopp bleibt schdehe oder is blockiert.",
    777: "Die Zeit is um. Guck noch, ob unnerm Gerät was im Weg is.",
    778: "Achtung, pass uff dei Finger uff.",
    782: "Fehler beim Uffflockern vun de Roll. Mach se sauber, dann geht's weider.",
    797: "Do schdimmt villeischt was net mit'm Gerät. Ruf beim Kundedienst aa.",
    799: "Die Zeit is um. Guck noch, ob en Viesch oder en Hindernis unnerm Gerät schdeht.",
    823: "De Wasserschdand im Waschbredd basst net. Mach's sauber, eh's losgeht.",
    824: "De Rollmopp bleibt schdehe oder is blockiert.",
    828: "De Filder is durch. Mach en bald sauber.",
    915: "De Wasserschdand im Waschbredd basst net. Mach de Filder sauber, dann verschdopft nix.",

    # --- Wegfindung ---------------------------------------------------
    30: "Isch guck grad, wo isch bin.",
    31: "Isch waaß net, wo isch bin. Dann fang isch halt neu aa.",
    45: "Isch bin do!",
    149: "Do komm isch net hie. Räum bidde weg, was im Weg schdeht.",
    151: "Mei Weg is verschdellt. Räum bidde was weg.",
    153: "Isch schdeh in ere Schberrzon. Nimm misch do bidde raus.",
    258: "Isch fang aa rumzufahre.",
    259: "Isch fahr dohie, wo de's gesagt hast.",
    260: "Isch fahr weider rum.",
    261: "Isch fahr weider dohie.",
    262: "Isch waaß net, wo isch bin.",
    698: "Es Kartemale is fertisch. Isch find die Station net un fang selber aa zu reinische.",
    702: "Mit ere provisorische Kart kann isch net reinische. Drick nochemol uff Reinischung, dann werd die Kart geschbeischert.",
    723: "Beim Kartemale guck, dass alles gud beleuscht is. Schdell nix in die Diere un schieb weder misch noch die Station rum.",

    # --- Bedienung -----------------------------------------------------
    26: "Isch setz misch zurick uff die Werkseinschdellung.",
    27: "Isch mach e Update. Dauert fünf Minudde. Bidde net ausschalte.",
    28: "Des Update hat geklappt.",
    29: "Des Update hat net geklappt. Probier's schbäder nochemol.",
    46: "Roboter un Handy sinn verbunne.",
    116: "Die Kindersischerung is aa. Die Knöpp sinn geschberrt.",
    117: "Die Kindersischerung is aus.",
    162: "Die Kamera is aa.",
    293: "Aaruf sinn aa.",
    294: "Aaruf sinn aus.",
    338: "De Videoaaruf schdeht.",
    339: "Aaruf abgelehnt.",
    340: "Kaa Antwort.",
    364: "Isch rischt de Videocode ei.",
    365: "Es Livebild is aus.",
    421: "Ei gude. Ab jetzt babbel isch Hessisch mit der.",
    463: "Ei gude, schee dass de do bischd. Mach de Deckel uff un scann de QR-Code.",
    464: "Damit schbäder alles glatt läft, schdell misch vor'm Start uff die Station.",
    465: 'Schdell misch vor\'m Start uff die Station. Wenn de "Isch lad uff" hörst, basst es.',
    466: "Mach bidde die Diere uff un räum de Bodde frei.",
    467: "Schdell misch uff die Station un fang es Male neu aa.",
    468: "Guck der die Kart bidde in de App aa.",
    630: "Ei gude, schee dass de do bischd. Mach de Deckel uff un scann de QR-Code.",
    631: "Schee, dass de disch fer de Dreame entschiede hast. Mach die Klabb uff un scann de QR-Code, dann kannst de die App ladde.",
    632: "De Schbrachwechsel dauert e halb Minudd.",
    633: "De Schbrachwechsel hat net geklappt.",
    634: "Isch fang aa, die Haar zu entwirrn.",
    697: "Isch bin geschberrt. Mach erschd die Kindersischerung aus.",
    718: "Des lässt sisch im Energieschbarmodus net ännern. Mach de Energieschbarmodus aus un probier nochemol.",
    910: "Ei gude un willkomme in de Ausschdellung fer Saugroboter.",

    # --- Sprachassistent ------------------------------------------------
    190: "Basst, isch fang aa zu sauge.",
    191: "Basst, isch saug un wisch.",
    192: "Basst, isch wisch.",
    193: "Basst, isch saug.",
    194: "Isch bin doch schon am Sauge.",
    195: "Basst scho, isch mach des Zimmer sauber. Guck, dass die Dür uff is.",
    196: "Basst scho, isch saug de Bodde. Guck, dass die Dür uff is.",
    197: "Basst scho, isch wisch de Bodde. Guck, dass die Dür uff is.",
    198: "Basst scho, isch saug un wisch. Guck, dass die Dür uff is.",
    199: "Des Zimmer kenn isch net. Guck in de App, wie es haaßt.",
    200: "Mach's gud. Ade.",
    201: "Basst scho, isch mach weider.",
    202: "Basst scho, isch hör uff un fahr zum Ladde.",
    203: "Basst scho, isch fahr zum Ladde.",
    204: "Basst scho, isch fang mit'm Male aa. Mach alle Diere uff.",
    205: "Basst scho, isch fahr vun de Station runner.",
    206: "Basst scho, isch guck, wo de bischd.",
    207: "Isch find disch net. Schdell disch in mei Sischtweit.",
    208: "Do bischd de ja. Isch komm sauge.",
    217: "Mehr Saugkraft geht net.",
    218: "Wenischer Saugkraft geht net.",
    219: "Mehr Wasser geht net.",
    220: "Wenischer Wasser geht net.",
    221: "Basst scho.",
    222: "Saugschduf leis.",
    223: "Saugschduf normal.",
    224: "Saugschduf schdark.",
    225: "Saugschduf Turbo.",
    226: "Des Wischduch is leischt feucht.",
    227: "Des Wischduch is feucht.",
    228: "Des Wischduch is nass.",
    229: "Heit is",
    230: "Heit is de aanunzwanzischste Februar zwaadausend-zwaaunzwanzisch.",
    231: "Heit is Mondag.",
    232: "Heit is Dienschdag.",
    233: "Heit is Mittwoch.",
    234: "Heit is Donnerschdag.",
    235: "Heit is Freidag.",
    236: "Heit is Samsdag.",
    237: "Heit is Sonndag.",
    238: "Basst scho, isch hör uff.",
    246: "Isch bin do hinne!",
    247: "Des hab isch jetzt net verschdanne.",
    249: "Isch schaff grad. Mach des erschd fertisch, dann geht es.",
    250: "Isch bin grad im Wischmodus. Schdell bidde um.",
    251: "Isch bin grad im Saugmodus. Schdell bidde um.",
    252: "Fertisch. Isch bin aus de eigeschdellte Reinischung raus.",
    253: "Lauder geht net.",
    254: "Leiser geht net.",
    255: "Des geht nur mit eigeschalteter Hindernisumfahrung.",
    269: "Probier nochemol, wenn isch fertisch bin.",
    275: "Des kenn isch net. In de App schdehe alle Schbrachbefehle.",
    276: "Des mach isch grad net.",
    277: "Basst scho, isch komm un mach do sauber.",
    279: "Isch saug grad. Mach des erschd fertisch un probier nochemol.",
    281: "Isch saug misch grad aus. Probier gleisch nochemol.",
    282: "Isch wasch grad mei Wischduch. Probier gleisch nochemol.",
    283: "Isch schdeh net in de Station. Probier schbäder nochemol.",
    284: "Basst scho, isch hör uff un komm sauge.",
    285: "Bleib kurz schdehe, isch guck wo de bischd.",
    286: "Do brauch isch erschd e Kart.",
    287: "Basst scho, jetzt is leis.",
    288: "Basst scho, jetzt is normal.",
    289: "Basst scho, jetzt is schdark.",
    290: "Basst scho, jetzt is Turbo.",
    291: "Basst scho, jetzt is leischt feucht.",
    292: "Basst scho, jetzt is nass.",
    308: "Des hab isch net mitkriegt. Weck misch nochemol.",
    309: "Do bischd de ja, isch komm.",
    310: "Basst scho, isch fahr gleisch do weg.",
    314: "Des geht net. Aber de kannst mer sage, isch soll misch umdrehe.",
    317: "Des geht grad net, isch mach e eigeschdellte Reinischung.",
    322: "Des kenn isch net. In de App schdehe alle Schbrachbefehle.",
    323: "Des kenn isch net. Frag misch emol, was isch alles kann.",
    324: "Isch wasch misch grad. Weck misch, wenn isch fertisch bin.",
    328: "Des kannst de mer nur sage, wenn isch grad saug.",
    341: "Do bischd de ja. Isch geh der nach. Sag Enn, wenn es reischt.",
    342: "Wo bischd de? Schdell disch ungefähr annerthalb Meter vor misch.",
    343: "Isch hab disch verlore. De bischd zu schnell. Schdell disch annerthalb Meter vor misch.",
    489: "Isch bin im Clean-Genius-Modus. Sag mer, isch soll uffhöre.",
    490: "Basst scho, eigeschdellte Reinischung: isch wisch.",
    491: "Basst scho, eigeschdellte Reinischung: isch saug.",
    508: "Isch babbel lauder.",
    509: "Isch babbel leiser.",
    510: "Gud, isch hör uff fer heit. Feierohmd.",
    511: "Isch mach grad goar nix.",
    512: "In de Kart is noch kaa Diermöbel. Trag es in de App ei.",
    513: "Basst scho, isch mach ums Diermöbel rum sauber.",
    515: "Sei so gud un heb emol die Fieß.",
    516: "Isch guck, wo dei Viesch schdeckt.",
    517: "Isch hab es gefunne. Isch fahr zum Ladde.",
    518: "Isch hab kaans gefunne. Isch fahr zum Ladde.",
    522: "Was is denn schiefgange?",
    523: "Kannst de mer des e bissi genauer sage?",
    524: "Nimm misch dohie, wo es passiert is.",
    525: "Wart kurz, isch guck mer des aa.",
    641: "Sag mer aafach, isch soll mit'm Sauge aafange.",
    642: "Sag mer aafach, isch soll schdärker sauge.",
    643: "Sag mer aafach, isch soll mehr Wasser nemme.",
    644: "Sag mer aafach, isch soll sauge un wische.",
    645: "Sag mer aafach, isch soll wische.",
    646: "Sag mer aafach, isch soll dohie komme un sauber mache.",
    647: "Sag mer aafach, isch soll erschd sauge un dann wische.",
    648: "Sag mer aafach, isch soll alles sauber mache.",
    659: "Des hab isch net verschdanne. Frag misch emol, was isch alles kann.",
    660: 'Entschuldische, des hab isch net verschdanne. Sach "Hey Rover, was kannst du", dann verzähl isch der, was isch alles kann.',
    664: "Sach zu mer: Hey Rover, fang aa zu reinische.",
    665: "Wenn alles basst, sach zu mer: Hey Rover, fang aa zu reinische.",
    666: "Sach zu mer: Hey Rover, mach die Saugkraft schdärker.",
    667: "Sach zu mer: Hey Rover, gib mehr Wasser.",
    668: "Sach zu mer: Hey Rover, fang aa zu sauge. Schbäder sachst de wische, dann wechsel isch de Modus.",
    669: "Sach zu mer: Hey Rover, fang aa zu wische. Schbäder kannst de de Modus wechsele.",
    670: "Sach zu mer: Hey Rover, komm her un mach do sauber.",
    671: "Sach zu mer: Hey Rover, fang aa zu sauge. Schbäder kannst de de Modus wechsele.",
    672: "Sach zu mer: Hey Rover, fang aa zu reinische. Schbäder kannst de die ganz Wohnung mache lasse.",
    694: "Sag mer aafach, isch soll mit'm Sauge aafange.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'De Akku is bei {p} Prozent.'
RAUM_MUSTER = 'Basst, isch mach {raum} sauber.'
RAUM_NAMEN = {
    'wohnzimmer': 'es Wohnzimmer',
    'schlafzimmer': 'es Schlafzimmer',
    'hauptschlafzimmer': 'es Hauptschlafzimmer',
    'gaestezimmer': 'es Gästezimmer',
    'arbeitszimmer': 'es Arbeitszimmer',
    'kueche': 'die Kisch',
    'esszimmer': 'es Esszimmer',
    'bad': 'es Bad',
    'balkon': 'de Balkon',
    'flur': 'de Flur',
    'hauswirtschaftsraum': 'die Waschkisch',
    'abstellraum': 'die Abschdellkammer',
    'salon': 'de Salon',
    'buero': 'es Büro',
    'gym': 'de Fitnessraum',
    'freizeitraum': 'de Freizeitraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))
