"""Kölsch - rheinisch, Kölner Färbung."""

from __future__ import annotations

from . import muster

KEY = "koelsch"
NAME = "Kölsch"
BESCHREIBUNG = (
    "Cologne's Kölsch dialect: good-humored, doesn't take anything "
    "too seriously. Et hätt noch immer joot jejange."
)
LANG_ID = "KOELN"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "Ich waade op et Netzwerk.",
    2: "Mittem WLAN hät et nit jeklapp. Luur ens noh dem Passwoot.",
    3: "Ich kumme nit op dä Server. Luur ens dinge Netzwerk aan.",
    5: "Netzwerk passt, ich ben dren.",
    6: "Mittem Netzwerk hät et nit jeklapp. Probeer et später norrens.",

    # --- Reinigung ---------------------------------------------------
    7: "Alaaf, dann jeht et los. Ich fange aan ze sauge.",
    8: "Ich maache dä eine Fleck sauber.",
    9: "De jeplante Reinijung jeht jetz los.",
    10: "Ich maache wigger, wo ich opjehürt hann.",
    12: "Fäädich. Alles sauber.",
    56: "Ich maache dat Zimmer sauber.",
    57: "Ich maache de Zone sauber.",
    58: "Ich maache ming Arbeit wigger.",
    61: "Ich fange aan ze wesche.",
    62: "Do steuers mich jetz selver.",
    82: "Ich maale jetz en Kaat vun dä Wohnung.",
    84: "De Kaat es fäädich.",
    105: "Op jeht et, ich fange aan.",
    126: "Ich fange aan ze sauge.",
    137: "Ich sauge wigger.",
    138: "Ich wesche wigger.",
    139: "Ich kumme zoröck.",
    143: "Fäädich. Do süht et jetz sauber uss.",
    144: "Jewescht hann ich och ald.",
    164: "So, dat wor et. Fierovend.",
    433: "Ich maache noch en Extrarund.",
    434: "De Extrarund es fäädich, ich maache normal wigger.",

    # --- Akku und Laden ----------------------------------------------
    13: "Ich fahre heim zum Oplade.",
    14: "Ming Batterie es bal leer. Ich fahre heim zum Lade un maache dann wigger.",
    17: "Stell mich bitte widder op de Station.",
    18: "Ich lade jrad op.",
    20: "Ming Batterie es bal leer.",
    21: "Batterie leer. Ich maache jetz Schluss.",
    47: "Ich fange aan ze lade.",
    48: "Batterie es schwaach, ich fahre zur Station.",
    50: "Mittem Lade stemmp jet nit. Maach ens de Kontakte sauber.",
    301: "Ich lade jrad op.",
    302: "Ich ben jrad am Schaffe.",

    # --- Station und Wischen -----------------------------------------
    106: "Ich wesche ming Weschdoch.",
    107: "Ich drüjje ming Weschdöcher.",
    110: "Ich sauge minge Stoff eruss.",
    111: "Mir fählen de Weschdöcher. Maach se mer bitte draan.",
    112: "Stell mich eesch ens en de Station.",
    113: "Fäädich. Maach bitte dä Schmotzwassertank leer.",
    114: "De Weschdöcher sinn draan.",
    115: "De Weschdöcher sinn erav.",
    148: "Ich fahre zur Station un maache mich selver sauber.",
    169: "De Weschdöcher sinn drüjje.",
    177: "Ich fahre loss.",
    179: "Weschdoch es sauber. Ävver dat Frischwasser jeht mer uss.",
    181: "Mir jeht dat Wasser uss. Füll mer bitte noh.",
    186: "Luur ens noh dem Frischwassertank.",
    187: "Dat duurt su fönef bes zehn Minutte.",
    318: "Ming Weschdoch es widder sauber.",
    636: "Ming Weschdoch es janz schmotzich. Ich moss zur Station.",

    # --- Fehler und Wartung ------------------------------------------
    35: "Mit dä Hauptbüsch stemmp jet nit. Maach se mer sauber.",
    36: "Mit dä Sigebüsch stemmp jet nit. Maach se mer sauber.",
    37: "Mittem rääte Rad stemmp jet nit.",
    38: "Mittem lenke Rad stemmp jet nit.",
    40: "Herrjott, ich hange fess. Mähs mich bitte frei?",
    42: "Luur ens noh mingem Filter.",
    43: "Mit mingem Stoßbüjel stemmp jet nit. Dröck ens sacht drop.",
    44: "Do stemmp jet nit. Luur bitte en de Aanleitung.",
    52: "Ich stonn scheef. Stell mich bitte jrad hin.",
    66: "Minge Filter es kapott. Tuusch en bitte uss.",
    67: "De Sigebüsch es kapott. Tuusch se bitte uss.",
    68: "De Hauptbüsch es kapott. Tuusch se bitte uss.",
    91: "Dä Frischwassertank fählt. Setz en bitte erin.",
    93: "Ze winnich Wasser dren. Füll bitte noh.",
    97: "Do fählt dä Stoffbüggel.",
    102: "Dä Stoffbüggel es voll odder dä Kanal es verstopp.",
    156: "Ming Weschdoch es nit draan.",
    166: "Do hät sich jet en ming Weschdoch jewickelt. Maach et bitte fott.",
    267: "Ming Sensore sinn schmotzich. Maach se mer bitte sauber.",
    331: "Alles en Ordnung. Ich hann nix jefunge.",
    332: "Ich hann ne Fähler jefunge. Luur ens en de App.",
    426: "Ich ben avjerötsch un hange fess. Ich probeer et wigger.",
    437: "Passt widder. Dröck op Start, dann jeht et wigger.",
    441: "Do hät sich jet öm de Hauptbüsch jewickelt. Maach et bitte sauber.",
    442: "Do hät sich jet öm de Sigebüsch jewickelt.",
    443: "Öm ming Räder hät sich jet jewickelt.",
    444: "Stell mich bitte op en freie Flääch, dann fange ich aan.",
    445: "Ming Weschdoch es mer erav. Luur ens en de Nöh.",
    446: "Am Weschdochhalter hängk jet draan.",
    447: "De Station hät keine Strom. Luur bitte ens noh.",
    448: "Dä Schmotzwassertank fählt. Setz en bitte erin.",
    449: "Om Teppich fange ich nit aan. Stell mich op de Hattbodde.",
    454: "Ze winnich Wasser em Tank. Füll mer bitte noh.",
    455: "Dä Frischwassertank setz nit richtich dren.",
    456: "Dä Schmotzwassertank es voll odder hä fählt.",
    458: "Dä Stoffbüggel setz nit richtich.",
    460: "Dä Jerochsfilter es op. Tuusch en bitte uss.",
    639: "Do fählt dä Filter vum Weschbredd.",
    658: "Dä Kalkschotz es op. Tuusch en bitte uss.",

    # --- Wegfindung ---------------------------------------------------
    30: "Ich luure jrad, wo ich ben.",
    31: "Ich weiß nit, wo ich ben. Ich fange einfach neu aan.",
    45: "Ich ben hee!",
    149: "Do kumme ich nit hin. Rüüm bitte fott, wat em Wääch steht.",
    151: "Minge Wääch es verstellt. Rüüm bitte jet fott.",
    153: "Ich stonn en ner Sperrzone. Hol mich do bitte eruss.",

    # --- Bedienung -----------------------------------------------------
    26: "Ich setze mich zoröck op de Werkseinstellung.",
    27: "Ich maache en Update. Duurt fönef Minutte. Bitte nit ussmaache.",
    28: "Dat Update hät jeklapp.",
    29: "Dat Update hät nit jeklapp. Probeer et später norrens.",
    116: "De Kindersicherung es aan. De Knöpp sinn jesperrt.",
    117: "De Kindersicherung es uss.",
    162: "De Kamera es aan.",
    329: "Ich teste mich jrad selver. Nemm mich nit vun dä Station erav.",
    421: "Alaaf. Av jetz kalle ich Kölsch met dir.",
    632: "Dä Sprochwessel duurt en halve Minutt.",
    633: "Dä Sprochwessel hät nit jeklapp.",

    # --- Sprachassistent ------------------------------------------------
    190: "Joot, ich fange aan ze sauge.",
    191: "Joot, ich sauge un wesche.",
    192: "Joot, ich wesche.",
    193: "Joot, ich sauge.",
    221: "Passt.",
    246: "Ich ben hee hinge!",
    247: "Dat hann ich jetz nit verstande.",
    508: "Ich kalle luuter.",
    509: "Ich kalle leiser.",
    510: "Joot, ich maache Schluss för hück.",
    515: "Sei su joot un heff ens de Fööss.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Batterie es bei {p} Prozent.'
RAUM_MUSTER = 'Joot, ich maache {raum} sauber.'
RAUM_NAMEN = {
    'wohnzimmer': 'dat Wohnzimmer',
    'schlafzimmer': 'dat Schlofzimmer',
    'hauptschlafzimmer': 'dat Hauptschlofzimmer',
    'gaestezimmer': 'dat Jästezimmer',
    'arbeitszimmer': 'dat Arbeitszimmer',
    'kueche': 'de Kösch',
    'esszimmer': 'dat Esszimmer',
    'bad': 'dat Bad',
    'balkon': 'dä Balkon',
    'flur': 'dä Flur',
    'hauswirtschaftsraum': 'de Waschkösch',
    'abstellraum': 'de Aafstellkammer',
    'salon': 'dä Salon',
    'buero': 'dat Büro',
    'gym': 'dä Fitnessraum',
    'freizeitraum': 'dä Freizickraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))

# --------------------------------------------------------------------------
# Vollständige Abdeckung: die restlichen Ansagen des X50 Ultra Complete.
# Nummern ohne Sprachinhalt (Klänge, Tierlaute) bleiben im Original; die
# Nummern-Umsetzung des Modells versorgt 856, 858, 859, 863 und 864.
# --------------------------------------------------------------------------

TEXTE.update({
    # --- Netzwerk -----------------------------------------------------
    4: "Ich ben us dem Netzwerkmodus erus.",
    304: "Et Netzwerk es verbunge.",
    306: "Dat han ich nit verstande. Reech ehsch et Netzwerk en.",
    313: "De Empfang es schlaach. Stell mich woandershen.",
    377: "Et Netzwerk well nit. Frooch beim Kundendienst noh.",
    378: "Et Passwoot stemmp nit. Reech et Netzwerk noch ens en.",
    379: "Ich finge kei WLAN. Nemm et Zweikommavier-Gigahertz-Netz.",
    380: "Ich han kei IP-Adress krät. Kuck ens en dinge Router.",
    381: "Ich kumme nit an de Server. Frooch beim Kundendienst noh.",
    382: "Ich kumme nit en et Netz. Kuck, ov ding Internet läuf.",
    383: "Et Netzwerk well nit. Frooch beim Kundendienst noh.",
    385: "Ich verbinge mich jrad met dem Netzwerk.",

    # --- Reinigung ----------------------------------------------------
    11: "Ich maache en Paus.",
    54: "Paff, ich sauge wigger.",
    55: "Paff, ich fahre wigger zor Station.",
    64: "Dat hät nit jeklapp. Ich fahre zor Station.",
    65: "Ich fahre wigger zor Station.",
    77: "Stell mich op de haate Bodde, dann fange ich aan.",
    83: "Ich mole wigger aan der Kaat.",
    85: "Paff, ich mole wigger.",
    86: "Dat hät nit jeklapp. Ich fange met dem Mole neu aan.",
    127: "Ich maache der Fleck sauber.",
    128: "Ich wesche der Fleck.",
    129: "De jeplante Reinigung jeht loss.",
    130: "Et jeplante Mole jeht loss.",
    133: "Ich maache de usjesöhkte Zimmer sauber.",
    134: "Ich wesche de usjesöhkte Zimmer.",
    135: "Ich maache de Zon sauber.",
    136: "Ich wesche de Zon.",
    145: "Paff, ich sauge wigger.",
    146: "Paff, ich mole wigger.",
    150: "Do kumme ich nit hen. Nemm bitte de Sperrzone fott.",
    152: "Ming Wääch es verstellt. Nemm de Sperrzone fott odder stell mich woandershen.",
    163: "Ich kucke jrad met der Kamera.",
    171: "De schlaue Hindernisumfahrung es aan.",
    172: "De schlaue Hindernisumfahrung es us.",
    257: "De Kameraüberwachung es us.",
    280: "Ich fange met der enjestellte Reinigung aan.",
    321: "Ich fange met dem jründliche Fleckewesche aan.",
    344: "Allet klor, ich sauge ehsch un wesche dann.",
    362: "Et Weschduch setz nit richtich. Ich sauge stattdesse bloss.",
    363: "Et Sauge es fäädich, jetz wesche ich.",
    366: "Do es ene Fleck, ich maache dä sauber.",
    367: "Allet klor, ich maache der Fleck sauber.",
    368: "Do es ene Fleck. Ich maache dä sauber, wann ich jewäsche han.",
    369: "Allet klor, ich maache do sauber.",
    424: "Ich weiss nit, wo ich ben. Stell mich op en freie Fläch un fang neu aan.",
    435: "Ich fahre us dem Beräch erus.",
    450: "En ener Sperrzon fange ich nit aan. Stell mich woandershen.",
    451: "Em versteckte Beräch fange ich nit aan. Stell mich woandershen.",
    677: "Do kumme ich nit hen. Nemm de Sperrzone odder de Schwelle fott.",
    678: "Ming Wääch es verstellt. Nemm de Sperrzone odder de Schwelle fott.",
    679: "Ich stonn en ener Sperrzon. Holl mich do bitte erus.",
    680: "Ich mole ehsch en Kaat, dann maache ich sauber.",
    681: "Allet klor, ich maache wigger.",

    # --- Akku und Laden ------------------------------------------------
    19: "Nemm mich vun der Station erav, ih dat de mich usmähs.",
    25: "Der Akku es ze schwaach för de jeplante Reinigung.",
    87: "Batterie schwaach, ich fahre zor Station.",
    303: "Ich ruh mich jrad us.",
    307: "Ich lade jrad op.",

    # --- Fehler und Wartung --------------------------------------------
    34: "Do fählt e Deil. Setz dat bitte en.",
    39: "Ming Rädcher hange en der Luff. Maach de Avsturzsensore sauber.",
    41: "Ming Rädcher hange en der Luff. Stell mich woandershen.",
    71: "Kuck ens, ov aam Laser-Avstandssensor jet klemmp.",
    72: "De Avdeckung vum Lasersensor klemmp.",
    73: "Met dem Kantesensor stemmp jet nit.",
    75: "Der Filter es fücht odder verstopp.",
    81: "Met dem Teppichsensor stemmp jet nit.",
    108: "Met dem Wasserstand vum Weschbrett stemmp jet nit. Maach dat sauber.",
    109: "Met dem Schmotzwassertank stemmp jet nit. Kuck, ov hä dren un leddich es.",
    118: "De Knöpp sin jesperrt. Halt de Tast aan der Station jedröck.",
    142: "Et Weschduch es hin. Tuusch dat bitte us.",
    173: "Tuusch bitte et Silberione-Modul us.",
    244: "De Reinigungsmittelflasch es draan.",
    245: "Mih Kaate jonn nit. Lösch bitte ein en der App.",
    296: "Kuck ens, ov der Schmotzwassertank voll es.",
    297: "De Reinigungsmittelflasch es draan. Wann de se noch nie jebruch häs, kuck en der App.",
    298: "Ich maache et Weschbrett sauber.",
    299: "De Reinigungsmittelflasch un et Nohfüllmodul sin draan.",
    300: "Dat Zubehör kenne ich nit.",
    312: "Övver dat Zubehör weiss ich nix. Tuusch dat us, wann et hin es.",
    315: "Et Weschduch es nit en der Station. Lääch dat en un probeer noch ens.",
    316: "En der Station litt ald e Weschduch.",
    319: "Et Weschduch es nit erav. Nemm dat met der Hand av.",
    320: "Et Weschduch es nit draan. Maach dat met der Hand draan.",
    330: "Waat, bes der Selbsttest fäädich es.",
    355: "Ze winnich Wasser. Füll der Freschwassertank noh.",
    356: "Der Fähler es noch do. De jeplante Reinigung es avjesaat.",
    384: "Em automatische Wassermodul es kei Wasser.",
    388: "Do darf ich nit hen. Stell mich woandershen.",
    389: "Der Laser fährt nit erav. Kuck, ov jet klemmp.",
    390: "Der Laser fährt nit erop. Kuck, ov jet klemmp.",
    391: "Stell mich op en freie Fläch, ih dat et losjeht.",
    392: "Em Clean-Genius-Modus jeht dat nit.",
    438: "Der Stossbüjel klemmp. Dröck ens sank drop.",
    439: "De Laseravdeckung klemmp. Dröck ens sank drop.",
    440: "E Rädche hängk en der Luff. Stell mich op en freie Fläch.",
    452: "Met dem Teppichsensor stemmp jet nit. Dreih mich öm un maach dat wiesse Löchelche sauber.",
    453: "Met dem Kantesensor stemmp jet nit. Maach mich rähts sauber.",
    457: "Der Schmotzwassertank es voll odder nit dren. Kuck ens noh.",
    459: "Der Weschduchhalter setz nit richtich. Kuck ens noh.",
    663: "Met dem Wasserstand em Weschbrett stemmp jet nit. Maach dat sauber.",
    673: "Öm ming Bein hät sich villeich jet jewickelt. Maach dat vör dem Start sauber.",

    # --- Basisstation ---------------------------------------------------
    46: "Roboter un Handy sin verbunge.",
    59: "De Kaat es fäädich. Nemm der Wassertank erus.",
    140: "En neue Ömjebung. Ich fahre zor Station.",
    188: "Ich docke automatisch aan.",
    209: "Allet klor, ich fahre zor Station un wesche ming Weschduch.",
    210: "Ich wesche de Weschdöcher.",
    211: "Ussauge jeht bloss, wann ich en der Station stonn.",
    212: "Allet klor, ich sauge mich us.",
    213: "Drüjje jeht bloss, wann ich en der Station stonn.",
    214: "Ich drüjje jrad.",
    215: "Allet klor, ich fange met dem Drüjje aan.",
    216: "Do moss ehsch et Weschduch draan.",
    278: "Allet klor, et Drüjje es fäädich.",
    349: "Kuck, dat de Station Strom hät, un stell mich drop.",
    350: "Ich fange met dem Enrichte vun der Station aan.",
    351: "De Station es enjerich.",
    352: "Et Enrichte hät nit jeklapp. Kuck en der App.",
    360: "Ich looss et Wasser us dem Tank.",
    361: "Et Wasser es erus.",
    371: "Nemm bitte et Weschbrett erus.",
    372: "Et Freschwasser läuf en.",
    373: "Et Wasser es dren. Waat zehn Sekunde, dann jeht et wigger.",
    374: "Maach der Bodde vun der Station met ener Bösch odder enem Duch sauber.",
    375: "Scheev der Dreck zum Ussauge hen. Dat duuert e bessje.",
    376: "Et Ussauge es fäädich. Maach et Weschbrett extra sauber un setz dat widder en.",
    396: "Ich maache et Wassermodul leddich. Dat duuert e bessje.",
    397: "Et Wasser es bove un unge erus.",
    398: "De Kaat es fäädich. Kuck se der en der App aan un stell mich zoröck.",
    399: "Der Test es fäädich. Stell mich zoröck op de Station.",
    400: "De Selbstreinigung es fäädich. Stell mich jetz op et richtije Stockwerk.",
    401: "Stell mich op de Station, dann fange ich met der Selbstreinigung aan.",
    478: "Wann ich jewäsche han, maache ich met dem Sauge wigger.",
    479: "Allet klor, fang ding Arbeit neu aan.",
    480: "Füll jenog Wasser en, dat et för et Nächste rääch.",
    481: "Ich maache der Handstaubsauger leddich.",
    482: "Ich maache der Handstaubsauger leddich. Mich selver sauge ich dann us.",
    483: "Ich maache der Handstaubsauger leddich. Et Weschduch wesche ich dann.",
    484: "Ich maache der Handstaubsauger leddich. Jesaug weed dann.",
    485: "Ich sauge mich jrad us. Der Handstaubsauger kütt dann.",
    486: "Ich wesche jrad et Weschduch. Der Handstaubsauger kütt dann.",
    487: "Kuck, dat ich en der Station stonn.",
    638: "Ich sauge mich wigger us.",
    661: "Ich maache et Weschbrett sauber. Dat duuert en knappe Menutt.",
    662: "Ich maache elektrolysiert Wasser zum Botze.",

    # --- Sprachassistent -------------------------------------------------
    194: "Ich ben ald am Sauge.",
    195: "Allet klor, ich maache et Zimmer sauber. Kuck, dat de Dör op es.",
    196: "Allet klor, ich sauge der Bodde. Kuck, dat de Dör op es.",
    197: "Allet klor, ich wesche der Bodde. Kuck, dat de Dör op es.",
    198: "Allet klor, ich sauge un wesche. Kuck, dat de Dör op es.",
    199: "Dat Zimmer kenne ich nit. Kuck en der App, wie et heiss.",
    200: "Maach et joot.",
    201: "Allet klor, ich maache wigger.",
    202: "Allet klor, ich hür op un fahre zum Lade.",
    203: "Allet klor, ich fahre zum Lade.",
    204: "Allet klor, ich fange met dem Mole aan. Maach bitte all Döre op.",
    205: "Allet klor, ich fahre vun der Station erav.",
    206: "Allet klor, ich kucke, wo de bes.",
    207: "Ich finge dich nit. Stell dich en ming Sichtwiggde.",
    208: "Do bes de jo. Ich kumme sauge.",
    217: "Mih Saugkraff jeht nit.",
    218: "Winnijer Saugkraff jeht nit.",
    219: "Mih Wasser jeht nit.",
    220: "Winnijer Wasser jeht nit.",
    222: "Saugstuf leis.",
    223: "Saugstuf normal.",
    224: "Saugstuf staak.",
    225: "Saugstuf Turbo.",
    226: "Et Weschduch es leich fücht.",
    227: "Et Weschduch es fücht.",
    228: "Et Weschduch es nass.",
    229: "Hück es",
    230: "Hück es der einunzwanzigste Februar zweidausendzweiunzwanzig.",
    231: "Hück es Mondaach.",
    232: "Hück es Dinsdaach.",
    233: "Hück es Metwoch.",
    234: "Hück es Dunnersdaach.",
    235: "Hück es Fridaach.",
    236: "Hück es Samsdaach.",
    237: "Hück es Sonndaach.",
    238: "Allet klor, ich hür op.",
    248: "Et Weschduch fählt. Maach dat draan un probeer noch ens.",
    249: "Ich arbeide jrad. Maach dat ehsch fäädich, dann jeht et.",
    250: "Ich ben jrad em Weschmodus. Stell bitte öm.",
    251: "Ich ben jrad em Saugmodus. Stell bitte öm.",
    252: "Fäädich. Ich ben us der enjestellte Reinigung erus.",
    253: "Luuter jeht nit.",
    254: "Leiser jeht nit.",
    255: "Dat jeht bloss met aanjeschalter Hindernisumfahrung.",
    258: "Ich fange aan eröm ze fahre.",
    259: "Ich fahre zo dä Stell hen.",
    260: "Ich fahre wigger eröm.",
    261: "Ich fahre wigger zo dä Stell.",
    262: "Ich weiss nit, wo ich ben.",
    266: "Tuusch bitte et Reinigungsmittel us.",
    269: "Probeer noch ens, wann ich fäädich ben.",
    275: "Dat kenne ich nit. En der App ston all Sprochbefähle.",
    276: "Dat maache ich jrad nit.",
    277: "Allet klor, ich kumme un maache do sauber.",
    279: "Ich sauge jrad. Maach dat ehsch fäädich un probeer noch ens.",
    281: "Ich sauge mich jrad us. Probeer jlich noch ens.",
    282: "Ich wesche jrad ming Weschduch. Probeer jlich noch ens.",
    283: "Ich stonn nit en der Station. Probeer spääder noch ens.",
    284: "Allet klor, ich hür op un kumme sauge.",
    285: "Blief kurz stonn, ich kucke wo de bes.",
    286: "Do bruch ich ehsch en Kaat.",
    287: "Allet klor, jetz es leis.",
    288: "Allet klor, jetz es normal.",
    289: "Allet klor, jetz es staak.",
    290: "Allet klor, jetz es Turbo.",
    291: "Allet klor, jetz es leich fücht.",
    292: "Allet klor, jetz es nass.",
    293: "Aanrofe sin aan.",
    294: "Aanrofe sin us.",
    305: "Allet klor, ich maache et Weschbrett sauber. Maach dat benne met ener Bösch sauber.",
    308: "Dat han ich nit metkräje. Weck mich noch ens.",
    309: "Do bes de jo, ich kumme.",
    310: "Allet klor, ich fahre jlich do fott.",
    311: "De Weschdöcher sin erav.",
    314: "Dat jeht nit. Do kanns mer saare, ich soll mich ömdreihe.",
    317: "Dat jeht jrad nit, ich maache en enjestellte Reinigung.",
    322: "Dat kenne ich nit. En der App ston all Sprochbefähle.",
    323: "Dat kenne ich nit. Frooch mich ens, wat ich all kann.",
    324: "Ich wesche mich jrad. Weck mich, wann ich fäädich ben.",
    328: "Dat kanns de mer bloss saare, wann ich jrad sauge.",
    338: "Der Videoaanroof steiht.",
    340: "Kein Antwoot.",
    341: "Do bes de jo. Ich jonn der noh. Saach Engk, wann et rääch.",
    342: "Wo bes de? Stell dich onjefähr anderthalv Meter vör mich.",
    343: "Ich han dich verlore. Do bes ze flöck. Stell dich anderthalv Meter vör mich.",
    364: "Ich reeche der Videocode en.",
    365: "Et Livebild es us.",
    489: "Ich ben em Clean-Genius-Modus. Saach mer, ich soll ophüre.",
    490: "Allet klor, enjestellte Reinigung: ich wesche.",
    491: "Allet klor, enjestellte Reinigung: ich sauge.",
    511: "Ich maache jrad nix.",
    512: "En der Kaat es noch kei Deermöbel. Draach dat en der App en.",
    513: "Allet klor, ich maache öm et Deermöbel eröm sauber.",
    516: "Ich kucke, wo ding Deerche steck.",
    517: "Ich han et jefunge. Ich fahre zum Lade.",
    518: "Ich han keins jefunge. Ich fahre zum Lade.",
    522: "Wat es dann scheefjejange?",
    523: "Kanns de mer dat e bessje jenauer saare?",
    524: "Nemm mich dohen, wo et passeet es.",
    525: "Waat kurz, ich kucke mer dat aan.",
    641: "Saach mer einfach, ich soll met dem Sauge aanfange.",
    642: "Saach mer einfach, ich soll stärker sauge.",
    643: "Saach mer einfach, ich soll mih Wasser nemme.",
    644: "Saach mer einfach, ich soll sauge un wesche.",
    645: "Saach mer einfach, ich soll wesche.",
    646: "Saach mer einfach, ich soll dohen kumme un sauber maache.",
    647: "Saach mer einfach, ich soll ehsch sauge un dann wesche.",
    648: "Saach mer einfach, ich soll allet sauber maache.",
    659: "Dat han ich nit verstande. Frooch mich ens, wat ich all kann.",
    694: "Saach mer einfach, ich soll met dem Sauge aanfange.",

    # --- Erste Einrichtung ------------------------------------------------
    463: "Alaaf, schön dat de do bes. Maach der Deckel op un scann der QR-Code.",
    464: "Domet spääder allet flupp, stell mich vör dem Start op de Station.",
    465: "Stell mich vör dem Start op de Station. Wann de Ich lade jrad op hührs, es et joot.",
    466: "Maach bitte de Döre op un rüm der Bodde frei.",
    467: "Stell mich op de Station un fang et Mole neu aan.",
    468: "Kuck der de Kaat bitte en der App aan.",
    630: "Alaaf, schön dat de do bes. Maach der Deckel op un scann der QR-Code.",
})

# --------------------------------------------------------------------------
# Die letzten Ansagen des r2532v (X50 Ultra Complete). Ihr Wortlaut steht in
# keiner Textdatei des Pakets - er wurde aus den deutschen Originalaufnahmen
# transkribiert (Windows-Spracherkennung) und anschliessend von Hand
# geglättet. Sinngemäß richtig, im Wortlaut sinnvoll gekürzt.
# --------------------------------------------------------------------------

TEXTE.update({
    24: 'Kuck ens, ov der Wassertank richtich dren steck.',
    101: 'De Klapp vun der Avsaugstation es op odder der Beutel fählt. Maach de Klapp zo odder lääch ene Beutel en.',
    104: 'Et Weschbrett es nit dren. Setz et en un maach de Klammere op beide Sigge fess.',
    170: 'De Tastesperr es aan. Halt de Taste aan der Station jedröck, dann jeht se widder op.',
    339: 'Aanroof avjelehnt.',
    353: 'Der Schmotzwasserbehälter es dren.',
    354: 'Der Schmotzwasserbehälter es erus.',
    358: 'Setz bitte der Schmotzwasserbehälter en.',
    386: 'Ming Schmotzwasserbehälter es voll. Ich fahre zoröck un maache dä leddich.',
    387: 'Et Leddichmaache es fäädich. Ich maache wigger.',
    393: 'Ming Schmotzwasserbehälter es dreckich. Maach dä jlich sauber.',
    394: 'Der Wassersensor deit et nit mih.',
    631: 'Schön, dat de dich för der Dreame entschiede häs. Maach de Klapp op un scann der QR-Code, dann kanns de de App lade.',
    634: 'Ich fange aan, de Hoore ze entwirre.',
    660: 'Tschuldijung, dat han ich nit verstande. Saach Hey Rover, wat kanns du, dann saare ich der, wat ich all kann.',
    664: 'Saach zo mer: Hey Rover, fang aan ze reinije.',
    665: 'Wann allet paff, saach zo mer: Hey Rover, fang aan ze reinije.',
    666: 'Saach zo mer: Hey Rover, maach de Saugkraff stärker.',
    667: 'Saach zo mer: Hey Rover, jib mih Wasser.',
    668: 'Saach zo mer: Hey Rover, fang aan ze sauge. Spääder saachs de wesche, dann wechsele ich der Modus.',
    669: 'Saach zo mer: Hey Rover, fang aan ze wesche. Spääder kanns de der Modus wechsele.',
    670: 'Saach zo mer: Hey Rover, kumm her un maach do sauber.',
    671: 'Saach zo mer: Hey Rover, fang aan ze sauge. Spääder kanns de der Modus wechsele.',
    672: 'Saach zo mer: Hey Rover, fang aan ze reinije. Spääder kanns de de janze Wohnung maache lasse.',
    674: 'Ming Mopp klemmp villeich odder hät sich jet ennjewickelt. Kuck noh un maach dä sauber.',
    682: 'Ming Mopp dreiht sich nit mih.',
    683: 'Der Mopp es nit draan. Maach ehsch der Mopp draan un probeer dann noch ens.',
    689: 'Ich fange aan, Staubbehälter un Beutel ze drüjje.',
    690: 'Et Drüjje vun Staubbehälter un Beutel es jestopp.',
    691: 'Der Mopp weed jrad jewäsche. Probeer spääder noch ens.',
    692: 'Ich fahre zum Lade. En extra Reinijung jeht jrad nit.',
    696: 'Fähler aan der Klapp.',
    697: 'Ich ben jesperrt. Maach ehsch de Kindersicherung us.',
    698: 'Et Kaatemole es fäädich. Ich finge de Station nit un fange alleen aan ze reinije.',
    699: 'Sensorfähler. Kuck noh, ov der Kamerasensor dreckich es.',
    701: 'De Platt es heiss. Bitte nit aanfasse.',
    702: 'Met ener vörläufije Kaat kann ich nit reinije. Dröck noch ens op Reinijung, dann weed de Kaat jespeichert.',
    703: 'Ich fange met der Staub- un Moppdrüjjung aan.',
    704: 'De Moppdrüjjung es pausseet.',
    706: 'Fähler aam Kreisel. Bitte de Opjab noch ens starte.',
    707: 'Fähler aam Fahrjestell. Bitte de Opjab noch ens starte.',
    708: 'Der Wääch zor Ladestation es zo. Kuck noh, ov jet em Wääch steiht.',
    711: 'De Desinfektion fängk aan.',
    712: 'Et Weschbrett es heiss. Bitte nit aanfasse.',
    715: 'En der Station fählt der Mopp. Setz dä en, dann maache ich wigger.',
    716: 'En der Station fählt der Mopp. Setz dä en - solang arbeide ich em Standardmodus.',
    717: 'Der Mopp setz nit richtich. Röck dä zorääch, dann maache ich wigger.',
    718: 'Dat löss sich em Energiesparmodus nit ändere. Maach der Energiesparmodus us un probeer noch ens.',
    719: 'Fähler beim Moppwechsel.',
    722: 'Der Mopp kütt en heiss Wasser, domet hä warm weed. Dröm duuert et e bessje länger. Hab e bessje Jeduld.',
    723: 'Beim Kaatemole kuck, dat allet joot beleuch es. Stell nix en de Döre un scheev weder mich noch de Station eröm.',
    724: 'Der Mopp litt en der Station nit richtich. Röck dä jlich zorääch.',
    725: 'Fähler aan der Moppavdeckung.',
    726: 'Fähler aam Rollmopp.',
    728: 'Ich fange met der Boddepflääch aan.',
    729: 'Der Mopp weed jrad jewechselt. Probeer spääder noch ens.',
    731: 'Ming Schmotzwassertank es voll. Stell mich zoröck op de Station, domet ich der Mopp wesche kann.',
    752: 'Ich maache met der Boddepflääch wigger.',
    754: 'Ich han mich jefunge. Ich maache met der Boddepflääch wigger.',
    755: 'Der Lasersensor deit et nit. Kuck noh, ov do jet dreckich es odder klemmp.',
    757: 'Ming Schmotzwassertank es voll. Maach dä jlich leddich.',
    758: 'Ze winnich Wasser. Stell mich zoröck op de Station un dröck op Start, dann weed nohjefüllt.',
    765: 'Der Mopp weed jrad jewechselt. Probeer spääder noch ens.',
    771: 'Der Rollmopp bliev stonn odder es blockeet.',
    775: 'Solang der Mopp läuf, looss de Klapp zo.',
    777: 'De Zick es eröm. Kuck noh, ov unger dem Jerät jet em Wääch es.',
    778: 'Oppjepass, pass op ding Finger op.',
    779: 'De Zick förs Mopperusnemme es eröm. Ich hür op.',
    780: 'Et Opnemme odder Avlääje vum Mopp hät nit jeklapp. Nemm der Mopp us der Halterung un lääch dä widder ens Fach aan der Klapp.',
    782: 'Fähler beim Oplockere vun der Roll. Maach se sauber, dann jeht et wigger.',
    784: 'Wann Schrett ein fäädich es, fahre ich vun alleen us der Station.',
    785: 'Maach de Weschbrett-Basis bitte met ener Bösch odder enem Duch sauber. Danoh tipps de en der App op Reinijung beende.',
    786: 'De Weschbrett-Basis es sauber.',
    787: 'Ich fahre vun alleen zor Station zoröck un maache der Mopp sauber un drüjj.',
    795: 'Ich fange met der Reinijung vun der Weschbrett-Basis aan. Dat duuert onjefähr zwei Menutte.',
    797: 'Do stemmp villeich jet nit met dem Jerät. Roof beim Kundendienst aan.',
    798: 'De Selbstreinijung vun der Station duuert onjefähr veer Menutte. Scheev mich solang nit eröm.',
    799: 'De Zick es eröm. Kuck noh, ov e Deer odder e Hindernis unger dem Jerät steiht.',
    805: 'Ich fange aan, der jrove Dreck opzesauge.',
    812: 'Stell mich bitte zum Lade en de Station.',
    813: 'Ich fange met der kräftije Avsaugung vum Dreck aan.',
    814: 'Ich fange met der Selbstreinijung vun der Station un der kräftije Avsaugung aan.',
    823: 'Der Wasserstand em Weschbrett paff nit. Maach et sauber, ih dat et losjeht.',
    824: 'Der Rollmopp bliev stonn odder es blockeet.',
    828: 'Der Filter es durch. Maach dä bald sauber.',
    849: 'Ich fange aan, Staubbehälter un Beutel ze drüjje.',
    850: 'Et Drüjje vun Staubbehälter un Beutel es jestopp.',
    857: 'Setz bitte et Weschbrett en.',
    910: 'Alaaf un willkomme en der Usstellung för Saugroboter.',
    915: 'Der Wasserstand em Weschbrett paff nit. Maach der Filter sauber, dann verstopp nix.',
})
