"""Sächsisch - Leipzig/Dresden."""

from __future__ import annotations

from . import muster
from ..i18n import t

KEY = "saechsisch"
NAME = t("saechsisch.name")
BESCHREIBUNG = t("saechsisch.beschreibung")
LANG_ID = "SACHSE"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "Isch warde uffs Netzwerg.",
    2: "Mitm WLAN hads nisch geglabbt. Guggemal nachm Passwort.",
    3: "Isch gomm nisch uffn Server. Guggemal dei Netzwerg an.",
    5: "Netzwerg basst, isch bin drinne.",
    6: "Mitm Netzwerg hads nisch geglabbt. Probier's schbäder nochemal.",

    # --- Reinigung ---------------------------------------------------
    7: "Nu, dann gehds los. Isch fange an zu saugen.",
    8: "Isch mache den een Fleck sauber.",
    9: "De geblante Reinigung gehd jetzt los.",
    10: "Isch mache weider, wo isch uffgehörd habe.",
    12: "Fertsch. Alles sauber.",
    56: "Isch mache das Zimmer sauber.",
    57: "Isch mache de Zone sauber.",
    58: "Isch mache meine Arbeed weider.",
    61: "Isch fange an zu wischen.",
    62: "Du steuerst misch jetzt selber.",
    82: "Isch zeischne jetzt ne Garde von der Wohnung.",
    84: "De Garde is fertsch.",
    105: "Uff gehds, isch fange an.",
    126: "Isch fange an zu saugen.",
    137: "Isch sauge weider.",
    138: "Isch wische weider.",
    139: "Isch gomme zurügge.",
    143: "Fertsch. Da siehds jetzt sauber aus.",
    144: "Gewischd habsch och schon.",
    164: "So, das wars. Feierahmd.",
    433: "Isch mache noch ne Extrarunde.",
    434: "De Extrarunde is fertsch, isch mache normal weider.",

    # --- Akku und Laden ----------------------------------------------
    13: "Isch fahre heeme zum Uffladen.",
    14: "Meine Batterie is bald leer. Isch fahre heeme zum Laden und mache dann weider.",
    17: "Stelle misch bitte wieder uff de Station.",
    18: "Isch lade grade uff.",
    20: "Meine Batterie is bald leer.",
    21: "Batterie leer. Isch schalde misch jetzt aus.",
    47: "Isch fange an zu laden.",
    48: "Batterie is schwach, isch fahre zur Station.",
    50: "Mitm Laden stimmd was nisch. Mach mer de Gondagde sauber.",
    301: "Isch lade grade uff.",
    302: "Isch bin grade am Arbeeden.",

    # --- Station und Wischen -----------------------------------------
    106: "Isch wasche mein Wischduch.",
    107: "Isch drockne meine Wischdücher.",
    110: "Isch sauge meinen Staub raus.",
    111: "Mir fehlen de Wischdücher. Mach se mer bitte dran.",
    112: "Stelle misch erschtmal in de Station.",
    113: "Fertsch. Mach bitte den Schmutzwassertank leer.",
    114: "De Wischdücher sinn dran.",
    115: "De Wischdücher sinn runder.",
    148: "Isch fahre zur Station und mache misch selber sauber.",
    169: "De Wischdücher sinn drogge.",
    177: "Isch fahre los.",
    179: "Wischduch is sauber. Aber das Frischwasser gehd mer aus.",
    181: "Mir gehd das Wasser aus. Fülle mer bitte nach.",
    186: "Guggemal nachm Frischwassertank.",
    187: "Das dauerd so fümf bis zehn Minudn.",
    318: "Mein Wischduch is wieder sauber.",
    636: "Mein Wischduch is arg drecksch. Isch muss zur Station.",

    # --- Fehler und Wartung ------------------------------------------
    35: "Mit der Hauptbürsde stimmd was nisch. Mach se mer sauber.",
    36: "Mit der Seidnbürsde stimmd was nisch. Mach se mer sauber.",
    37: "Mitm rechden Rad stimmd was nisch.",
    38: "Mitm ligen Rad stimmd was nisch.",
    40: "Ach du meine Gide, isch hänge fest. Machsd misch bitte frei?",
    42: "Guggemal nach meim Filder.",
    43: "Mit meim Stoßbüchel stimmd was nisch. Drügge mal sachte drauf.",
    44: "Da stimmd was nisch. Gugg bitte in de Anleidung.",
    52: "Isch stehe schief. Stelle misch bitte grade hin.",
    66: "Mein Filder is hinnüber. Dausche'n bitte aus.",
    67: "De Seidnbürsde is hinnüber. Dausche se bitte aus.",
    68: "De Hauptbürsde is hinnüber. Dausche se bitte aus.",
    91: "Der Frischwassertank fehld. Setze'n bitte rein.",
    93: "Zu wenisch Wasser drinne. Fülle bitte nach.",
    97: "Da fehld der Staubbeidel.",
    102: "Der Staubbeidel is voll oder der Ganal is verstopfd.",
    156: "Mein Wischduch is nisch dran.",
    166: "Da had sisch was in mein Wischduch gewiggeld. Mach's bitte weg.",
    267: "Meine Sensoren sinn drecksch. Mach se mer bitte sauber.",
    331: "Alles in Ordnung. Isch habe nischts gefunden.",
    332: "Isch habe een Fehler gefunden. Gugg mal in de App.",
    426: "Isch bin abgeruschd und hänge fesd. Isch brobier's weider.",
    437: "Basst wieder. Drügge uff Start, dann gehds weider.",
    441: "Da had sisch was um de Hauptbürsde gewiggeld. Mach's bitte sauber.",
    442: "Da had sisch was um de Seidnbürsde gewiggeld.",
    443: "Um meine Räder had sisch was gewiggeld.",
    444: "Stelle misch bitte uff ne freie Fläsche, dann fange isch an.",
    445: "Mein Wischduch is mer runder. Guggemal in der Nähe.",
    446: "Am Wischduchhalder hängd was dran.",
    447: "De Station had geen Strom. Gugg bitte mal nach.",
    448: "Der Schmutzwassertank fehld. Setze'n bitte rein.",
    449: "Uffm Debbisch fange isch nisch an. Stelle misch uffn Hartboden.",
    454: "Zu wenisch Wasser im Tank. Fülle mer bitte nach.",
    455: "Der Frischwassertank sitzd nisch richtsch drinne.",
    456: "Der Schmutzwassertank is voll oder er fehld.",
    458: "Der Staubbeidel sitzd nisch richtsch.",
    460: "Der Geruchsfilder is uffgebraucht. Dausche'n bitte aus.",
    639: "Da fehld der Filder vom Waschbredd.",
    658: "Der Galgschutz is uffgebraucht. Dausche'n bitte aus.",

    # --- Wegfindung ---------------------------------------------------
    30: "Isch gugge grade, wo isch bin.",
    31: "Isch weeß nisch, wo isch bin. Isch fange eemfach neu an.",
    45: "Isch bin hier!",
    149: "Da gomme isch nisch hin. Räume bitte weg, was im Wege stehd.",
    151: "Mein Weg is verstelld. Räume bitte was weg.",
    153: "Isch stehe in ner Sperrzone. Nimm misch da bitte raus.",

    # --- Bedienung -----------------------------------------------------
    26: "Isch setze misch zurügge uff de Werkseinstellung.",
    27: "Isch mache ee Update. Dauerd fümf Minudn. Bitte nisch ausschalden.",
    28: "Das Update had geglabbt.",
    29: "Das Update had nisch geglabbt. Probier's schbäder nochemal.",
    116: "De Kindersischerung is an. De Gnöbbe sinn gesperrd.",
    117: "De Kindersischerung is aus.",
    162: "De Gamera is an.",
    329: "Isch tesde misch grade selber. Nimm misch nisch von der Station runder.",
    421: "Nu, ab jetzt schnagge isch Sächssch mit dir.",
    632: "Der Sprachwechsel dauerd ne halbe Minude.",
    633: "Der Sprachwechsel had nisch geglabbt.",

    # --- Sprachassistent ------------------------------------------------
    190: "Nu gud, isch fange an zu saugen.",
    191: "Nu gud, isch sauge und wische.",
    192: "Nu gud, isch wische.",
    193: "Nu gud, isch sauge.",
    221: "Nu freilisch.",
    246: "Isch bin hier hinden!",
    247: "Das habsch jetzt nisch verstanden.",
    508: "Isch schnagge lauder.",
    509: "Isch schnagge leiser.",
    510: "Gud, isch höre uff für heide.",
    515: "Sei so gud und hebe mal de Füße.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Aggu is bei {p} Brozent.'
RAUM_MUSTER = 'Nu gud, isch mache {raum} sauber.'
RAUM_NAMEN = {
    'wohnzimmer': 'das Wohnzimmer',
    'schlafzimmer': 'das Schlafzimmer',
    'hauptschlafzimmer': 'das Hauptschlafzimmer',
    'gaestezimmer': 'das Gästezimmer',
    'arbeitszimmer': 'das Arbeedszimmer',
    'kueche': 'de Gische',
    'esszimmer': 'das Esszimmer',
    'bad': 'das Bad',
    'balkon': 'den Balgon',
    'flur': 'den Flur',
    'hauswirtschaftsraum': 'de Waschgische',
    'abstellraum': 'de Abstellgammer',
    'salon': 'den Salon',
    'buero': 'das Büro',
    'gym': 'den Fitnessraum',
    'freizeitraum': 'den Freizeidraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))

# --------------------------------------------------------------------------
# Vollständige Abdeckung: die restlichen Ansagen des X50 Ultra Complete.
# Nummern ohne Sprachinhalt (Klänge, Tierlaute) bleiben im Original; die
# Nummern-Umsetzung des Modells versorgt 856, 858, 859, 863 und 864.
# --------------------------------------------------------------------------

TEXTE.update({
    # --- Netzwerk -----------------------------------------------------
    4: "Isch bin ausm Netzwerggmodus raus.",
    304: "Das Netzwerg is verbunden.",
    306: "Das hab isch nisch verstanden. Richde erschd das Netzwerg ein.",
    313: "Der Embfang is schlecht. Stelle misch woanders hin.",
    377: "Das Netzwerg lässd sisch nisch einrichden. Frag beim Gundendiensd nach.",
    378: "Das Basswort stimmd nisch. Richde das Netzwerg nochemal ein.",
    379: "Isch finde gee WLAN. Nimm das Zweigommavier-Gigahertz-Netz.",
    380: "Isch hab gee IP-Adresse griegd. Guggemal in dein Rouder.",
    381: "Isch gomme nisch uffn Server. Frag beim Gundendiensd nach.",
    382: "Isch gomme nisch ins Netz. Gugg, ob dei Inderned läuft.",
    383: "Das Netzwerg lässd sisch nisch einrichden. Frag beim Gundendiensd nach.",
    385: "Isch verbinde misch grade mitm Netzwerg.",

    # --- Reinigung ----------------------------------------------------
    11: "Isch mache ne Bause.",
    54: "Basst, isch sauge weider.",
    55: "Basst, isch fahre weider zur Station.",
    64: "Hat nisch geglabbt. Isch fahre zur Station.",
    65: "Isch fahre weider zur Station.",
    77: "Stelle misch uff n Hardboden, dann fange isch an.",
    83: "Isch zeischne weider an der Garde.",
    85: "Basst, isch zeischne weider.",
    86: "Hat nisch geglabbt. Isch fange mitm Zeischnen neu an.",
    127: "Isch mache den Fleck sauber.",
    128: "Isch wische den Fleck.",
    129: "De geblante Reinigung gehd los.",
    130: "De geblante Gardierung gehd los.",
    133: "Isch mache de ausgesuchden Zimmer sauber.",
    134: "Isch wische de ausgesuchden Zimmer.",
    135: "Isch mache de Zone sauber.",
    136: "Isch wische de Zone.",
    145: "Basst, isch sauge weider.",
    146: "Basst, isch zeischne weider.",
    150: "Da gomme isch nisch hin. Nimm bitte de Sberrzonen weg.",
    152: "Mein Weg is verstelld. Nimm de Sberrzonen weg oder stelle misch woanders hin.",
    163: "Isch gugge grade mit der Gamera.",
    171: "De schlaue Hindernisumfahrung is an.",
    172: "De schlaue Hindernisumfahrung is aus.",
    257: "De Gameraüberwachung is aus.",
    280: "Isch fange mit der eingestellden Reinigung an.",
    321: "Isch fange mitm gründlischen Fleckenwischen an.",
    344: "Nu gud, isch sauge erschd und wische danach.",
    362: "Das Wischduch sitzd nisch richdsch. Isch sauge stattdessen bloß.",
    363: "Das Saugen is fertsch, jetzt wische isch.",
    366: "Da is een Fleck, isch mache den sauber.",
    367: "Nu gud, isch mache den Fleck sauber.",
    368: "Da is een Fleck. Isch mache den sauber, wenn isch gewaschen habe.",
    369: "Nu gud, isch mache da sauber.",
    424: "Isch weeß nisch, wo isch bin. Stelle misch uff ne freie Fläsche und fange neu an.",
    435: "Isch fahre aus dem Bereisch raus.",
    450: "In ner Sberrzone fange isch nisch an. Stelle misch woanders hin.",
    451: "Im versteckden Bereisch fange isch nisch an. Stelle misch woanders hin.",
    677: "Da gomme isch nisch hin. Nimm de Sberrzonen oder de Schwellen weg.",
    678: "Mein Weg is verstelld. Nimm de Sberrzonen oder de Schwellen weg.",
    679: "Isch stehe in ner Sberrzone. Nimm misch da bitte raus.",
    680: "Isch zeischne erschd ne Garde, dann mache isch sauber.",
    681: "Nu gud, isch mache weider.",

    # --- Akku und Laden ------------------------------------------------
    19: "Nimm misch von der Station runder, bevor de misch ausmachsd.",
    25: "Der Aggu is zu schwach für de geblante Reinigung.",
    87: "Batterie schwach, isch fahre zur Station.",
    303: "Isch ruhe misch grade aus.",
    307: "Isch lade grade uff.",

    # --- Fehler und Wartung --------------------------------------------
    34: "Da fehld ee Deil. Setze das bitte rein.",
    39: "Meine Räder hängen in der Luft. Mach de Absturzsensoren sauber.",
    41: "Meine Räder hängen in der Luft. Stelle misch woanders hin.",
    71: "Guggemal, ob am Laser-Abstandssensor was glemmd.",
    72: "De Abdeggung vom Lasersensor glemmd.",
    73: "Mitm Gandensensor stimmd was nisch.",
    75: "Der Filder is feucht oder verstopfd.",
    81: "Mitm Debbischsensor stimmd was nisch.",
    108: "Mitm Wasserstand vom Waschbredd stimmd was nisch. Mach das sauber.",
    109: "Mitm Schmutzwassertank stimmd was nisch. Gugg, ob er drinne und leer is.",
    118: "De Gnöbbe sinn gesberrd. Halde de Tasde an der Station gedrüggd.",
    142: "Das Wischduch is hinnüber. Dausche das bitte aus.",
    173: "Dausche bitte das Silberionen-Modul aus.",
    244: "De Reinigungsmittelflasche is dran.",
    245: "Mehr Garden gehen nisch. Lösche bitte eene in der App.",
    296: "Guggemal, ob der Schmutzwassertank voll is.",
    297: "De Reinigungsmittelflasche is dran. Wenn de se noch nie benutzd hast, gugg in de App.",
    298: "Isch mache das Waschbredd sauber.",
    299: "De Reinigungsmittelflasche und das Nachfüllmodul sinn dran.",
    300: "Das Zubehör genne isch nisch.",
    312: "Über das Zubehör weeß isch nischts. Dausche das aus, wenn es hinnüber is.",
    315: "Das Wischduch is nisch in der Station. Lege das rein und brobier nochemal.",
    316: "In der Station liegd schon ee Wischduch.",
    319: "Das Wischduch is nisch runder. Nimm das von Hand ab.",
    320: "Das Wischduch is nisch drangegangen. Mach das von Hand dran.",
    330: "Warde, bis der Selbsttest fertsch is.",
    355: "Zu wenisch Wasser. Fülle den Frischwassertank nach.",
    356: "Der Fehler is noch da. De geblante Reinigung is abgesagd.",
    384: "Im automatischen Wassermodul is gee Wasser.",
    388: "Da darf isch nisch hin. Stelle misch woanders hin.",
    389: "Der Laser fährd nisch runder. Gugg, ob was glemmd.",
    390: "Der Laser fährd nisch ruff. Gugg, ob was glemmd.",
    391: "Stelle misch uff ne freie Fläsche, bevor es losgehd.",
    392: "Im Clean-Genius-Modus lässd sisch das nisch einstellen.",
    438: "Der Stoßbüchel glemmd. Drügge mal sachte drauf.",
    439: "De Laserabdeggung glemmd. Drügge mal sachte drauf.",
    440: "Ee Rad hängd in der Luft. Stelle misch uff ne freie Fläsche.",
    452: "Mitm Debbischsensor stimmd was nisch. Drehe misch um und butz das weiße Loch.",
    453: "Mitm Gandensensor stimmd was nisch. Butz misch rechds ab.",
    457: "Der Schmutzwassertank is voll oder nisch drinne. Guggemal nach.",
    459: "Der Wischduchhalder sitzd nisch richdsch. Guggemal nach.",
    663: "Mitm Wasserstand im Waschbredd stimmd was nisch. Butz das.",
    673: "Um meine Beinchen had sisch vielleicht was gewiggeld. Butz das vorm Start.",

    # --- Basisstation ---------------------------------------------------
    46: "Roboder und Handy sinn verbunden.",
    59: "De Garde is fertsch. Nimm den Wassertank raus.",
    140: "Ne neue Umgebung. Isch fahre zur Station.",
    188: "Isch dogge automatisch an.",
    209: "Nu gud, isch fahre zur Station und wasche mein Wischduch.",
    210: "Isch wasche de Wischdücher.",
    211: "Aussaugen gehd bloß, wenn isch in der Station stehe.",
    212: "Nu gud, isch sauge misch aus.",
    213: "Droggnen gehd bloß, wenn isch in der Station stehe.",
    214: "Isch droggne grade.",
    215: "Nu gud, isch fange mitm Droggnen an.",
    216: "Da muss erschd das Wischduch dran.",
    278: "Nu gud, das Droggnen is fertsch.",
    349: "Gugg, dass de Station Strom had, und stelle misch drauf.",
    350: "Isch fange mitm Einrichden von der Station an.",
    351: "De Station is eingerichded.",
    352: "Das Einrichden had nisch geglabbt. Gugg in de App.",
    360: "Isch lasse das Wasser ausm Tank.",
    361: "Das Wasser is draußen.",
    371: "Nimm bitte das Waschbredd raus.",
    372: "Das Frischwasser läufd rein.",
    373: "Das Wasser is drinne. Warde zehn Segunden, dann gehds weider.",
    374: "Butz den Boden von der Station mit ner Bürsde oder eem Duch.",
    375: "Schieb den Dregg zum Aussaugen hin. Das dauerd ee bissl.",
    376: "Das Aussaugen is fertsch. Butz das Waschbredd extra und setze das wieder rein.",
    396: "Isch mache das Wassermodul leer. Das dauerd ee bissl.",
    397: "Das Wasser is oben und unden draußen.",
    398: "De Garde is fertsch. Gugg se dir in der App an und stelle misch zurügge.",
    399: "Der Test is fertsch. Stelle misch zurügge uff de Station.",
    400: "De Selbstreinigung is fertsch. Stelle misch jetzt uff das richdsche Stoggwerk.",
    401: "Stelle misch uff de Station, dann fange isch mit der Selbstreinigung an.",
    478: "Wenn isch gewaschen habe, mache isch mitm Saugen weider.",
    479: "Nu gud, fange deine Arbeed neu an.",
    480: "Fülle genug Wasser rein, dass es fürs Nächsde reichd.",
    481: "Isch mache den Handstaubsauger leer.",
    482: "Isch mache den Handstaubsauger leer. Misch selber sauge isch danach aus.",
    483: "Isch mache den Handstaubsauger leer. Das Wischduch wasche isch danach.",
    484: "Isch mache den Handstaubsauger leer. Gesaugd wird danach.",
    485: "Isch sauge misch grade aus. Der Handstaubsauger gommd danach.",
    486: "Isch wasche grade das Wischduch. Der Handstaubsauger gommd danach.",
    487: "Gugg, dass isch in der Station stehe.",
    638: "Isch sauge misch weider aus.",
    661: "Isch mache das Waschbredd sauber. Das dauerd ne gnabbe Minude.",
    662: "Isch mache eleggdrolysiertes Wasser zum Butzen.",

    # --- Sprachassistent -------------------------------------------------
    194: "Isch bin schon am Saugen.",
    195: "Nu gud, isch mache das Zimmer sauber. Gugg, dass de Dür uff is.",
    196: "Nu gud, isch sauge den Boden. Gugg, dass de Dür uff is.",
    197: "Nu gud, isch wische den Boden. Gugg, dass de Dür uff is.",
    198: "Nu gud, isch sauge und wische. Gugg, dass de Dür uff is.",
    199: "Das Zimmer genne isch nisch. Gugg in de App, wie es heeßd.",
    200: "Machs gud.",
    201: "Nu gud, isch mache weider.",
    202: "Nu gud, isch höre uff und fahre zum Laden.",
    203: "Nu gud, isch fahre zum Laden.",
    204: "Nu gud, isch fange mitm Zeischnen an. Mach bitte alle Düren uff.",
    205: "Nu gud, isch fahre von der Station runder.",
    206: "Nu gud, isch gugge, wo de bisd.",
    207: "Isch finde disch nisch. Stelle disch in meine Sichtweide.",
    208: "Da bisd de ja. Isch gomme saugen.",
    217: "Mehr Sauggraft gehd nisch.",
    218: "Weniger Sauggraft gehd nisch.",
    219: "Mehr Wasser gehd nisch.",
    220: "Weniger Wasser gehd nisch.",
    222: "Saugstufe leise.",
    223: "Saugstufe normal.",
    224: "Saugstufe stark.",
    225: "Saugstufe Durbo.",
    226: "Das Wischduch is leicht feucht.",
    227: "Das Wischduch is feucht.",
    228: "Das Wischduch is nass.",
    229: "Heude is",
    230: "Heude is der eenunzwanzigsde Februar zweedausendzweeunzwanzig.",
    231: "Heude is Mondag.",
    232: "Heude is Diensdag.",
    233: "Heude is Mittwoch.",
    234: "Heude is Donnersdag.",
    235: "Heude is Freidag.",
    236: "Heude is Samsdag.",
    237: "Heude is Sonndag.",
    238: "Nu gud, isch höre uff.",
    248: "Das Wischduch fehld. Mach das dran und brobier nochemal.",
    249: "Isch arbeede grade. Mach das erschd fertsch, dann gehds.",
    250: "Isch bin grade im Wischmodus. Stelle bitte um.",
    251: "Isch bin grade im Saugmodus. Stelle bitte um.",
    252: "Fertsch. Isch bin aus der eingestellden Reinigung raus.",
    253: "Lauder gehd nisch.",
    254: "Leiser gehd nisch.",
    255: "Das gehd bloß mit eingeschalded er Hindernisumfahrung.",
    258: "Isch fange an rumzufahren.",
    259: "Isch fahre zu der Stelle hin.",
    260: "Isch fahre weider rum.",
    261: "Isch fahre weider zu der Stelle.",
    262: "Isch weeß nisch, wo isch bin.",
    266: "Dausche bitte das Reinigungsmittel aus.",
    269: "Brobier nochemal, wenn isch fertsch bin.",
    275: "Das genne isch nisch. In der App stehen alle Sprachbefehle.",
    276: "Das mache isch grade nisch.",
    277: "Nu gud, isch gomme und mache da sauber.",
    279: "Isch sauge grade. Mach das erschd fertsch und brobier nochemal.",
    281: "Isch sauge misch grade aus. Brobier gleisch nochemal.",
    282: "Isch wasche grade mein Wischduch. Brobier gleisch nochemal.",
    283: "Isch stehe nisch in der Station. Brobier schbäder nochemal.",
    284: "Nu gud, isch höre uff und gomme saugen.",
    285: "Bleib gurz stehen, isch gugge wo de bisd.",
    286: "Da brauche isch erschd ne Garde.",
    287: "Nu gud, jetzt is leise.",
    288: "Nu gud, jetzt is normal.",
    289: "Nu gud, jetzt is stark.",
    290: "Nu gud, jetzt is Durbo.",
    291: "Nu gud, jetzt is leicht feucht.",
    292: "Nu gud, jetzt is nass.",
    293: "Anrufe sinn an.",
    294: "Anrufe sinn aus.",
    305: "Nu gud, isch mache das Waschbredd sauber. Butz das innen mit ner Bürsde.",
    308: "Das hab isch nisch mitgegriegd. Wegge misch nochemal.",
    309: "Da bisd de ja, isch gomme.",
    310: "Nu gud, isch fahre gleisch da weg.",
    311: "De Wischdücher sinn runder.",
    314: "Das gehd nisch. De gannsd mir sagen, isch soll misch umdrehen.",
    317: "Das gehd grade nisch, isch mache ne eingestellde Reinigung.",
    322: "Das genne isch nisch. In der App stehen alle Sprachbefehle.",
    323: "Das genne isch nisch. Frag misch mal, was isch alles gann.",
    324: "Isch wasche misch grade. Wegge misch, wenn isch fertsch bin.",
    328: "Das gannsd de mir bloß sagen, wenn isch grade sauge.",
    338: "Der Videoanruf stehd.",
    340: "Geene Antwort.",
    341: "Da bisd de ja. Isch gehe dir nach. Sag Ende, wenn es reichd.",
    342: "Wo bisd de? Stelle disch ungefähr anderthalb Meder vor misch.",
    343: "Isch hab disch verloren. De bisd zu schnell. Stelle disch anderthalb Meder vor misch.",
    364: "Isch richde den Videocode ein.",
    365: "Das Livebild is aus.",
    489: "Isch bin im Clean-Genius-Modus. Sag mir, isch soll uffhören.",
    490: "Nu gud, eingestellde Reinigung: isch wische.",
    491: "Nu gud, eingestellde Reinigung: isch sauge.",
    511: "Isch mache grade nischts.",
    512: "In der Garde is noch gee Diermöbel. Drag das in de App ein.",
    513: "Nu gud, isch mache ums Diermöbel rum sauber.",
    516: "Isch gugge, wo dei Diersch steggd.",
    517: "Isch hab es gefunden. Isch fahre zum Laden.",
    518: "Isch hab geens gefunden. Isch fahre zum Laden.",
    522: "Was is denn schiefgegangen?",
    523: "Gannsd de mir das ee bissl genauer sagen?",
    524: "Nimm misch dahin, wo es bassierd is.",
    525: "Warde gurz, isch gugge mir das an.",
    641: "Sag mir eemfach, isch soll mitm Saugen anfangen.",
    642: "Sag mir eemfach, isch soll stärger saugen.",
    643: "Sag mir eemfach, isch soll mehr Wasser nehmen.",
    644: "Sag mir eemfach, isch soll saugen und wischen.",
    645: "Sag mir eemfach, isch soll wischen.",
    646: "Sag mir eemfach, isch soll dahin gommen und sauber machen.",
    647: "Sag mir eemfach, isch soll erschd saugen und dann wischen.",
    648: "Sag mir eemfach, isch soll alles sauber machen.",
    659: "Das hab isch nisch verstanden. Frag misch mal, was isch alles gann.",
    694: "Sag mir eemfach, isch soll mitm Saugen anfangen.",

    # --- Erste Einrichtung ------------------------------------------------
    463: "Nu, schön dass de da bisd. Mach den Deggel uff und scann den QR-Code.",
    464: "Damit schbäder alles glatt läufd, stelle misch vorm Start uff de Station.",
    465: "Stelle misch vorm Start uff de Station. Wenn de 'Isch lade uff' hörsd, basst es.",
    466: "Mach bitte de Düren uff und räume den Boden frei.",
    467: "Stelle misch uff de Station und fange das Zeischnen neu an.",
    468: "Gugg dir de Garde bitte in der App an.",
    630: "Nu, schön dass de da bisd. Mach den Deggel uff und scann den QR-Code.",
})

# --------------------------------------------------------------------------
# Die letzten Ansagen des r2532v (X50 Ultra Complete). Ihr Wortlaut steht in
# keiner Textdatei des Pakets - er wurde aus den deutschen Originalaufnahmen
# transkribiert (Windows-Spracherkennung) und anschliessend von Hand
# geglättet. Sinngemäß richtig, im Wortlaut sinnvoll gekürzt.
# --------------------------------------------------------------------------

TEXTE.update({
    24: 'Gugge ma, ob der Wassertank richdsch drinne sitzd.',
    101: 'De Glabbe von der Absaugstation is offen oder der Beudel fehlt. Mach de Glabbe zu oder lech en Beudel rein.',
    104: 'Das Waschbrett is nich drin. Setz es rein und mach de Glammern uff beeden Seiden fest.',
    170: 'De Dastensperre is an. Halt de Dasten an der Station gedrückt, dann geht se wieder uff.',
    339: 'Anruf abgelehnt.',
    353: 'Der Schmutzwasserbehälter is drin.',
    354: 'Der Schmutzwasserbehälter is raus.',
    358: 'Setz bidde den Schmutzwasserbehälter rein.',
    386: 'Mei Schmutzwasserbehälter is volle. Isch fahre zurügge und mache en leer.',
    387: 'Das Leermachen is fertsch. Isch mache weider.',
    393: 'Mei Schmutzwasserbehälter is dreggsch. Mach en glei sauber.',
    394: 'Der Wassersensor machds nich mehr.',
    631: 'Schön, dass de disch fürn Dreame entschieden hast. Mach de Glabbe uff und scanne den QR-Code, dann kannsde de App laden.',
    634: 'Isch fange an, de Haare zu entwirren.',
    660: 'Dschuldschung, das hab isch nich verstanden. Sach Hey Rover, was kannst du, dann sach isch dir, was isch alles kann.',
    664: 'Sach zu mir: Hey Rover, fange an zu reinschen.',
    665: 'Wenn alles basst, sach zu mir: Hey Rover, fange an zu reinschen.',
    666: 'Sach zu mir: Hey Rover, mach de Saugkraft stärger.',
    667: 'Sach zu mir: Hey Rover, gib mehr Wasser.',
    668: 'Sach zu mir: Hey Rover, fange an zu saugen. Spääder sachsde wischen, dann wechsle isch den Modus.',
    669: 'Sach zu mir: Hey Rover, fange an zu wischen. Spääder kannsde den Modus wechseln.',
    670: 'Sach zu mir: Hey Rover, komm her und mach da sauber.',
    671: 'Sach zu mir: Hey Rover, fange an zu saugen. Spääder kannsde den Modus wechseln.',
    672: 'Sach zu mir: Hey Rover, fange an zu reinschen. Spääder kannsde de ganze Wohnung machen lassen.',
    674: 'Mei Mobb glemmt vielleicht oder hat sisch was reingewiggelt. Gugge nach und mach en sauber.',
    682: 'Mei Mobb dreht sisch nich mehr.',
    683: 'Der Mobb is nich dran. Mach erst den Mobb dran und broehiers dann nomal.',
    689: 'Isch fange an, Staubbehälter und Beudel zu drochnen.',
    690: 'Das Drochnen von Staubbehälter und Beudel is gestobbt.',
    691: 'Der Mobb wird grade gewaschen. Broehiers spääder nomal.',
    692: 'Isch fahre zum Laden. Ne extra Reinschung geht grade nich.',
    696: 'Fehler an der Glabbe.',
    697: 'Isch bin gesberrt. Mach erst de Kindersischerung aus.',
    698: 'Das Kardenmalen is fertsch. Isch finde de Station nich und fange alleene an zu reinschen.',
    699: 'Sensorfehler. Gugge nach, ob der Kamerasensor dreggsch is.',
    701: 'De Bladde is heiß. Bidde nich anfassen.',
    702: 'Mit ner vorläufschen Karde kann isch nich reinschen. Drügge nomal uff Reinschung, dann wird de Karde gesbeischert.',
    703: 'Isch fange mit der Staub- und Mobbdrochnung an.',
    704: 'De Mobbdrochnung is bausiert.',
    706: 'Fehler am Greisel. Bidde de Uffgabe nomal starden.',
    707: 'Fehler am Fahrgestell. Bidde de Uffgabe nomal starden.',
    708: 'Der Weg zur Ladestation is zu. Gugge nach, ob was im Weg steht.',
    711: 'De Desinfegtion fängt an.',
    712: 'Das Waschbrett is heiß. Bidde nich anfassen.',
    715: 'In der Station fehlt der Mobb. Setz en rein, dann mach isch weider.',
    716: 'In der Station fehlt der Mobb. Setz en rein - solange arbeide isch im Standardmodus.',
    717: 'Der Mobb sitzt nich richdsch. Rügg en zurechte, dann mach isch weider.',
    718: 'Das lässt sisch im Energiesbarmodus nich ändern. Mach den Energiesbarmodus aus und broehiers nomal.',
    719: 'Fehler beim Mobbwechsel.',
    722: 'Der Mobb kommt in heißes Wasser, damit er warm wird. Drum dauerds e bissel länger. Hab e bissel Geduld.',
    723: 'Beim Kardenmalen gugge, dass alles gut beleuchtet is. Stell nischt in de Diren und schieb weder misch noch de Station rum.',
    724: 'Der Mobb liecht in der Station nich richdsch. Rügg en glei zurechte.',
    725: 'Fehler an der Mobbabdeggung.',
    726: 'Fehler am Rollmobb.',
    728: 'Isch fange mit der Bodenblege an.',
    729: 'Der Mobb wird grade gewechselt. Broehiers spääder nomal.',
    731: 'Mei Schmutzwassertank is volle. Stell misch zurügge uff de Station, damit isch den Mobb waschen kann.',
    752: 'Isch mache mit der Bodenblege weider.',
    754: 'Isch hab misch gefunden. Isch mache mit der Bodenblege weider.',
    755: 'Der Lasersensor machds nich. Gugge nach, ob da was dreggsch is oder glemmt.',
    757: 'Mei Schmutzwassertank is volle. Mach en glei leer.',
    758: 'Zu wenisch Wasser. Stell misch zurügge uff de Station und drügge uff Start, dann wird nachgefüllt.',
    765: 'Der Mobb wird grade gewechselt. Broehiers spääder nomal.',
    771: 'Der Rollmobb bleibt stehen oder is blogierd.',
    775: 'Solange der Mobb läuft, lass de Glabbe zu.',
    777: 'De Zeit is um. Gugge nach, ob unterm Gerät was im Weg is.',
    778: 'Achdung, bass uff deine Finger uff.',
    779: 'De Zeit fürs Mobbrausnehmen is um. Isch höre uff.',
    780: 'Das Uffnehmen oder Ablegen vom Mobb hat nich gegladdt. Nimm den Mobb aus der Halderung und lech en wieder ins Fach an der Glabbe.',
    782: 'Fehler beim Uffloggern von der Rolle. Mach se sauber, dann gehds weider.',
    784: 'Wenn Schridd eens fertsch is, fahre isch von alleene aus der Station.',
    785: 'Mach de Waschbrett-Basis bidde mit ner Bürste oder nem Duch sauber. Danach dibbsde in der Abb uff Reinschung beenden.',
    786: 'De Waschbrett-Basis is sauber.',
    787: 'Isch fahre von alleene zur Station zurügge und mache den Mobb sauber und droggen.',
    795: 'Isch fange mit der Reinschung von der Waschbrett-Basis an. Das dauerd ungefähr zwee Minuden.',
    797: 'Da stimmt vielleicht was nich mim Gerät. Ruf beim Kundendienst an.',
    798: 'De Selbstreinschung von der Station dauerd ungefähr vier Minuden. Schieb misch solange nich rum.',
    799: 'De Zeit is um. Gugge nach, ob e Dier oder e Hindernis unterm Gerät steht.',
    805: 'Isch fange an, den groben Dregg uffzusaugen.',
    812: 'Stell misch bidde zum Laden in de Station.',
    813: 'Isch fange mit der gräfdschen Absaugung vom Dregg an.',
    814: 'Isch fange mit der Selbstreinschung von der Station und der gräfdschen Absaugung an.',
    823: "Der Wasserstand im Waschbrett basst nich. Mach's sauber, bevors losgeht.",
    824: 'Der Rollmobb bleibt stehen oder is blogierd.',
    828: 'Der Filder is durch. Mach en bald sauber.',
    849: 'Isch fange an, Staubbehälter und Beudel zu drochnen.',
    850: 'Das Drochnen von Staubbehälter und Beudel is gestobbt.',
    857: 'Setz bidde das Waschbrett rein.',
    910: 'Nu, willgommen in der Ausstellung für Saugrobodder.',
    915: 'Der Wasserstand im Waschbrett basst nich. Mach den Filder sauber, dann verstobft nischt.',
})
