"""Schwäbisch - Stuttgart und Umgebung."""

from __future__ import annotations

from . import muster
from ..i18n import t

KEY = "schwaebisch"
NAME = t("schwaebisch.name")
BESCHREIBUNG = t("schwaebisch.beschreibung")
LANG_ID = "SCHWABE"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "I wart auf's Netzwerk.",
    2: "Mit'm WLAN hots net klappt. Guck dr amol s Passwort a.",
    3: "I komm net auf da Server. Guck dr amol dei Netzwerk a.",
    5: "Netzwerk passt, i bin drin.",
    6: "Mit'm Netzwerk hots net klappt. Probier's später nomol.",

    # --- Reinigung ---------------------------------------------------
    7: "So, jetzt gohts los. I fang a zom Sauga.",
    8: "I mach den oine Fleck sauber.",
    9: "D geplante Reinigung goht jetzt los.",
    10: "I mach weiter, wo i aufghört hab.",
    12: "Fertig. Alles sauber. Kehrwoch erledigt.",
    56: "I mach des Zimmer sauber.",
    57: "I mach d Zone sauber.",
    58: "I mach mei Arbet weiter.",
    61: "I fang a zom Wischa.",
    62: "Du steuerscht mi jetzt selber.",
    82: "I zeichne jetzt a Kart vo dr Wohnung.",
    84: "D Kart isch fertig.",
    105: "Auf gohts, i fang a.",
    126: "I fang a zom Sauga.",
    137: "I saug weiter.",
    138: "I wisch weiter.",
    139: "I komm zrück.",
    143: "Fertig. Do siehts jetzt sauber aus.",
    144: "Gwischt hen i au scho.",
    164: "So, des wars. Feierobed.",
    433: "I mach no a Extrarond.",
    434: "D Extrarond isch fertig, i mach normal weiter.",

    # --- Akku und Laden ----------------------------------------------
    13: "I fahr hoim zom Aufladda.",
    14: "Mei Batterie isch bald leer. I fahr hoim zom Ladda ond mach nochher weiter.",
    17: "Stell mi bitte wieder auf d Station.",
    18: "I lad grad auf.",
    20: "Mei Batterie isch bald leer.",
    21: "Batterie leer. I schalt mi jetzt aus.",
    47: "I fang a zom Ladda.",
    48: "Batterie isch schwach, i fahr zur Station.",
    50: "Mit'm Ladda stimmt ebbes net. Butz mr d Kontakt.",
    301: "I lad grad auf.",
    302: "I schaff grad.",

    # --- Station und Wischen -----------------------------------------
    106: "I wasch mei Wischtuach.",
    107: "I trockne meine Wischtiacher.",
    110: "I saug mein Staub raus.",
    111: "Mir fehlet d Wischtiacher. Mach se mr bitte dra.",
    112: "Stell mi zerscht amol in d Station.",
    113: "Fertig. Mach bitte da Schmutzwassertank leer.",
    114: "D Wischtiacher send dra.",
    115: "D Wischtiacher send runter.",
    148: "I fahr zur Station ond mach mi selber sauber.",
    169: "D Wischtiacher send trocka.",
    177: "I fahr los.",
    179: "Wischtuach isch sauber. Aber s Frischwasser goht mr aus.",
    181: "Mir goht s Wasser aus. Füll mr bitte nach.",
    186: "Guck dr bitte da Frischwassertank a.",
    187: "Des dauert so fünf bis zeh Minutta.",
    318: "Mei Wischtuach isch wieder sauber.",
    636: "Mei Wischtuach isch arg dreckig. I muass zur Station.",

    # --- Fehler und Wartung ------------------------------------------
    35: "Mit dr Hauptbürscht stimmt ebbes net. Butz se mr.",
    36: "Mit dr Seitabürscht stimmt ebbes net. Butz se mr.",
    37: "Mit'm rechta Rädle stimmt ebbes net.",
    38: "Mit'm linka Rädle stimmt ebbes net.",
    40: "Herrschaftszeita, i häng fescht. Machsch mi bitte frei?",
    42: "Guck dr bitte mein Filter a.",
    43: "Mit meim Stoßbügel stimmt ebbes net. Drück amol sanft drauf.",
    44: "Do stimmt ebbes net. Guck bitte in dr Aleitung nach.",
    52: "I stand schief. Stell mi bitte grad hi.",
    66: "Mei Filter isch hi. Tausch'n bitte aus.",
    67: "D Seitabürscht isch hi. Tausch se bitte aus.",
    68: "D Hauptbürscht isch hi. Tausch se bitte aus.",
    91: "Dr Frischwassertank fehlt. Setz'n bitte nei.",
    93: "Z wenig Wasser drin. Füll bitte nach.",
    97: "Do fehlt dr Staubbeutel.",
    102: "Dr Staubbeutel isch voll oder dr Kanal isch verstopft.",
    156: "Mei Wischtuach isch net dra.",
    166: "Do hots ebbes in mei Wischtuach gwickelt. Mach's bitte weg.",
    267: "Meine Sensora send dreckig. Butz se mr bitte.",
    331: "Alles in Ordnung. I hab nix gfonda.",
    332: "I hab a Fehler gfonda. Guck amol in dr App nach.",
    426: "I bin abgrutscht ond häng fescht. I probier's weiter.",
    437: "Passt wieder. Drück auf Start, no gohts weiter.",
    441: "Do hots ebbes om d Hauptbürscht gwickelt. Butz's bitte.",
    442: "Do hots ebbes om d Seitabürscht gwickelt.",
    443: "Om meine Rädle hots ebbes gwickelt.",
    444: "Stell mi bitte auf a freie Fläch, no fang i a.",
    445: "Mei Wischtuach isch mr runter. Guck amol in dr Näh.",
    446: "Am Wischtuachhalter hängt ebbes dra.",
    447: "D Station hot koin Strom. Guck bitte amol nach.",
    448: "Dr Schmutzwassertank fehlt. Setz'n bitte nei.",
    449: "Auf'm Teppich fang i net a. Stell mi auf da Hartboda.",
    454: "Z wenig Wasser im Tank. Füll mr bitte nach.",
    455: "Dr Frischwassertank sitzt net richtig drin.",
    456: "Dr Schmutzwassertank isch voll oder er fehlt.",
    458: "Dr Staubbeutel sitzt net richtig.",
    460: "Dr Geruchsfilter isch aufbraucht. Tausch'n bitte aus.",
    639: "Do fehlt dr Filter vom Waschbrett.",
    658: "Dr Kalkschutz isch aufbraucht. Tausch'n bitte aus.",

    # --- Wegfindung ---------------------------------------------------
    30: "I guck grad, wo i bin.",
    31: "I woiß net, wo i bin. I fang halt nei a.",
    45: "I ben do!",
    149: "Do komm i net na. Raum bitte weg, was im Weg stoht.",
    151: "Mei Weg isch verstellt. Raum bitte ebbes weg.",
    153: "I stand in ere Sperrzon. Nimm mi do bitte raus.",

    # --- Bedienung -----------------------------------------------------
    26: "I setz mi zrück auf d Werkseinstellung.",
    27: "I mach a Update. Dauert fünf Minutta. Bitte net ausschalta.",
    28: "S Update hot klappt.",
    29: "S Update hot net klappt. Probier's später nomol.",
    116: "D Kindersicherung isch a. D Knöpf send gsperrt.",
    117: "D Kindersicherung isch aus.",
    162: "D Kamera isch a.",
    329: "I test mi grad selber. Nimm mi net vo dr Station runter.",
    421: "Griaß di. Ab jetzt schwätz i Schwäbisch mit dr.",
    632: "Dr Sprachwechsel dauert a halbe Minutt.",
    633: "Dr Sprachwechsel hot net klappt.",

    # --- Sprachassistent ------------------------------------------------
    190: "Passt, i fang a zom Sauga.",
    191: "Passt, i saug ond wisch.",
    192: "Passt, i wisch.",
    193: "Passt, i saug.",
    221: "Passt scho.",
    246: "I ben do hinta!",
    247: "Des hab i jetzt net verstanda.",
    508: "I schwätz lauter.",
    509: "I schwätz leiser.",
    510: "Guat, i hör auf für heit.",
    515: "Sei so guat ond heb amol d Füaß.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Akku isch bei {p} Prozent.'
RAUM_MUSTER = 'Passt, i mach {raum} sauber.'
RAUM_NAMEN = {
    'wohnzimmer': 's Wohnzimmer',
    'schlafzimmer': 's Schlafzimmer',
    'hauptschlafzimmer': 's Hauptschlafzimmer',
    'gaestezimmer': 's Gäschtezimmer',
    'arbeitszimmer': 's Arbetszimmer',
    'kueche': 'd Kuchi',
    'esszimmer': 's Esszimmer',
    'bad': 's Bad',
    'balkon': 'da Balkon',
    'flur': 'da Gang',
    'hauswirtschaftsraum': 'd Waschkuchi',
    'abstellraum': 'd Abstellkammer',
    'salon': 'da Salon',
    'buero': 's Büro',
    'gym': 'da Fitnessraum',
    'freizeitraum': 'da Freizeitraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))

# --------------------------------------------------------------------------
# Vollständige Abdeckung: die restlichen Ansagen des X50 Ultra Complete.
# Nummern ohne Sprachinhalt (Klänge, Tierlaute) bleiben im Original; die
# Nummern-Umsetzung des Modells versorgt 856, 858, 859, 863 und 864.
# --------------------------------------------------------------------------

TEXTE.update({
    # --- Netzwerk -----------------------------------------------------
    4: "I ben aus'm Netzwerkmodus raus.",
    304: "S Netzwerk isch verbonda.",
    306: "Des hab i net verstanda. Richt zerscht s Netzwerk ei.",
    313: "Dr Empfang isch schlecht. Stell mi wo anders na.",
    377: "S Netzwerk lauft net. Frag beim Kundadienscht nach.",
    378: "S Passwort stimmt net. Richt s Netzwerk nomol ei.",
    379: "I find koi WLAN. Nimm s Zwoikommavier-Gigahertz-Netz.",
    380: "I hab koi IP-Adress kriagt. Guck amol en dein Router.",
    381: "I komm net auf da Server. Frag beim Kundadienscht nach.",
    382: "I komm net ens Netz. Guck, ob dei Internet lauft.",
    383: "S Netzwerk lauft net. Frag beim Kundadienscht nach.",
    385: "I verbend mi grad mit'm Netzwerk.",

    # --- Reinigung ----------------------------------------------------
    11: "I mach a Pause.",
    54: "Positionierung passt, i saug weiter.",
    55: "Positionierung passt, i fahr weiter zur Station.",
    64: "Positionierung hot net klappt. I fahr zur Station.",
    65: "I fahr weiter zur Station.",
    77: "Stell mi auf an Hartboda, no fang i a.",
    83: "I zeichne weiter a dr Kart.",
    85: "Positionierung passt, i zeichne weiter.",
    86: "Positionierung hot net klappt. I fang mit'm Zeichne nei a.",
    127: "I mach da Fleck sauber.",
    128: "I wisch da Fleck.",
    129: "D geplante Reinigung goht los.",
    130: "D geplante Kartierung goht los.",
    133: "I mach d ausgsuchte Zimmer sauber.",
    134: "I wisch d ausgsuchte Zimmer.",
    135: "I mach d Zone sauber.",
    136: "I wisch d Zone.",
    145: "Positionierung passt, i saug weiter.",
    146: "Positionierung passt, i zeichne weiter.",
    150: "Do komm i net na. Nimm bitte d Sperrzone weg.",
    152: "Mei Weg isch verstellt. Nimm d Sperrzone weg oder stell mi wo anders na.",
    163: "I guck grad mit dr Kamera.",
    171: "D schlaue Hindernisumfahrung isch a.",
    172: "D schlaue Hindernisumfahrung isch aus.",
    257: "D Kameraüberwachung isch aus.",
    280: "I fang mit dr eigstellte Reinigung a.",
    321: "I fang mit'm gründliche Fleckawische a.",
    344: "Passt, i saug zerscht ond wisch nochher.",
    362: "S Wischtuach sitzt net richtig. I saug stattdesse bloß.",
    363: "S Sauga isch fertig, jetzt wisch i.",
    366: "Do isch a Fleck, i mach en sauber.",
    367: "Passt, i mach da Fleck sauber.",
    368: "Do isch a Fleck. I mach en sauber, wenn i gwäsche hab.",
    369: "Passt, i mach do sauber.",
    424: "I woiß net, wo i ben. Stell mi auf a freie Fläch ond fang nei a.",
    435: "I fahr aus dem Bereich raus.",
    450: "En ere Sperrzon fang i net a. Stell mi wo anders na.",
    451: "Em versteckte Bereich fang i net a. Stell mi wo anders na.",
    677: "Do komm i net na. Nimm d Sperrzone oder d Schwelle weg.",
    678: "Mei Weg isch verstellt. Nimm d Sperrzone oder d Schwelle weg.",
    679: "I stand en ere Sperrzon. Nimm mi do bitte raus.",
    680: "I zeichne zerscht a Kart, no mach i sauber.",
    681: "Passt, i mach weiter.",

    # --- Akku und Laden ------------------------------------------------
    19: "Nimm mi vo dr Station runter, bevor du mi ausmachsch.",
    25: "Dr Akku isch z schwach für d geplante Reinigung.",
    87: "Batterie schwach, i fahr zur Station.",
    303: "I ruh mi grad aus.",
    307: "I lad grad auf.",

    # --- Fehler und Wartung --------------------------------------------
    34: "Do fehlt a Deil. Setz's bitte nei.",
    39: "Meine Räder henget en dr Luft. Butz d Abstürzsensora.",
    41: "Meine Räder henget en dr Luft. Stell mi wo anders na.",
    71: "Guck amol, ob am Laser-Abstandssensor ebbes klemmt.",
    72: "D Abdeckung vom Lasersensor klemmt.",
    73: "Mit'm Kantasensor stimmt ebbes net.",
    75: "Dr Filter isch feucht oder verstopft.",
    81: "Mit'm Teppichsensor stimmt ebbes net.",
    108: "Mit'm Wasserstand vom Waschbrett stimmt ebbes net. Butz's.",
    109: "Mit'm Schmutzwassertank stimmt ebbes net. Guck, ob er drin ond leer isch.",
    118: "D Knöpf send gsperrt. Halt d Tast a dr Station druckt.",
    142: "S Wischtuach isch hi. Tausch's bitte aus.",
    173: "Tausch bitte s Silberiona-Modul aus.",
    244: "D Reinigungsmittelflasch isch dra.",
    245: "Mehr Karta gehet net. Lösch bitte oine en dr App.",
    296: "Guck amol, ob dr Schmutzwassertank voll isch.",
    297: "D Reinigungsmittelflasch isch dra. Wenn du se no nie braucht hosch, guck en dr App.",
    298: "I mach s Waschbrett sauber.",
    299: "D Reinigungsmittelflasch ond s Nachfüllmodul send dra.",
    300: "Des Zubehör kenn i net.",
    312: "Über des Zubehör woiß i nix. Tausch's aus, wenn's hi isch.",
    315: "S Wischtuach isch net en dr Station. Leg's nei ond probier's nomol.",
    316: "En dr Station leit scho a Wischtuach.",
    319: "S Wischtuach isch net runter. Nimm's vo Hand ab.",
    320: "S Wischtuach isch net dra. Mach's vo Hand dra.",
    330: "Wart, bis dr Selbschttest fertig isch.",
    355: "Z wenig Wasser. Füll da Frischwassertank nach.",
    356: "Dr Fehler isch no do. D geplante Reinigung isch abgsagt.",
    384: "Em automatische Wassermodul isch koi Wasser.",
    388: "Do derf i net na. Stell mi wo anders na.",
    389: "Dr Laser fahrt net runter. Guck, ob ebbes klemmt.",
    390: "Dr Laser fahrt net nauf. Guck, ob ebbes klemmt.",
    391: "Stell mi auf a freie Fläch, bevor's losgoht.",
    392: "Em Clean-Genius-Modus lauft des net.",
    438: "Dr Stoßbügel klemmt. Druck amol sanft drauf.",
    439: "D Laserabdeckung klemmt. Druck amol sanft drauf.",
    440: "A Rädle hängt en dr Luft. Stell mi auf a freie Fläch.",
    452: "Mit'm Teppichsensor stimmt ebbes net. Dreh mi om ond butz s weiße Loch.",
    453: "Mit'm Kantasensor stimmt ebbes net. Butz mi rechts a.",
    457: "Dr Schmutzwassertank isch voll oder net drin. Guck amol nach.",
    459: "Dr Wischtuachhalter sitzt net richtig. Guck amol nach.",
    663: "Mit'm Wasserstand em Waschbrett stimmt ebbes net. Butz's.",
    673: "Om meine Beinle hot sich villeicht ebbes gwickelt. Butz's vor'm Start.",

    # --- Basisstation ---------------------------------------------------
    46: "Roboter ond Handy send verbonda.",
    59: "D Kart isch fertig. Nimm da Wassertank raus.",
    140: "A neue Umgebung. I fahr zur Station.",
    188: "I dock automatisch a.",
    209: "Passt, i fahr zur Station ond wasch mei Wischtuach.",
    210: "I wasch d Wischtiacher.",
    211: "Aussauga goht bloß, wenn i en dr Station stand.",
    212: "Passt, i saug mi aus.",
    213: "Trockne goht bloß, wenn i en dr Station stand.",
    214: "I trockne grad.",
    215: "Passt, i fang mit'm Trockne a.",
    216: "Do muass zerscht s Wischtuach dra.",
    278: "Passt, s Trockne isch fertig.",
    349: "Guck, dass d Station Strom hot, ond stell mi drauf.",
    350: "I fang mit'm Eirichte vo dr Station a.",
    351: "D Station isch eigricht.",
    352: "S Eirichte hot net klappt. Guck en dr App nach.",
    360: "I lass s Wasser ausm Tank.",
    361: "S Wasser isch draußa.",
    371: "Nimm bitte s Waschbrett raus.",
    372: "S Frischwasser lauft nei.",
    373: "S Wasser isch drin. Wart zeh Sekonda, no gohts weiter.",
    374: "Butz da Boda vo dr Station mit ere Bürscht oder eme Tuach.",
    375: "Schieb da Dreck zom Aussauga hi. Des dauert a bissle.",
    376: "S Aussauga isch fertig. Butz s Waschbrett extra ond setz's wieder nei.",
    396: "I mach s Wassermodul leer. Des dauert a bissle.",
    397: "S Wasser isch oba ond onta draußa.",
    398: "D Kart isch fertig. Guck se dr en dr App a ond stell mi zrück.",
    399: "Dr Test isch fertig. Stell mi zrück auf d Station.",
    400: "D Selbschtreinigung isch fertig. Stell mi jetzt auf s richtige Stockwerk.",
    401: "Stell mi auf d Station, no fang i mit dr Selbschtreinigung a.",
    478: "Wenn i gwäsche hab, mach i mit'm Sauga weiter.",
    479: "Passt, fang dei Arbet nei a.",
    480: "Füll gnug Wasser nei, dass es fürs Nächschte reicht.",
    481: "I mach da Handstaubsauger leer.",
    482: "I mach da Handstaubsauger leer. Mi selber saug i nochher aus.",
    483: "I mach da Handstaubsauger leer. S Wischtuach wasch i nochher.",
    484: "I mach da Handstaubsauger leer. Gsaugt wird nochher.",
    485: "I saug mi grad aus. Dr Handstaubsauger kommt nochher.",
    486: "I wasch grad s Wischtuach. Dr Handstaubsauger kommt nochher.",
    487: "Guck, dass i en dr Station stand.",
    638: "I saug mi weiter aus.",
    661: "I mach s Waschbrett sauber. Des dauert a knappe Minutt.",
    662: "I mach elektrolysiertes Wasser zom Butze.",

    # --- Sprachassistent -------------------------------------------------
    194: "I ben scho am Sauga.",
    195: "Passt, i mach des Zimmer sauber. Guck, dass d Tür auf isch.",
    196: "Passt, i saug da Boda. Guck, dass d Tür auf isch.",
    197: "Passt, i wisch da Boda. Guck, dass d Tür auf isch.",
    198: "Passt, i saug ond wisch. Guck, dass d Tür auf isch.",
    199: "Des Zimmer kenn i net. Guck en dr App, wie's hoißt.",
    200: "Machs guat.",
    201: "Passt, i mach weiter.",
    202: "Passt, i hör auf ond fahr zom Lada.",
    203: "Passt, i fahr zom Lada.",
    204: "Passt, i fang mit'm Zeichne a. Mach bitte alle Türa auf.",
    205: "Passt, i fahr vo dr Station runter.",
    206: "Passt, i guck, wo du bisch.",
    207: "I find di net. Stell di en mei Sichtweit.",
    208: "Do bisch ja. I komm sauga.",
    217: "Mehr Saugkraft goht nemme.",
    218: "Weniger Saugkraft goht nemme.",
    219: "Mehr Wasser goht nemme.",
    220: "Weniger Wasser goht nemme.",
    222: "Saugstuf leis.",
    223: "Saugstuf normal.",
    224: "Saugstuf stark.",
    225: "Saugstuf Turbo.",
    226: "S Wischtuach isch leicht feucht.",
    227: "S Wischtuach isch feucht.",
    228: "S Wischtuach isch nass.",
    229: "Heit isch",
    230: "Heit isch dr oinazwanzigschte Februar zwoitausendzwoiazwanzig.",
    231: "Heit isch Mendig.",
    232: "Heit isch Zieschdig.",
    233: "Heit isch Mittwoch.",
    234: "Heit isch Donnschdig.",
    235: "Heit isch Freidig.",
    236: "Heit isch Samschdig.",
    237: "Heit isch Sonndig.",
    238: "Passt, i hör auf.",
    248: "S Wischtuach fehlt. Mach's dra ond probier's nomol.",
    249: "I schaff grad. Mach des zerscht fertig, no gohts.",
    250: "I ben grad em Wischmodus. Stell bitte om.",
    251: "I ben grad em Saugmodus. Stell bitte om.",
    252: "Fertig. I ben aus dr eigstellte Reinigung raus.",
    253: "Lauter goht nemme.",
    254: "Leiser goht nemme.",
    255: "Des goht bloß mit eigschaltete Hindernisumfahrung.",
    258: "I fang a romzfahre.",
    259: "I fahr zu dere Stell na.",
    260: "I fahr weiter rom.",
    261: "I fahr weiter zu dere Stell.",
    262: "I woiß net, wo i ben.",
    266: "Tausch bitte s Reinigungsmittel aus.",
    269: "Probier's nomol, wenn i fertig ben.",
    275: "Des kenn i net. En dr App stanget alle Sprachbefehle.",
    276: "Des mach i grad net.",
    277: "Passt, i komm ond mach do sauber.",
    279: "I saug grad. Mach des zerscht fertig ond probier's nomol.",
    281: "I saug mi grad aus. Probier's glei nomol.",
    282: "I wasch grad mei Wischtuach. Probier's glei nomol.",
    283: "I stand net en dr Station. Probier's spder nomol.",
    284: "Passt, i hör auf ond komm sauga.",
    285: "Bleib kurz stande, i guck wo du bisch.",
    286: "Do brauch i zerscht a Kart.",
    287: "Passt, jetzt isch leis.",
    288: "Passt, jetzt isch normal.",
    289: "Passt, jetzt isch stark.",
    290: "Passt, jetzt isch Turbo.",
    291: "Passt, jetzt isch leicht feucht.",
    292: "Passt, jetzt isch nass.",
    293: "Aruf send a.",
    294: "Aruf send aus.",
    305: "Passt, i mach s Waschbrett sauber. Butz's inna mit ere Bürscht.",
    308: "Des hab i net mitkriagt. Weck mi nomol.",
    309: "Do bisch ja, i komm.",
    310: "Passt, i fahr glei do weg.",
    311: "D Wischtiacher send runter.",
    314: "Des goht net. Du kannsch mr saga, i soll mi umdrehe.",
    317: "Des goht grad net, i mach a eigstellte Reinigung.",
    322: "Des kenn i net. En dr App stanget alle Sprachbefehle.",
    323: "Des kenn i net. Frag mi amol, was i alles ka.",
    324: "I wasch mi grad. Weck mi, wenn i fertig ben.",
    328: "Des kannsch mr bloß saga, wenn i grad saug.",
    338: "Dr Videoaruf stoht.",
    340: "Koi Antwort.",
    341: "Do bisch ja. I gang dr nach. Sag End, wenn's reicht.",
    342: "Wo bisch? Stell di ungfähr anderthalb Meter vor mi.",
    343: "I hab di verlore. Du bisch z schnell. Stell di anderthalb Meter vor mi.",
    364: "I richt da Videocode ei.",
    365: "S Livebild isch aus.",
    489: "I ben em Clean-Genius-Modus. Sag mr, i soll aufhöre.",
    490: "Passt, eigstellte Reinigung: i wisch.",
    491: "Passt, eigstellte Reinigung: i saug.",
    511: "I mach grad nix.",
    512: "En dr Kart isch no koi Tiermöbel. Trag's en dr App ei.",
    513: "Passt, i mach oms Tiermöbel rom sauber.",
    516: "I guck, wo dei Viech steckt.",
    517: "I hab's gfonda. I fahr zom Lada.",
    518: "I hab koins gfonda. I fahr zom Lada.",
    522: "Was isch denn schiefganga?",
    523: "Kannsch mr des a bissle genauer saga?",
    524: "Nimm mi dahi, wo's passiert isch.",
    525: "Wart kurz, i guck mr des a.",
    641: "Sag mr oifach, i soll mit'm Sauga afanga.",
    642: "Sag mr oifach, i soll stärker sauga.",
    643: "Sag mr oifach, i soll mehr Wasser nemme.",
    644: "Sag mr oifach, i soll sauga ond wische.",
    645: "Sag mr oifach, i soll wische.",
    646: "Sag mr oifach, i soll dahi komme ond sauber mache.",
    647: "Sag mr oifach, i soll zerscht sauga ond no wische.",
    648: "Sag mr oifach, i soll alles sauber mache.",
    659: "Des hab i net verstanda. Frag mi amol, was i alles ka.",
    694: "Sag mr oifach, i soll mit'm Sauga afanga.",

    # --- Erste Einrichtung ------------------------------------------------
    463: "Griaß di, schee dass d do bisch. Mach da Deckel auf ond scann da QR-Code.",
    464: "Damit spder alles glatt lauft, stell mi vor'm Start auf d Station.",
    465: "Stell mi vor'm Start auf d Station. Wenn du 'I lad auf' hörsch, passt's.",
    466: "Mach bitte d Türa auf ond raum da Boda frei.",
    467: "Stell mi auf d Station ond fang s Zeichne nei a.",
    468: "Guck dr d Kart bitte en dr App a.",
    630: "Griaß di, schee dass d do bisch. Mach da Deckel auf ond scann da QR-Code.",
})

# --------------------------------------------------------------------------
# Die letzten Ansagen des r2532v (X50 Ultra Complete). Ihr Wortlaut steht in
# keiner Textdatei des Pakets - er wurde aus den deutschen Originalaufnahmen
# transkribiert (Windows-Spracherkennung) und anschliessend von Hand
# geglättet. Sinngemäß richtig, im Wortlaut sinnvoll gekürzt.
# --------------------------------------------------------------------------

TEXTE.update({
    24: 'Guck amol, ob dr Wassertank recht drensteckt.',
    101: 'D Klappe vo dr Absaugstation isch offe oder dr Beutel fehlt. Mach d Klappe zua oder leg an Beutel nei.',
    104: 'S Waschbrett isch et dren. Setz es nei ond mach d Klammera auf beide Seita fescht.',
    170: 'D Taschtesperr isch a. Halt d Taschte an dr Station drückt, no gohts wieder auf.',
    339: 'Aruf abglehnt.',
    353: 'Dr Schmutzwasserbehälter isch dren.',
    354: 'Dr Schmutzwasserbehälter isch draußa.',
    358: 'Setz bitte den Schmutzwasserbehälter nei.',
    386: 'Mei Schmutzwasserbehälter isch voll. I fahr zrück ond leer en aus.',
    387: 'S Ausleera isch fertig. I mach weiter.',
    393: 'Mei Schmutzwasserbehälter isch dreckig. Mach en glei sauber.',
    394: 'Dr Wassersensor mag nemme.',
    631: 'Schee, dass du di für den Dreame entschieda hosch. Mach d Klappe auf ond scann den QR-Code, no kasch d App lada.',
    634: 'I fang a, d Haar z entwirra.',
    660: 'Tschuldigong, des hab i et verstanda. Sag Hey Rover, was kannst du, no sag i dr, was i alles ka.',
    664: 'Sag zu mr: Hey Rover, fang a zom Reiniga.',
    665: 'Wenn alles passt, sag zu mr: Hey Rover, fang a zom Reiniga.',
    666: 'Sag zu mr: Hey Rover, mach d Saugkraft stärker.',
    667: 'Sag zu mr: Hey Rover, gib meh Wasser.',
    668: 'Sag zu mr: Hey Rover, fang a zom Sauga. Später sagsch wischa, no wechsel i den Modus.',
    669: 'Sag zu mr: Hey Rover, fang a zom Wischa. Später kasch den Modus wechsla.',
    670: 'Sag zu mr: Hey Rover, komm her ond mach do sauber.',
    671: 'Sag zu mr: Hey Rover, fang a zom Sauga. Später kasch den Modus wechsla.',
    672: 'Sag zu mr: Hey Rover, fang a zom Reiniga. Später kasch d ganz Wohnong macha lassa.',
    674: 'Mei Mopp klemmt vielleicht oder hot sich ebbes neigwicklet. Guck noch ond mach en sauber.',
    682: 'Mei Mopp dreht sich nemme.',
    683: 'Dr Mopp isch et dra. Mach zerscht den Mopp dra ond probiers no amol.',
    689: 'I fang a, Staubbehälter ond Beutel z trockna.',
    690: 'S Trockna vo Staubbehälter ond Beutel isch gstoppt.',
    691: 'Dr Mopp wird grad gwäscha. Probiers später no amol.',
    692: 'I fahr zom Lada. A extra Reinigong goht grad et.',
    696: 'Fehler an dr Klappe.',
    697: 'I bin gsperrt. Mach zerscht d Kindersicherong aus.',
    698: 'S Kartazeichna isch fertig. I find d Station et ond fang selber a zom Reiniga.',
    699: 'Sensorfehler. Guck noch, ob dr Kamerasensor dreckig isch.',
    701: 'D Platt isch heiß. Bitte et alanga.',
    702: 'Mit ra provisorische Karte ka i et reiniga. Drück no amol auf Reinigong, no wird d Karte gspeichert.',
    703: 'I fang mit dr Staub- ond Mopptrocknong a.',
    704: 'D Mopptrocknong isch pausiert.',
    706: 'Fehler am Kreisel. Bitte d Aufgab no amol starta.',
    707: 'Fehler am Fahrgstell. Bitte d Aufgab no amol starta.',
    708: 'Dr Weg zor Ladestation isch zua. Guck noch, ob ebbes im Weg stoht.',
    711: 'D Desinfektion fangt a.',
    712: 'S Waschbrett isch heiß. Bitte et alanga.',
    715: 'In dr Station fehlt dr Mopp. Setz en nei, no mach i weiter.',
    716: 'In dr Station fehlt dr Mopp. Setz en nei - solang schaff i im Standardmodus.',
    717: 'Dr Mopp sitzt et recht. Ruck en zrecht, no mach i weiter.',
    718: 'Des lasst sich im Energiesparmodus et ändera. Mach den Energiesparmodus aus ond probiers no amol.',
    719: 'Fehler beim Moppwechsel.',
    722: 'Dr Mopp kommt in heiß Wasser, dass er warm wird. Drom dauerts a bissle länger. Hab a bissle Geduld.',
    723: 'Beim Kartazeichna guck, dass alles guat beleuchtet isch. Stell nix in d Türa ond schieb weder mi no d Station rom.',
    724: 'Dr Mopp liegt in dr Station et recht. Ruck en glei zrecht.',
    725: 'Fehler an dr Moppabdeckong.',
    726: 'Fehler am Rollmopp.',
    728: 'I fang mit dr Bodapfleg a.',
    729: 'Dr Mopp wird grad gwechslet. Probiers später no amol.',
    731: 'Mei Schmutzwassertank isch voll. Stell mi zrück auf d Station, dass i den Mopp wäscha ka.',
    752: 'I mach mit dr Bodapfleg weiter.',
    754: 'I hab mi gfonda. I mach mit dr Bodapfleg weiter.',
    755: 'Dr Lasersensor mag et. Guck noch, ob do ebbes dreckig isch oder klemmt.',
    757: 'Mei Schmutzwassertank isch voll. Leer en glei aus.',
    758: 'Z wenig Wasser. Stell mi zrück auf d Station ond drück auf Start, no wird nochgfüllt.',
    765: 'Dr Mopp wird grad gwechslet. Probiers später no amol.',
    771: 'Dr Rollmopp bleibt stoh oder isch blockiert.',
    775: 'Solang dr Mopp lauft, lass d Klappe zua.',
    777: 'D Zeit isch rom. Guck noch, ob onterm Gerät ebbes im Weg isch.',
    778: 'Achtong, pass auf dei Finger auf.',
    779: 'D Zeit fürs Moppraushola isch rom. I hör auf.',
    780: 'S Aufnehma oder Ablega vom Mopp hot et klappt. Nimm den Mopp aus dr Halterong ond leg en wieder ens Fach an dr Klappe.',
    782: 'Fehler beim Auflockera vo dr Rolle. Mach se sauber, no gohts weiter.',
    784: 'Wenn Schritt oins fertig isch, fahr i vo selber aus dr Station.',
    785: 'Mach d Waschbrett-Basis bitte mit ra Bürscht oder ma Tuach sauber. Nochher tippsch in dr App auf Reinigong beenda.',
    786: 'D Waschbrett-Basis isch sauber.',
    787: 'I fahr vo selber zor Station zrück ond mach den Mopp sauber ond trocka.',
    795: 'I fang mit dr Reinigong vo dr Waschbrett-Basis a. Des dauert ongfähr zwoi Minuta.',
    797: 'Do stimmt vielleicht ebbes et mitm Gerät. Ruf beim Kondadienscht a.',
    798: 'D Selbschtreinigong vo dr Station dauert ongfähr vier Minuta. Schieb mi solang et rom.',
    799: 'D Zeit isch rom. Guck noch, ob a Viech oder a Hindernis onterm Gerät stoht.',
    805: 'I fang a, den grobe Dreck aufzsauga.',
    812: 'Stell mi bitte zom Lada in d Station.',
    813: 'I fang mit dr kräftige Absaugong vom Dreck a.',
    814: 'I fang mit dr Selbschtreinigong vo dr Station ond dr kräftige Absaugong a.',
    823: "Dr Wasserstand im Waschbrett passt et. Mach's sauber, bevors losgoht.",
    824: 'Dr Rollmopp bleibt stoh oder isch blockiert.',
    828: 'Dr Filter isch durch. Mach en bald sauber.',
    849: 'I fang a, Staubbehälter ond Beutel z trockna.',
    850: 'S Trockna vo Staubbehälter ond Beutel isch gstoppt.',
    857: 'Setz bitte s Waschbrett nei.',
    910: 'Griaß di ond willkomma in dr Ausstellong für Saugroboter.',
    915: 'Dr Wasserstand im Waschbrett passt et. Mach den Filter sauber, no verstopft nix.',
})
