"""Wienerisch - Wien-Stadt, lautgetreu geschrieben, leicht grantig.

Diese Fassung wurde durchgehend überarbeitet. Vorher standen hier zwei
Schreibweisen nebeneinander (halbes Hochdeutsch und lautgetreu), und der
später ergänzte Teil war altbairisch geprägt - in Wien schlicht falsch.

Die Regeln, nach denen hier geschrieben wird:

* r wird zum Vokal:   Wasser -> Wossa, wieder -> wieda, unter -> unta
* l wird zum Vokal:   viel -> vü, alles -> ois, voll -> voi, stellen -> stö
* a wird dunkel:      machen -> mochn, haben -> hom, was -> wos
* ei wird zu aa:      heiss -> haaß, weiss -> waaß, zwei -> zwaa
* uo wird zu ua:      gut -> guat, Tuch -> Tuach
* an- wird zu au-:    anschauen -> auschaun, andocken -> audockn
* Richtungswörter:    eine, ausse, obe, aufe, umadum

Nicht wienerisch und deshalb verbannt: Pfinzta/Erchta (Donnersta,
Diensta), nacha (nacher), eini/aussa/abi/auffi, a bisserl (a bissl),
Wosser (Wossa), umanand (umadum), kimm (kum), bloss (nur).

Der Grant ist bewusst sparsam dosiert - bei fast 600 Ansagen wird
Dauergrant anstrengend, und Fehlermeldungen müssen verständlich bleiben.
Er sitzt dort, wo ein Wiener wirklich grantig wäre: Start, Ende,
Feststecken, Blockaden.
"""

from __future__ import annotations

from . import muster
from ..i18n import t

KEY = "wienerisch"
NAME = t("wienerisch.name")
BESCHREIBUNG = t("wienerisch.beschreibung")
LANG_ID = "WIEN"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "I wart aufs Netzwerk.",
    2: "Mit'm WLAN hot's ned highaut. Schau da bitte s Passwort au.",
    3: "I kum ned auf'n Server. Schau da bitte dei Netzwerk au.",
    4: "I bin ausm Netzwerkmodus ausse.",
    5: "Netzwerk passt, i bin drin.",
    6: "Mit'm Netzwerk hot's ned highaut. Probier's späda nomoi.",
    304: "S Netzwerk is verbunden.",
    306: "Des hob i ned verstandn. Richt zerst s Netzwerk ei.",
    313: "Da Empfang is schlecht. Stö mi woandas hi.",
    377: "S Netzwerk mog ned. Frog bei'm Kundendienst noch.",
    378: "S Passwort stimmt ned. Richt s Netzwerk nomoi ei.",
    379: "I find kaa WLAN. Nimm s Zwaakommavier-Gigahertz-Netz.",
    380: "I hob kaane IP-Adresse kriagt. Schau amoi in dein Router.",
    381: "I kum ned zum Server. Frog bei'm Kundendienst noch.",
    382: "I kum ned ins Netz. Schau, ob dei Internet geht.",
    383: "S Netzwerk mog ned. Frog bei'm Kundendienst noch.",
    385: "I verbind mi grod mit'm Netzwerk.",

    # --- Reinigung ---------------------------------------------------
    7: "Na servas, dann fang ma au. I saug jetzt.",
    8: "I mach den aan Fleck sauba.",
    9: "De eigstellte Reinigung geht jetzt los.",
    10: "I mach weida, wo i aufghört hob.",
    11: "I leg a Pausn ei.",
    12: "Ferti samma. Ois sauba.",
    54: "Passt, i saug weida.",
    55: "Passt, i fahr weida zur Station.",
    56: "I mach des Zimma sauba.",
    57: "I mach de Zone sauba.",
    58: "I mach mei Hackn weida.",
    61: "I fang au zum Wischn.",
    62: "Du steuerst mi jetzt söwa.",
    64: "Des hot ned highaut. I fahr zur Station.",
    65: "I fahr weida zur Station.",
    77: "Stö mi auf'n hoartn Bodn, dann fang i au.",
    82: "I zeichne jetzt a Kartn von da Wohnung.",
    83: "I zeichne weida au da Kartn.",
    84: "De Kartn is ferti.",
    85: "Passt, i zeichne weida.",
    86: "Des hot ned highaut. I fang mit'm Zeichnen neich au.",
    105: "Auf geht's, i fang au.",
    126: "I fang au zum Saugn.",
    127: "I mach den Fleck sauba.",
    128: "I wisch den Fleck.",
    129: "De eigstellte Reinigung geht los.",
    130: "S eigstellte Zeichnen geht los.",
    133: "I mach de ausgsuachtn Zimma sauba.",
    134: "I wisch de ausgsuachtn Zimma.",
    135: "I mach de Zone sauba.",
    136: "I wisch de Zone.",
    137: "I saug weida.",
    138: "I wisch weida.",
    139: "I kum zruck.",
    143: "Ferti. Do schaut's jetzt sauba aus, gö.",
    144: "Gwischt hob i a scho.",
    145: "Passt, i saug weida.",
    146: "Passt, i zeichne weida.",
    150: "Do kum i ned hi. Nimm bitte de Sperrzonen weg.",
    152: "Mei Weg is verstöllt. Nimm de Sperrzonen weg oda stö mi woandas hi.",
    163: "I schau grod mit da Kamera.",
    164: "So, des war's. Feierobend.",
    171: "De gscheite Hindernisumfahrung is eigschoitn.",
    172: "De gscheite Hindernisumfahrung is aus.",
    257: "De Kameraüberwachung is aus.",
    280: "I fang mit da eigstelltn Reinigung au.",
    321: "I fang mit'm grindlichn Fleckenwischn au.",
    344: "Passt scho, i saug zerst und wisch nacher.",
    362: "S Wischtuach sitzt ned richtig. Dann saug i hoit nur.",
    363: "S Saugn is ferti, jetzt wisch i.",
    366: "Do is a Fleck, i mach'n sauba.",
    367: "Passt scho, i mach'n Fleck sauba.",
    368: "Do is a Fleck. I mach'n sauba, wenn i gwoschn hob.",
    369: "Passt scho, i mach do sauba.",
    424: "I waaß ned, wo i bin. Stö mi auf a freie Flächn und fang neich au.",
    433: "I mach no a Extrarundn.",
    434: "De Extrarundn is ferti, i mach normal weida.",
    435: "I fahr aus dem Bereich ausse.",
    450: "In ana Sperrzone fang i ned au. Stö mi woandas hi.",
    451: "Im verstecktn Bereich fang i ned au. Stö mi woandas hi.",
    677: "Do kum i ned hi. Nimm de Sperrzonen oda de Schwelln weg.",
    678: "Mei Weg is verstöllt. Nimm de Sperrzonen oda de Schwelln weg.",
    679: "I steh in ana Sperrzone. Hol mi do bitte ausse.",
    680: "I zeichne zerst a Kartn, dann mach i sauba.",
    681: "Passt scho, i mach weida.",

    # --- Akku und Laden ----------------------------------------------
    13: "I fahr ham zum Aufladn.",
    14: "Mei Batterie is boid leer. I fahr ham zum Ladn und mach nacher weida.",
    17: "Stö mi bitte wieda auf de Station.",
    18: "I lad grod auf.",
    19: "Nimm mi von da Station obe, bevor'st mi ausschoitst.",
    20: "Mei Batterie is boid leer.",
    21: "Batterie leer. I schoit mi jetzt ob.",
    25: "Da Akku is z'schwoch für de eigstellte Reinigung.",
    47: "I fang au zum Ladn.",
    48: "Batterie is schwoch, i fahr zur Station.",
    50: "Mit'm Ladn stimmt wos ned. Putz ma bitte de Kontakte.",
    87: "Batterie schwoch, i fahr zur Station.",
    301: "I lad grod auf.",
    302: "I bin grod am Hackln.",
    303: "I rast mi grod aus.",
    307: "I lad grod auf.",
    692: "I fahr zum Ladn. A extra Reinigung geht grod ned.",
    708: "Da Weg zur Ladestation is zua. Schau noch, ob wos im Weg steht.",
    812: "Stö mi bitte zum Ladn in de Station.",

    # --- Station und Wischen -----------------------------------------
    59: "De Kartn is ferti. Nimm'n Wossatank ausse.",
    106: "I wosch mei Wischtuach.",
    107: "I trockne meine Wischtiacha.",
    110: "I saug mein Staub aus.",
    111: "Ma fehln de Wischtiacha. Mach's ma bitte dro.",
    112: "Stö mi zerst amoi in de Station.",
    113: "Ferti. Leer bitte'n Schmutzwossatank aus.",
    114: "De Wischtiacha san dro.",
    115: "De Wischtiacha san obe.",
    140: "A neiche Umgebung. I fahr zur Station.",
    148: "I fahr zur Station und mach mi söwa sauba.",
    169: "De Wischtiacha san trocken.",
    177: "I fahr los.",
    179: "S Wischtuach is sauba. Owa s Frischwossa geht ma aus.",
    181: "Ma geht s Wossa aus. Füll ma bitte noch.",
    186: "Schau da bitte'n Frischwossatank au.",
    187: "Des dauert so fünf bis zehn Minutn.",
    188: "I dock automatisch au.",
    209: "Passt scho, i fahr zur Station und wosch mei Wischtuach.",
    210: "I wosch de Wischtiacha.",
    211: "Aussaugn geht nur, wenn i in da Station steh.",
    212: "Passt scho, i saug mi aus.",
    213: "Trocknen geht nur, wenn i in da Station steh.",
    214: "I trockne grod.",
    215: "Passt scho, i fang mit'm Trocknen au.",
    216: "Do muass zerst s Wischtuach dro.",
    278: "Passt scho, s Trocknen is ferti.",
    298: "I mach s Woschbrett sauba.",
    305: "Passt scho, i mach s Woschbrett sauba. Mach des innen mit ana Bürstn sauba.",
    311: "De Wischtiacha san obe.",
    318: "Mei Wischtuach is wieda sauba.",
    349: "Schau, dass de Station Strom hot, und stö mi drauf.",
    350: "I fang mit'm Eirichtn von da Station au.",
    351: "De Station is eigricht.",
    352: "S Eirichtn hot ned highaut. Schau in da App.",
    360: "I loss s Wossa ausm Tank.",
    361: "S Wossa is ausse.",
    371: "Nimm bitte s Woschbrett ausse.",
    372: "S Frischwossa lauft eine.",
    373: "S Wossa is drin. Wart zehn Sekundn, dann geht's weida.",
    374: "Mach'n Bodn von da Station mit ana Bürstn oda am Tuach sauba.",
    375: "Schieb'n Dreck zum Aussaugn hi. Des dauert a bissl.",
    376: "S Aussaugn is ferti. Mach s Woschbrett extra sauba und setz's wieda eine.",
    396: "I mach s Wossamodul leer. Des dauert a bissl.",
    397: "S Wossa is obn und untn ausse.",
    398: "De Kartn is ferti. Schau da's in da App au und stö mi zruck.",
    399: "Da Test is ferti. Stö mi zruck auf de Station.",
    400: "De Selbstreinigung is ferti. Stö mi jetzt aufs richtige Stockwerk.",
    401: "Stö mi auf de Station, dann fang i mit da Selbstreinigung au.",
    478: "Wenn i gwoschn hob, mach i mit'm Saugn weida.",
    479: "Passt scho, fang dei Hackn neich au.",
    480: "Füll gnua Wossa eine, dass's fürs Nächste laungt.",
    481: "I mach'n Handstaubsauger leer.",
    482: "I mach'n Handstaubsauger leer. Mi söwa saug i nacher aus.",
    483: "I mach'n Handstaubsauger leer. S Wischtuach wosch i nacher.",
    484: "I mach'n Handstaubsauger leer. Gsaugt wird nacher.",
    485: "I saug mi grod aus. Da Handstaubsauger kummt nacher.",
    486: "I wosch grod s Wischtuach. Da Handstaubsauger kummt nacher.",
    487: "Schau, dass i in da Station steh.",
    636: "Mei Wischtuach is picken-dreckig. I muass zur Station.",
    638: "I saug mi weida aus.",
    661: "I mach s Woschbrett sauba. Des dauert a knappe Minutn.",
    662: "I mach elektrolysiert's Wossa zum Putzn.",
    689: "I fang au, Staubbehälter und Sackl z'trockna.",
    690: "S Trockna vom Staubbehälter und Sackl is gstoppt.",
    691: "Da Mopp wird grod gwoschn. Probier's späda nomoi.",
    701: "De Plattn is haaß. Bitte ned augreifn.",
    703: "I fang mit da Staub- und Mopptrocknung au.",
    704: "De Mopptrocknung is pausiert.",
    711: "De Desinfektion fangt au.",
    712: "S Woschbrett is haaß. Bitte ned augreifn.",
    715: "In da Station fehlt da Mopp. Setz'n eine, dann mach i weida.",
    716: "In da Station fehlt da Mopp. Setz'n eine - solang hackl i im Standardmodus.",
    717: "Da Mopp sitzt ned richtig. Ruck'n zrecht, dann mach i weida.",
    722: "Da Mopp kummt in haaß's Wossa, damit er woam wird. Drum dauert's a bissl länga. Hob a bissl Geduld.",
    724: "Da Mopp liegt in da Station ned richtig. Ruck'n glei zrecht.",
    728: "I fang mit da Bodnpfleg au.",
    729: "Da Mopp wird grod gwechselt. Probier's späda nomoi.",
    731: "Mei Schmutzwossatank is voi. Stö mi zruck auf de Station, damit i'n Mopp woschn kann.",
    752: "I mach mit da Bodnpfleg weida.",
    754: "I hob mi gfundn. I mach mit da Bodnpfleg weida.",
    757: "Mei Schmutzwossatank is voi. Mach'n glei leer.",
    758: "Z'wenig Wossa. Stö mi zruck auf de Station und druck auf Start, dann wird nochgfüllt.",
    765: "Da Mopp wird grod gwechselt. Probier's späda nomoi.",
    775: "Solang da Mopp lauft, loss de Klappn zua.",
    779: "De Zeit fürs Mopp-Rausnehma is um. I hör auf.",
    780: "S Aufnehma oda Oblegn vom Mopp hot ned klappt. Nimm'n Mopp aus da Hoiterung und leg'n wieda ins Foch bei da Klappn.",
    784: "Wenn Schritt aans ferti is, fahr i von söwa aus da Station.",
    785: "Mach de Woschbrett-Basis bitte mit ana Bürstn oda am Tuach sauba. Nacher tippst in da App auf Reinigung beendn.",
    786: "De Woschbrett-Basis is sauba.",
    787: "I fahr von söwa zur Station zruck und mach'n Mopp sauba und trocken.",
    795: "I fang mit da Reinigung von da Woschbrett-Basis au. Des dauert ungfähr zwaa Minutn.",
    798: "De Selbstreinigung von da Station dauert ungfähr vier Minutn. Schieb mi solang ned umadum.",
    805: "I fang au, den grobn Dreck aufz'saugn.",
    813: "I fang mit da kräftign Absaugung vom Dreck au.",
    814: "I fang mit da Selbstreinigung von da Station und da kräftign Absaugung au.",
    849: "I fang au, Staubbehälter und Sackl z'trockna.",
    850: "S Trockna vom Staubbehälter und Sackl is gstoppt.",
    857: "Setz bitte s Woschbrett eine.",

    # --- Fehler und Wartung ------------------------------------------
    24: "Schau amoi, ob da Wossatank richtig drin steckt.",
    34: "Do fehlt a Teil. Steck des bitte eine.",
    35: "Mit da Hauptbürstn stimmt wos ned. Putz's ma bitte.",
    36: "Mit da Seitenbürstn stimmt wos ned. Putz's ma bitte.",
    37: "Mit'm rechtn Radl stimmt wos ned.",
    38: "Mit'm linkn Radl stimmt wos ned.",
    39: "Meine Radln hängn in da Luft. Mach de Absturzsensorn sauba.",
    40: "Heast, i häng fest. Mochst mi bitte frei?",
    41: "Meine Radln hängn in da Luft. Stö mi woandas hi.",
    42: "Schau da bitte mein Filta au.",
    43: "Mit meim Stoßbügel stimmt wos ned. Druck amoi sanft drauf.",
    44: "Do stimmt wos ned. Schau bitte in da Anleitung noch.",
    52: "I steh schiaf. Stö mi bitte grod hi.",
    66: "Mei Filta is hi. Tausch'n bitte aus.",
    67: "De Seitenbürstn is hi. Tausch's bitte aus.",
    68: "De Hauptbürstn is hi. Tausch's bitte aus.",
    71: "Schau amoi, ob am Laser-Obstandssensor wos klemmt.",
    72: "De Obdeckung vom Lasersensor klemmt.",
    73: "Mit'm Kantensensor stimmt wos ned.",
    75: "Da Filta is feicht oda verstopft.",
    81: "Mit'm Teppichsensor stimmt wos ned.",
    91: "Da Frischwossatank fehlt. Setz'n bitte eine.",
    93: "Z'wenig Wossa drin. Füll bitte noch.",
    97: "Do fehlt s Staubsackl.",
    101: "De Klappn von da Absaugstation is offen oda s Sackl fehlt. Mach de Klappn zua oda leg a Sackl eine.",
    102: "S Staubsackl is voi oda da Kanal is verstopft.",
    104: "S Woschbrett is ned drin. Setz's eine und mach de Klammern auf beide Seitn fest.",
    108: "Mit'm Wossastand vom Woschbrett stimmt wos ned. Mach des sauba.",
    109: "Mit'm Schmutzwossatank stimmt wos ned. Schau, ob a drin und leer is.",
    118: "De Knöpf san gsperrt. Hoit de Tastn an da Station druckt.",
    142: "S Wischtuach is hi. Tausch des bitte aus.",
    156: "Mei Wischtuach is ned dro.",
    166: "Do hot si wos in mei Wischtuach gwickelt. Mach's bitte weg.",
    170: "De Tastnsperr is eigschoitn. Hoit de Tastn an da Station druckt, dann geht's wieda auf.",
    173: "Tausch bitte s Silberionen-Modul aus.",
    244: "De Reinigungsmittelflaschn is dro.",
    245: "Mehr Kartn gehn ned. Lösch bitte aane in da App.",
    248: "S Wischtuach fehlt. Mach des dro und probier's nomoi.",
    266: "Tausch bitte s Reinigungsmittel aus.",
    267: "Meine Sensorn san dreckig. Putz's ma bitte.",
    296: "Schau amoi, ob da Schmutzwossatank voi is.",
    297: "De Reinigungsmittelflaschn is dro. Wenn'st's no nia benutzt host, schau in da App.",
    299: "De Reinigungsmittelflaschn und s Nochfüllmodul san dro.",
    300: "Des Zubehör kenn i ned.",
    312: "Über des Zubehör waaß i nix. Tausch's aus, wenn's hi is.",
    315: "S Wischtuach is ned in da Station. Leg's eine und probier's nomoi.",
    316: "In da Station liegt eh scho a Wischtuach.",
    319: "S Wischtuach is ned obegangen. Nimm's mit da Hand obe.",
    320: "S Wischtuach is ned dro. Mach's mit da Hand dro.",
    329: "I test mi grod söwa. Nimm mi ned von da Station obe.",
    330: "Wart, bis da Selbsttest ferti is.",
    331: "Ois in Ordnung. I hob nix gfundn.",
    332: "I hob an Fehler gfundn. Schau amoi in de App.",
    353: "Da Schmutzwossabehälter is drin.",
    354: "Da Schmutzwossabehälter is ausse.",
    355: "Z'wenig Wossa. Füll'n Frischwossatank noch.",
    356: "Da Fehler is no do. De eigstellte Reinigung is obgsogt.",
    358: "Setz bitte'n Schmutzwossabehälter eine.",
    384: "Im automatischn Wossamodul is kaa Wossa.",
    386: "Mei Schmutzwossabehälter is voi. I fahr zruck und mach'n leer.",
    387: "S Ausleern is ferti. I mach weida.",
    388: "Do derf i ned hi. Stö mi woandas hi.",
    389: "Da Laser fahrt ned obe. Schau, ob wos klemmt.",
    390: "Da Laser fahrt ned aufe. Schau, ob wos klemmt.",
    391: "Stö mi auf a freie Flächn, bevor's losgeht.",
    392: "Im Clean-Genius-Modus geht des ned.",
    393: "Mei Schmutzwossabehälter is dreckig. Mach'n glei sauba.",
    394: "Da Wossasensor mog nimma.",
    426: "I bin ausgrutscht und häng fest. I probier's weida.",
    437: "Passt wieda. Druck auf Start, dann geht's weida.",
    438: "Da Stoßbügel klemmt. Druck amoi sanft drauf.",
    439: "De Laserobdeckung klemmt. Druck amoi sanft drauf.",
    440: "A Radl hängt in da Luft. Stö mi auf a freie Flächn.",
    441: "Do hot si wos um de Hauptbürstn gwickelt. Putz's bitte.",
    442: "Do hot si wos um de Seitenbürstn gwickelt.",
    443: "Um meine Radln hot si wos gwickelt.",
    444: "Stö mi bitte auf a freie Flächn, dann fang i au.",
    445: "Mei Wischtuach is ma obegfoin. Schau amoi in da Nähe.",
    446: "Am Wischtuachhoita hängt wos dro.",
    447: "De Station hot kan Strom. Schau bitte amoi noch.",
    448: "Da Schmutzwossatank fehlt. Setz'n bitte eine.",
    449: "Auf'm Teppich fang i ned au. Stö mi auf'n Hoartbodn.",
    452: "Mit'm Teppichsensor stimmt wos ned. Dreh mi um und mach's waaße Fensterl sauba.",
    453: "Mit'm Kantensensor stimmt wos ned. Mach mi rechts sauba.",
    454: "Z'wenig Wossa im Tank. Füll ma bitte noch.",
    455: "Da Frischwossatank sitzt ned richtig drin.",
    456: "Da Schmutzwossatank is voi oda er fehlt.",
    457: "Da Schmutzwossatank is voi oda ned drin. Schau amoi noch.",
    458: "S Staubsackl sitzt ned richtig.",
    459: "Da Wischtuachhoita sitzt ned richtig. Schau amoi noch.",
    460: "Da Geruchsfilta is verbraucht. Tausch'n bitte aus.",
    639: "Do fehlt da Filta vom Woschbrett.",
    658: "Da Kalkschutz is verbraucht. Tausch'n bitte aus.",
    663: "Mit'm Wossastand im Woschbrett stimmt wos ned. Mach'n Filta sauba.",
    673: "Um meine Haxn hot si vielleicht wos gwickelt. Mach des vor'm Start sauba.",
    674: "Mei Mopp klemmt vielleicht oda hot si wos eingwickelt. Schau noch und mach'n sauba.",
    682: "Mei Mopp dreht si nimma.",
    683: "Da Mopp is ned dro. Mach zerst'n Mopp dro und probier's dann nomoi.",
    696: "Fehler bei da Klappn.",
    699: "Sensorfehler. Schau noch, ob da Kamerasensor dreckig is.",
    706: "Fehler bei'm Kreisl. Bitte de Aufgob nomoi startn.",
    707: "Fehler bei'm Fohrgstell. Bitte de Aufgob nomoi startn.",
    719: "Fehler bei'm Moppwechsel.",
    725: "Fehler bei da Moppobdeckung.",
    726: "Fehler bei'm Rollmopp.",
    755: "Da Lasersensor mog ned. Schau noch, ob do wos dreckig is oda klemmt.",
    771: "Da Rollmopp bleibt stehn oda is blockiert.",
    777: "De Zeit is um. Schau noch, ob unter'm Gerät wos im Weg is.",
    778: "Ochtung, poss auf deine Finger auf.",
    782: "Fehler bei'm Auflockern von da Rolle. Mach's sauba, dann geht's weida.",
    797: "Do stimmt vielleicht wos ned mit'm Gerät. Ruaf bei'm Kundendienst au.",
    799: "De Zeit is um. Schau noch, ob a Viecherl oda a Hindernis unter'm Gerät steht.",
    823: "Da Wossastand im Woschbrett passt ned. Mach's sauba, bevor's losgeht.",
    824: "Da Rollmopp bleibt stehn oda is blockiert.",
    828: "Da Filta is durch. Mach'n boid sauba.",
    915: "Da Wossastand im Woschbrett passt ned. Mach'n Filta sauba, damit nix verstopft.",

    # --- Wegfindung ---------------------------------------------------
    30: "I schau grod, wo i bin.",
    31: "I waaß ned, wo i bin. Dann fang i hoit neich au.",
    45: "I bin do!",
    149: "Do kum i ned hi. Raum bitte weg, wos im Weg steht.",
    151: "Mei Weg is verstöllt. Raum bitte wos weg.",
    153: "I steh in ana Sperrzone. Hol mi do bitte ausse.",
    258: "I fang au zum Umadumfahrn.",
    259: "I fahr do hi, wo'st gsogt host.",
    260: "I fahr weida umadum.",
    261: "I fahr weida do hi.",
    262: "I waaß ned, wo i bin.",
    698: "S Kartnzeichna is ferti. I find de Station ned und fang söwa au zum Reinign.",
    702: "Mit ana vorläufign Kartn kann i ned reinign. Druck nomoi auf Reinigung, dann wird de Kartn gspeichert.",
    723: "Bei'm Kartnzeichna schau, dass ois guat ausgleicht is. Stö nix in de Türn und schieb weda mi no de Station umadum.",

    # --- Bedienung -----------------------------------------------------
    26: "I setz mi zruck auf de Werkseinstellung.",
    27: "I mach a Update. Dauert fünf Minutn. Bitte ned obschoitn.",
    28: "Des Update hot funktioniert.",
    29: "Des Update hot ned funktioniert. Probier's späda nomoi.",
    46: "Roboter und Handy san verbunden.",
    116: "De Kindersicherung is eigschoitn. De Knöpf san gsperrt.",
    117: "De Kindersicherung is aus.",
    162: "De Kamera is eigschoitn.",
    293: "Anruf san eigschoitn.",
    294: "Anruf san aus.",
    338: "Da Videoanruf steht.",
    339: "Anruf oblehnt.",
    340: "Kaane Antwort.",
    364: "I richt'n Videocode ei.",
    365: "S Livebild is aus.",
    421: "Servus. Von jetzt au red i Wienerisch mit dir.",
    463: "Servus, schön, dass'd do bist. Mach'n Deckel auf und scann'n QR-Code.",
    464: "Damit späda ois glatt lauft, stö mi vor'm Start auf de Station.",
    465: "Stö mi vor'm Start auf de Station. Wenn'st I lad grod auf hörst, passt's.",
    466: "Mach bitte de Türn auf und raum'n Bodn frei.",
    467: "Stö mi auf de Station und fang s Zeichnen neich au.",
    468: "Schau da de Kartn bitte in da App au.",
    630: "Servus, schön, dass'd do bist. Mach'n Deckel auf und scann'n QR-Code.",
    631: "Schön, dass'd di für'n Dreame entschiedn host. Mach de Klappn auf und scann'n QR-Code, dann kannst de App ladn.",
    632: "Da Sprochwechsel dauert a hoibe Minutn.",
    633: "Da Sprochwechsel hot ned funktioniert.",
    634: "I fang au, de Hoar z'entwirrn.",
    697: "I bin gsperrt. Mach zerst de Kindersicherung aus.",
    718: "Des losst si im Energiesparmodus ned ändern. Mach'n Energiesparmodus aus und probier's nomoi.",
    910: "Servus und willkommen in da Ausstellung für Saugroboter.",

    # --- Sprachassistent ------------------------------------------------
    190: "Passt, i fang au zum Saugn.",
    191: "Passt, i saug und wisch.",
    192: "Passt, i wisch.",
    193: "Passt, i saug.",
    194: "I bin eh scho am Saugn.",
    195: "Passt scho, i mach des Zimma sauba. Schau, dass de Tür offen is.",
    196: "Passt scho, i saug'n Bodn. Schau, dass de Tür offen is.",
    197: "Passt scho, i wisch'n Bodn. Schau, dass de Tür offen is.",
    198: "Passt scho, i saug und wisch. Schau, dass de Tür offen is.",
    199: "Des Zimma kenn i ned. Schau in da App, wia's haaßt.",
    200: "Baba.",
    201: "Passt scho, i mach weida.",
    202: "Passt scho, i hör auf und fahr zum Ladn.",
    203: "Passt scho, i fahr zum Ladn.",
    204: "Passt scho, i fang mit'm Zeichnen au. Mach bitte olle Türn auf.",
    205: "Passt scho, i fahr von da Station obe.",
    206: "Passt scho, i schau, wo'st bist.",
    207: "I find di ned. Stö di in mei Sichtweitn.",
    208: "Do bist ja. I kum saugn.",
    217: "Mehr Saugkroft geht ned.",
    218: "Weniger Saugkroft geht ned.",
    219: "Mehr Wossa geht ned.",
    220: "Weniger Wossa geht ned.",
    221: "Passt scho.",
    222: "Saugstufn leise.",
    223: "Saugstufn normal.",
    224: "Saugstufn stork.",
    225: "Saugstufn Turbo.",
    226: "S Wischtuach is leicht feicht.",
    227: "S Wischtuach is feicht.",
    228: "S Wischtuach is noss.",
    229: "Heit is",
    230: "Heit is da aanazwanzigste Februar zwaatausendzwaaundzwanzig.",
    231: "Heit is Monta.",
    232: "Heit is Diensta.",
    233: "Heit is Mittwoch.",
    234: "Heit is Donnersta.",
    235: "Heit is Freita.",
    236: "Heit is Samsta.",
    237: "Heit is Sonnta.",
    238: "Passt scho, i hör auf.",
    246: "I bin do hintn!",
    247: "Des hob i jetzt ned verstandn.",
    249: "I hackl grod. Mach des zerst ferti, dann geht's.",
    250: "I bin grod im Wischmodus. Stö bitte um.",
    251: "I bin grod im Saugmodus. Stö bitte um.",
    252: "Ferti. I bin aus da eigstelltn Reinigung ausse.",
    253: "Lauta geht ned.",
    254: "Leiser geht ned.",
    255: "Des geht nur mit eigschoitna Hindernisumfahrung.",
    269: "Probier's nomoi, wenn i ferti bin.",
    275: "Des kenn i ned. In da App stengan olle Sprochbefehle.",
    276: "Des mach i grod ned.",
    277: "Passt scho, i kum und mach do sauba.",
    279: "I saug grod. Mach des zerst ferti und probier's nomoi.",
    281: "I saug mi grod aus. Probier's glei nomoi.",
    282: "I wosch grod mei Wischtuach. Probier's glei nomoi.",
    283: "I steh ned in da Station. Probier's späda nomoi.",
    284: "Passt scho, i hör auf und kum saugn.",
    285: "Bleib kurz stehn, i schau, wo'st bist.",
    286: "Do brauch i zerst a Kartn.",
    287: "Passt scho, jetzt is leise.",
    288: "Passt scho, jetzt is normal.",
    289: "Passt scho, jetzt is stork.",
    290: "Passt scho, jetzt is Turbo.",
    291: "Passt scho, jetzt is leicht feicht.",
    292: "Passt scho, jetzt is noss.",
    308: "Des hob i ned mitkriagt. Weck mi nomoi.",
    309: "Do bist ja, i kum.",
    310: "Passt scho, i fahr glei do weg.",
    314: "Des geht ned. Owa du kannst ma sogn, i soi mi umdrahn.",
    317: "Des geht grod ned, i mach a eigstellte Reinigung.",
    322: "Des kenn i ned. In da App stengan olle Sprochbefehle.",
    323: "Des kenn i ned. Frog mi amoi, wos i ois ka.",
    324: "I wosch mi grod. Weck mi, wenn i ferti bin.",
    328: "Des kannst ma nur sogn, wenn i grod saug.",
    341: "Do bist ja. I geh da noch. Sog Ende, wenn's gnua is.",
    342: "Wo bist? Stö di ungfähr andahoib Meter vor mi.",
    343: "I hob di verlorn. Du bist z'schnö. Stö di andahoib Meter vor mi.",
    489: "I bin im Clean-Genius-Modus. Sog ma, i soi aufhörn.",
    490: "Passt scho, eigstellte Reinigung: i wisch.",
    491: "Passt scho, eigstellte Reinigung: i saug.",
    508: "I red lauta.",
    509: "I red leiser.",
    510: "Guat, i hör auf für heit.",
    511: "I mach grod goa nix.",
    512: "In da Kartn is no kaa Tiermöbel. Trog des in da App ei.",
    513: "Passt scho, i mach ums Tiermöbel umadum sauba.",
    515: "Sei so guat und heb amoi de Füß.",
    516: "I schau, wo dei Viecherl steckt.",
    517: "I hob's gfundn. I fahr zum Ladn.",
    518: "I hob kaans gfundn. I fahr zum Ladn.",
    522: "Wos is denn schiefganga?",
    523: "Kannst ma des a bissl genauer sogn?",
    524: "Nimm mi do hi, wo's passiert is.",
    525: "Wart kurz, i schau ma des au.",
    641: "Sog ma afoch, i soi saugn.",
    642: "Sog ma afoch, i soi störka saugn.",
    643: "Sog ma afoch, i soi mehr Wossa nehma.",
    644: "Sog ma afoch, i soi saugn und wischn.",
    645: "Sog ma afoch, i soi wischn.",
    646: "Sog ma afoch, i soi do hi kumma und sauba mochn.",
    647: "Sog ma afoch, i soi zerst saugn und nacher wischn.",
    648: "Sog ma afoch, i soi ois sauba mochn.",
    659: "Des hob i ned verstandn. Frog mi amoi, wos i ois ka.",
    660: "Tschuidigung, des hob i ned verstandn. Sog Hey Rover, wos kannst du, dann sog i da, wos i ois ka.",
    664: "Sog zu mir: Hey Rover, fang au zum Reinign.",
    665: "Wenn ois passt, sog zu mir: Hey Rover, fang au zum Reinign.",
    666: "Sog zu mir: Hey Rover, mach de Saugkroft störka.",
    667: "Sog zu mir: Hey Rover, gib mehr Wossa.",
    668: "Sog zu mir: Hey Rover, fang au zum Saugn. Späda sogst wischn, dann wechsel i'n Modus.",
    669: "Sog zu mir: Hey Rover, fang au zum Wischn. Späda kannst'n Modus wechseln.",
    670: "Sog zu mir: Hey Rover, kum her und mach do sauba.",
    671: "Sog zu mir: Hey Rover, fang au zum Saugn. Späda kannst'n Modus wechseln.",
    672: "Sog zu mir: Hey Rover, fang au zum Reinign. Späda kannst de ganze Wohnung mochn lossn.",
    694: "Sog ma afoch, i soi saugn.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestätigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Da Akku is auf {p} Prozent.'
RAUM_MUSTER = 'Passt, i mach {raum} sauba.'
RAUM_NAMEN = {
    'wohnzimmer': 's Wohnzimma',
    'schlafzimmer': 's Schlofzimma',
    'hauptschlafzimmer': 's Hauptschlofzimma',
    'gaestezimmer': 's Gästezimma',
    'arbeitszimmer': 's Arbeitszimma',
    'kueche': 'd Kuchl',
    'esszimmer': 's Esszimma',
    'bad': 's Bad',
    'balkon': 'n Balkon',
    'flur': 'n Vorraum',
    'hauswirtschaftsraum': 'd Waschkuchl',
    'abstellraum': 's Kabinett',
    'salon': 'n Salon',
    'buero': 's Büro',
    'gym': 'n Fitnessraum',
    'freizeitraum': 'n Freizeitraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))
